### ISSUE TITLE
保存的日志超过7天没有自动删除

### ISSUE THREAD

**Issue by a130785** [Meituan-Dianping/Logan#102]
之前看到有的Issues上有回答，说保存的日志超过7天的回自动删除，就是默认只会保留7天的日志，但是我iOS手机有10几天的日志，这是怎么回事

**Comment by jiangteng** [comment]
自动删除过期日志文件有个小bug，预计今晚会发个修复后的版本。

**Comment by jiangteng** [comment]
Logan 1.2.3版本，日志超过7天的回自动删除。
