### ISSUE TITLE
本地设置日志文件删除天数的问题

### ISSUE THREAD

**Issue by Sawep** [Meituan-Dianping/Logan#103]
Android 初始配置时可以通过config.setData()来设置本地日志删除天数，但iOS好像没有设置删除天数的方法？

**Comment by Richard-Cao** [comment]
#102

**Comment by Sawep** [comment]
此问题和 #102 问题非同一问题，#102 问题是超过7天本地日志并不会删除，而我想请问的是如何设置删除天数，比如我想让日志保留在本地20天，超过20天的日志才进行删除，该如何设置？

**Comment by Richard-Cao** [comment]
> 此问题和 #102 问题非同一问题，#102 问题是超过7天本地日志并不会删除，而我想请问的是如何设置删除天数，比如我想让日志保留在本地20天，超过20天的日志才进行删除，该如何设置？

@jiangteng

**Comment by jiangteng** [comment]
目前版本iOS没有提供设置保存本地日志文件天数，统一默认7天。本周6可以提供一个设置保存本地日志文件天数的版本。

**Comment by jiangteng** [comment]
iOS Logan 1.2.4 支持设置本地保存最大文件天数。
@Sawep 
**API**
```
/**
 设置本地保存最大文件天数

 @param max_reversed_date 超过该文件天数的文件会被Logan删除，默认7天
 */
extern void loganSetMaxReversedDate(int max_reversed_date);
```

**Comment by Sawep** [comment]
好的谢谢
