### ISSUE TITLE
让日志保持能写入状态，保留最新

### ISSUE THREAD

**Issue by JoesRain** [Meituan-Dianping/Logan#104]
修改clogan_core.c文件

clogan_write 方法

 

if (logan_model->file_len > max_file_len) {

            char *filePath = malloc(strlen(logan_model->file_path));

            memcpy(filePath, logan_model->file_path, strlen(logan_model->file_path));

            

            char *newPath = malloc(strlen(filePath)+5);

            memset(newPath, 0 , strlen(filePath)+5);

            memcpy(newPath, filePath, strlen(filePath));

            strcat(newPath, "_copy");

 

            FILE *fp_to;

            int len;                            //获取文件长度

            char *ch=NULL;            //缓存buffer

            fflush(logan_model->file);                                        //刷新文件

            

            if ((fp_to=fopen(newPath,"w+"))==NULL)                //打开目标文件

            {

                return CLOAGN_WRITE_FAIL_MAXFILE;

            }

            

            len=ftell(logan_model->file);                //获取源文件长度

            ch=(char *)malloc(sizeof(char *)*(len));                //动态分配数组长度

            memset(ch,0,len);                            //清零，否则无法将内容写入！！！

            

            rewind(logan_model->file);                            //将源文件指针复位到开头，否则写入为空！

            fread(ch,1,len,logan_model->file);                //将源文件内容写到buffer中

            fwrite(ch,1,len,fp_to);                    //将buffer中的内容写回到目标文件中

            

            fclose(logan_model->file);                            //关闭文件

            fclose(fp_to);

            

            remove(filePath);

            logan_model = NULL;

            char *filename = strrchr(filePath, '/')+1;

            clogan_open(filename);

        }

**Comment by Richard-Cao** [comment]
你想要表达什么……

**Comment by JoesRain** [comment]
目前的日志库，1天最多只能写入固定长度的内容，10M日志，然后就不能写入了。最好的办法是仍然让它可以写入，但是保留最新的内容，总的长度在10M内就可以了。

**Comment by JoesRain** [comment]
> 你想要表达什么……

目前的日志库，1天最多只能写入固定长度的内容，10M日志，然后就不能写入了。最好的办法是仍然让它可以写入，但是保留最新的内容，总的长度在10M内就可以了。

**Comment by Richard-Cao** [comment]
现在的策略是丢弃新写入的，10m不是写死的，你可以定制，但是日志肯定不是无限大，很多情况下保留原有的内容会更有参考价值
