### ISSUE TITLE
请教日志上传成功后数据删除问题

### ISSUE THREAD

**Issue by yinjining** [Meituan-Dianping/Logan#105]
看到只有清除本地所有日志，即直接把文件给删除了。有没有可以删除文件部分内容的方法，即操作文件内容？

**Comment by yinjining** [comment]
还有，上传过程中需要继续添加日志，这块直接对文件进行删除操作，会不会出现丢日志的情况？

**Comment by Richard-Cao** [comment]
> 看到只有清除本地所有日志，即直接把文件给删除了。有没有可以删除文件部分内容的方法，即操作文件内容？

删的是当天的.copy文件，可以看下demo的写法

**Comment by Richard-Cao** [comment]
> 还有，上传过程中需要继续添加日志，这块直接对文件进行删除操作，会不会出现丢日志的情况？

并不会在上传过程中删除日志

**Comment by yinjining** [comment]
> > 还有，上传过程中需要继续添加日志，这块直接对文件进行删除操作，会不会出现丢日志的情况？
> 
> 并不会在上传过程中删除日志

日志会在什么时机删除？上传成功后不删除吗？

**Comment by Richard-Cao** [comment]
> > > 还有，上传过程中需要继续添加日志，这块直接对文件进行删除操作，会不会出现丢日志的情况？
> > 
> > 
> > 并不会在上传过程中删除日志
> 
> 日志会在什么时机删除？上传成功后不删除吗？

README中建议只删除.copy文件，这个只会在上传当天日志文件的时候生成。源文件不需要删除，过期之后会自动删除。目前期限为7天，可以通过config设置
