### ISSUE TITLE
关于加密解密

### ISSUE THREAD

**Issue by weiweiForAndroid** [Meituan-Dianping/Logan#107]
能把加密给关掉么？

**Comment by Richard-Cao** [comment]
不能。
顺便问下出于什么原因要关掉？

**Comment by weiweiForAndroid** [comment]
目前日志是上传到oss ，没有做界面，或者后端的解密。

**Comment by Richard-Cao** [comment]
后端加一下解密解压的处理吧，日志明文存储存在挺大的安全隐患，如何解密解压可以使用java的parser，其他语言可以参照实现相应的版本。
