### ISSUE TITLE
上传日志

### ISSUE THREAD

**Issue by weiweiForAndroid** [Meituan-Dianping/Logan#108]
![image](https://user-images.githubusercontent.com/7279815/59757594-b20abb00-92be-11e9-8293-e811bf58c9a8.png)
上传日志的runnable不执行

**Comment by Richard-Cao** [comment]
要看下是不是你本地没有这一天的日志，和demo对比一下。

**Comment by weiweiForAndroid** [comment]
@Richard-Cao  现在执行了，但是根据返回的File 路径 在设备中找不到，只看到了mmap 的文件。
