### ISSUE TITLE
padding === 1能执行到吗？

### ISSUE THREAD

**Issue by fengbianyun** [Meituan-Dianping/Logan#109]
let padding = 0
if (padding1 > 1 && padding1 === padding2) {
        padding = padding1;
      } else if (padding === 1) {
        padding = padding1;
      }

**Comment by fengbianyun** [comment]
server.js中的这个方法，我看着貌似执行不到 @cyndibaby905  @chenyihu

**Comment by jiangteng** [comment]
写日志时，如果只填充了一个位的话，那padding就等于1。其他情况就不会为1。
现在执行不到这行，是因为没有命中这种情况

**Comment by fengbianyun** [comment]
> 写日志时，如果只填充了一个位的话，那padding就等于1。其他情况就不会为1。
> 现在执行不到这行，是因为没有命中这种情况

当前我的app一直在运行中，也没有出现只写部分日志，但是解析的时候总是出现{ Error: unexpected end of file     at Zlib.zlibOnError [as onerror] (zlib.js:154:17) errno: -5, code: 'Z_BUF_ERROR' }
最后的错误是：
{ Error: invalid code lengths set
    at Zlib.zlibOnError [as onerror] (zlib.js:154:17) errno: -3, code: 'Z_DATA_ERROR' }
我看了以前的问题，说是日志没写完才会出现这种情况。日志没写完要么APP突然间被杀了，要么写了一部分其他没写进去。我这APP一直在前台运行，按理说应该不会出现这种情况啊

**Comment by jiangteng** [comment]
> 我这APP一直在前台运行，按理说应该不会出现这种情况啊。把数据清空了，一开始OK，运行一段时间又这样。
APP一直在前台运行？没有APP杀死的情况出现？要不你在APP初始化时写入一个Log，如果看看解析出的日志截断部分后面是不是紧跟着 **APP初始化时写入一个Log** 时的Log
