### ISSUE TITLE
iOS 

### ISSUE THREAD

**Issue by nillcui** [Meituan-Dianping/Logan#111]
按照文档说明在pod文件中添加
source 'https://github.com/CocoaPods/Specs.git'
        pod 'Logan', '~> 1.2.5'

执行pod install后报错：
[!] CocoaPods could not find compatible versions for pod "Logan":
  In Podfile:
    Logan (~> 1.2.5)

None of your spec sources contain a spec satisfying the dependency: `Logan (~> 1.2.5)`.

难道没有1.2.5这个版本？

**Comment by gilnuy** [comment]
去掉版本，让pod自己找

**Comment by jiangteng** [comment]
> Logan (~> 1.2.5)

你再试下，发版本延迟问题

**Comment by nillcui** [comment]
好了！谢谢。
