### ISSUE TITLE
调用了Android 9.0非SDK接口

### ISSUE THREAD

**Issue by txlbupt** [Meituan-Dianping/Logan#112]
Reflection blacklist Ljava/lang/Runtime;->loadLibrary0 use(s):
       Lcom/dianping/logan/c;->a(Ljava/lang/String;Ljava/lang/Class;)Z
使用 veridex 工具进行静态扫描的时候提示调用了黑名单中的非SDK接口

**Comment by Richard-Cao** [comment]
这个后期我们会考虑去掉，替换成系统api，感谢反馈。

**Comment by walfud** [comment]
```java
static {
    if (!Util.loadLibrary(LIBRARY_NAME, CLoganProtocol.class)) {
          System.loadLibrary(LIBRARY_NAME);
     }

     ....
}
```

请问这里是为什么需要在 Utils 中使用 loadLibrary0 呢?

**Comment by Richard-Cao** [comment]
> ```java
> static {
>     if (!Util.loadLibrary(LIBRARY_NAME, CLoganProtocol.class)) {
>           System.loadLibrary(LIBRARY_NAME);
>      }
> 
>      ....
> }
> ```
> 
> 请问这里是为什么需要在 Utils 中使用 loadLibrary0 呢?

这个是针对一些机型加载so失败的情况做一些兼容。

**Comment by walfud** [comment]
> > ```java
> > static {
> >     if (!Util.loadLibrary(LIBRARY_NAME, CLoganProtocol.class)) {
> >           System.loadLibrary(LIBRARY_NAME);
> >      }
> > 
> >      ....
> > }
> > ```
> > 
> > 
> > 请问这里是为什么需要在 Utils 中使用 loadLibrary0 呢?
> 
> 这个是针对一些机型加载so失败的情况做一些兼容。

好的, 感谢
