### ISSUE TITLE
log写入之后上传文件出现中文乱码情况

### ISSUE THREAD

**Issue by SuperDannyBoy** [Meituan-Dianping/Logan#115]
![51562828829_ pic_hd](https://user-images.githubusercontent.com/5237197/61032240-a315b500-a3f3-11e9-8725-0ee3e2971717.jpg)
这边使用宏定义的方式进行日志采集。发现上传的日志文件内容出现了中文乱码的情况。
具体宏定义如下：
`#define NSLog(format, ...) logan(1, [NSString stringWithFormat:@"\n[%s] %s (第%d行) %@\n", __TIME__, __FUNCTION__, __LINE__, [NSString stringWithFormat:format, ## __VA_ARGS__]]);`

**Comment by jiangteng** [comment]
这日志中有些中文是好，有些中文是乱码。其中requestSuccess中文是乱码，有没有可能requestSuccess的中文本身的编码格式不对，不是utf8。

**Comment by SuperDannyBoy** [comment]
中文部分是宏定义写死的中文。然后乱码的是动态加入的

**Comment by jiangteng** [comment]
先把动态加入的字符串写死固定的中文？试试

**Comment by SuperDannyBoy** [comment]
写死的中文写入是正常的。是否可以确定是返回来的动态数据编码问题？

**Comment by SuperDannyBoy** [comment]
我查看了一些动态注入的字符串是这边使用mj_JSONString解析服务器返回来的数据，将数据使用mj提供的方式转成字符串类型。不过这个mj_JSONString内部的实现我看了是有转成utf8
`- (NSString *)mj_JSONString
{
    if ([self isKindOfClass:[NSString class]]) {
        return (NSString *)self;
    } else if ([self isKindOfClass:[NSData class]]) {
        return [[NSString alloc] initWithData:(NSData *)self encoding:NSUTF8StringEncoding];
    }
    
    return [[NSString alloc] initWithData:[self mj_JSONData] encoding:NSUTF8StringEncoding];
}`

**Comment by jiangteng** [comment]
先在这里打个断点，看看里显示出来的中文是不是乱码

**Comment by SuperDannyBoy** [comment]
这边的NSLog在控制台上面打印都是中文的。另外我看到debug模式执行
logan(1, [NSString stringWithFormat:@"\n[%s] %s (第%d行) %@\n", __TIME__, __FUNCTION__, __LINE__, [NSString stringWithFormat:format, ## __VA_ARGS__]]);也是可以正常打印出中文。

**Comment by SuperDannyBoy** [comment]
![7EC42877-A560-450F-A85D-42CA98B54D1E](https://user-images.githubusercontent.com/5237197/61042181-496ab600-a406-11e9-994b-480861251f04.png)
这个截图是在控制台打印出来的。因为项目一直在用这种打印方式。
第一个是logan打印出来的，第二个是`printf("\n[%s] %s (第%d行) %s\n", __TIME__, __FUNCTION__, __LINE__, [[NSString stringWithFormat:format, ## __VA_ARGS__] UTF8String]);`打印出来的

**Comment by jiangteng** [comment]
打印都是好的，解析出来就有问题，这太奇怪了

**Comment by SuperDannyBoy** [comment]
这边在自己的笔记本上面部署了一下服务器。然后上传之后的文件就不会乱码，但是用另一台mac电脑部署的上传就乱码。
