### ISSUE TITLE
压缩和加密

### ISSUE THREAD

**Issue by jxppp** [Meituan-Dianping/Logan#120]
文件已有压缩加密的日志，那么再写入新的日志是如何压缩加密呢？另外解压缩解密如何保证不会失败的呀？

**Comment by Richard-Cao** [comment]
先压缩加密再写入。

**Comment by jxppp** [comment]
哦，我的意思是多条日志加密写入同一份文件，到时候从文件一次读出来解密应该只有第一条成功吧，可能是我加密算法了解的不多，我这里想的是每次写入一条加密日志都带上一个特殊字符做间隔。

**Comment by Richard-Cao** [comment]
写入是有序的呀
