### ISSUE TITLE
loganFlash拼写错误，吐槽一下

### ISSUE THREAD

**Issue by iamlion** [Meituan-Dianping/Logan#124]
我们项目组老项目cocopads 1.4.0 只能装到 v1.2.1  方法名为 loganFlash
我们的日志组件基于 Logan v1.2.5 开发，方法名为 loganFlush
升级引用的时候直接导致我们项目编译错误，“undefined unsymbol _lognFlush” 心累
如果要更新新版本，还需要我们开发成员更新本地cocopads索引

**Comment by jiangteng** [comment]
是的，有个拼写错误。
