### ISSUE TITLE
日志解析的时候发生异常

### ISSUE THREAD

**Issue by LeqiangBian** [Meituan-Dianping/Logan#128]
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:118)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at LoganParser.parse(LoganParser.java:86)
	at Test.main(Test.java:15)

这是使用了LoganParser.java这个工具解析日志文件过程中报的错，报错位置：
![image](https://user-images.githubusercontent.com/20633364/63482087-2d106d80-c4ca-11e9-9ca0-2a55994b0d83.png)

想向作者了解一下怎么修复这个bug

**Comment by LeqiangBian** [comment]
希望作者可以沟通一下，谢谢。

**Comment by Richard-Cao** [comment]
报了这个问题之后有日志被截断的现象吗？

**Comment by njuxjy** [comment]
我也遇到日志解析异常的情况。 

有些写入的日志不是合法的json串，导致服务端json序列化失败。

**Comment by Richard-Cao** [comment]
建议在app切换到后台的时候，调用一下flush，目前我们发现反馈截断的用户里绝大多数的截断都发生在切到后台的情况。

**Comment by njuxjy** [comment]
> 建议在app切换到后台的时候，调用一下flush，目前我们发现反馈截断的用户里绝大多数的截断都发生在切到后台的情况。

Logan.m中已经监听了进入后台前台等情况，做过flush了

**Comment by jiangteng** [comment]
由于异常情况，会出现一些日志缺少压缩结束符，会有少量日志出现截断现象丢失少量信息情况。@njuxjy  你那边是详细情况是什么？

**Comment by caiqingchong1989** [comment]
确实是这样的，应用切到后台日志有截断的现象，每次都会发生

**Comment by Richard-Cao** [comment]
> 我这里也发生了，应用切到后台日志有截断的现象，每次都会发生

app到后台的时候，flush一下

**Comment by caiqingchong1989** [comment]
> > 我这里也发生了，应用切到后台日志有截断的现象，每次都会发生
> 
> app到后台的时候，flush一下

程序被强制杀死的时候也会报这个错误，然而强制杀死是没有任何通知的。。。

**Comment by caiqingchong1989** [comment]
> > 我这里也发生了，应用切到后台日志有截断的现象，每次都会发生
> 
> app到后台的时候，flush一下

应用被强制杀死，或者其他情况进程被杀死的情况下，也会出现这种异常，请问现在有解决方案吗？

**Comment by Richard-Cao** [comment]
> > > 我这里也发生了，应用切到后台日志有截断的现象，每次都会发生
> > 
> > 
> > app到后台的时候，flush一下
> 
> 应用被强制杀死，或者其他情况进程被杀死的情况下，也会出现这种异常，请问现在有解决方案吗？

应用被强杀再打开会残缺，能复现？

**Comment by caiqingchong1989** [comment]
> > > > 我这里也发生了，应用切到后台日志有截断的现象，每次都会发生
> > > 
> > > 
> > > app到后台的时候，flush一下
> > 
> > 
> > 应用被强制杀死，或者其他情况进程被杀死的情况下，也会出现这种异常，请问现在有解决方案吗？
> 
> 应用被强杀再打开会残缺，能复现？

adb shell am force-stop xxx  模拟强制被杀 应用不走任何回调，无法flush，下次在打开应用flush就会出现丢失，100%复现

**Comment by jiangteng** [comment]
> > > 我这里也发生了，应用切到后台日志有截断的现象，每次都会发生
> > 
> > 
> > app到后台的时候，flush一下
> 
> 应用被强制杀死，或者其他情况进程被杀死的情况下，也会出现这种异常，请问现在有解决方案吗？

如果应用被异常杀死，会出导致最后一条日志缺少压缩结束符，导致后端解析时出现截断的现象。目前没有兼容这种情况

**Comment by ktoy1943** [comment]
我也遇到 测试反馈日志经常出现这个解析异常

**Comment by Richard-Cao** [comment]
> 我也遇到 测试反馈日志经常出现这个解析异常

应用切到后台的时候，flush一下？

**Comment by ktoy1943** [comment]
> > 我也遇到 测试反馈日志经常出现这个解析异常
> 
> 应用切到后台的时候，flush一下？

是的 ,每个页面销毁 或者 不可见的时候 都调用 Logan.f ()了.还有其他方法能避免吗

**Comment by Richard-Cao** [comment]
目前的情况就是在应用切到后台的时候，f一下，倒不用每个页面销毁都f

**Comment by JackyAndroid** [comment]
这个问题能直接定位下，彻底解决下吗

**Comment by Richard-Cao** [comment]
> 这个问题能直接定位下，彻底解决下吗

使用Logan开源的后端试试呢

**Comment by JackyAndroid** [comment]
@Richard-Cao 我们是在端上使用，这个问题最好能从根本上解决下，或者有方案大家一起做也可以。
而且就算是在应用后台主动flush可以避免，但后台应用或服务还是没办法使用，应用和后台服务在极端情况还是会丢日志，奔溃是比较常见的情景，现在崩溃就是会丢日志的把。

**Comment by Richard-Cao** [comment]
> @Richard-Cao 我们是在端上使用，这个问题最好能从根本上解决下，或者有方案大家一起做也可以。
> 而且就算是在应用后台主动flush可以避免，但后台应用或服务还是没办法使用，应用和后台服务在极端情况还是会丢日志，奔溃是比较常见的情景，现在崩溃就是会丢日志的把。

并不是崩溃就会丢日志哦，https://tech.meituan.com/2018/02/11/logan.html

**Comment by jiangteng** [comment]
> 吗

崩溃是被异常杀死的一种，所有异常关闭都会导致最后一条日志缺少压缩结束符。

**Comment by jiangteng** [comment]
> @Richard-Cao
> 
> > 我这里也发生了，应用切到后台日志有截断的现象，每次都会发生
> 
> > app到后台的时候，flush一下
> 
> > 应用被强制杀死，或者其他情况进程被杀死的情况下，也会出现这种异常，请问现在有解决方案吗？
> 
> > adb shell am force-stop xxx 模拟强制被杀 应用不走任何回调，无法flush，下次在打开应用flush就会出现丢失，100%复现
> 
> > 如果应用被异常杀死，会出导致最后一条日志缺少压缩结束符，导致后端解析时出现截断的现象。目前没有兼容这种情况
> 
> 引用如上讨论：
> 
> 1. “模拟强制被杀，下次在打开应用flush就会出现丢失“（说明mmap  cache回写还是不能弥补截断日志）
> 2. “应用被异常杀死，导致最后一条日志缺少压缩结束符，导致后端解析时出现截断的现象”
> 
> 请问崩溃算不算被异常杀死的一种，崩溃不会导致最后一条日志缺少压缩结束符而导致无法解压丢失吗？

崩溃是被异常杀死的一种，所有异常关闭都会导致最后一条日志缺少压缩结束符。

**Comment by JackyAndroid** [comment]
@jiangteng 为什么要关掉？

**Comment by jiangteng** [comment]
这个问题，应该已经解释清楚了。如果有其他的疑问可以新建issues方便问题归类

**Comment by JackyAndroid** [comment]
@jiangteng 那就是奔溃会丢日志，而且短期还解决不了？那issue应该保留啊

**Comment by jiangteng** [comment]
关于异常时最后一条日志问题，建议你重新起个issue。因为这个主题讲的是后端解析时异常现象，这个异常现象从功能本质上来讲是正常的。

**Comment by wsxyeah** [comment]
Logan 在进行加密时，以 16 字节为单位对数据做了分块。
如果字节数不是 16 的整数倍，余下的数据不会被立即写入缓冲，而是先保存在内存里，等待下条日志写入或者 flush 的时候再写入。如果进程被杀时没仍写入缓冲，这部分数据会永久丢失。

个人想到的解决方案：
1. 加密时做 padding 处理
2. 将余下的数据写入一块单独的缓冲，进程下次启动时尝试恢复

**Comment by feng-tianyou** [comment]
> > [@Richard-Cao](https://github.com/Richard-Cao)
> > > 我这里也发生了，应用切到后台日志有截断的现象，每次都会发生
> > 
> > 
> > > app到后台的时候，flush一下
> > 
> > 
> > > 应用被强制杀死，或者其他情况进程被杀死的情况下，也会出现这种异常，请问现在有解决方案吗？
> > 
> > 
> > > adb shell am force-stop xxx 模拟强制被杀 应用不走任何回调，无法flush，下次在打开应用flush就会出现丢失，100%复现
> > 
> > 
> > > 如果应用被异常杀死，会出导致最后一条日志缺少压缩结束符，导致后端解析时出现截断的现象。目前没有兼容这种情况
> > 
> > 
> > 引用如上讨论：
> > 
> > 1. “模拟强制被杀，下次在打开应用flush就会出现丢失“（说明mmap  cache回写还是不能弥补截断日志）
> > 2. “应用被异常杀死，导致最后一条日志缺少压缩结束符，导致后端解析时出现截断的现象”
> > 
> > 请问崩溃算不算被异常杀死的一种，崩溃不会导致最后一条日志缺少压缩结束符而导致无法解压丢失吗？
> 
> 崩溃是被异常杀死的一种，所有异常关闭都会导致最后一条日志缺少压缩结束符。

如果这个文件一直缺少压缩符，继续写入日志，重新上传这个文件也会解析错误
