### ISSUE TITLE
server.js  出现Error

### ISSUE THREAD

**Issue by jorry** [Meituan-Dianping/Logan#13]
**部分Log:**
start decode log file
decrypt complete
remove padding complete
{ Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:355:17) errno: -5, code: 'Z_BUF_ERROR' }

start decode log file
decrypt complete
remove padding complete
write finish

start decode log file
decrypt complete
remove padding complete
write finish

start decode log file
decrypt complete
remove padding complete
write finish

start decode log file
decrypt complete
remove padding complete
write finish

start decode log file
decrypt complete
remove padding complete
{ Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:355:17) errno: -5, code: 'Z_BUF_ERROR' }

start decode log file
decrypt complete
remove padding complete
write finish

可以创建log-demo.txt文件，并且有日志内容

**Comment by Richard-Cao** [comment]
内容全就可以，这是针对日志残缺的情况，尽量多解析其他部分。
