### ISSUE TITLE
mmap读写转io普通读写

### ISSUE THREAD

**Issue by yinjining** [Meituan-Dianping/Logan#130]
请教一下，mmap读写失败了会转io普通文件读写，想咨询下mmap读写失败的场景？为什么会失败呢？

**Comment by jiangteng** [comment]
那段代码，方便贴一下吗？

**Comment by yinjining** [comment]
@jiangteng 我就是找不到场景才会问，看到mmap读写是为了减少io读写，mmap读写失败会转io读写，网上也说mmap读写会经常失败，但是我找不到场景，不太明白为什么会失败，知道的麻烦解释下mmap读写为什么会失败？

**Comment by jiangteng** [comment]
> mmap读写失败了会转io普通文件读写

你问的是Logan问题吗？能把这段代码贴一下吗？

不同的业务有着不同的情况，我只能解释Logan中发生mmap读写失败情况。问为什么前，我要确认一下是不是，所以你要先指明是那一段代码。
