### ISSUE TITLE
请教一个问题。

### ISSUE THREAD

**Issue by hitYOUcry** [Meituan-Dianping/Logan#131]
你好，想请教下，对于需要实时上传到后台的统计日志（广告点击、app下载行为等等），为了保证不丢日志，会需要先把日志存储在本地，当上报完成之后再删除本地的缓存。

你觉得这类日志适合用logan这种基于mmap的处理方式做本地存储吗，相比于用DB存储会有优势吗？目前是用DB存储，往DB写数据稍微有些耗时（但没有打印log时写文件那样耗时）。

**Comment by jiangteng** [comment]
我觉得这种用DB存储就好，因为实时上报日志主要的担心是请求失败了导致后端日志数据发生了丢失。
并且很多DB内部用mmap做的。比如：sqlite。

**Comment by hitYOUcry** [comment]
所以Android提供的SQLiteDatabase是基于mmap来写数据到db文件的么？找到资料比较少，这点不太确认。

**Comment by jiangteng** [comment]
可以看一下这个。
http://sqlite.1065341.n5.nabble.com/Enabling-MMAP-in-Android-td99149.html
