### ISSUE TITLE
是否能允许初始化的时候使用不加密的方式

### ISSUE THREAD

**Issue by kugarliyifan** [Meituan-Dianping/Logan#138]
是否能允许初始化的时候使用不加密的方式,,也就是日志文件不加密

**Comment by jiangteng** [comment]
这个功能还暂未支持

**Comment by kugarliyifan** [comment]
那么如果本地要读取的话,怎么查看?

**Comment by Richard-Cao** [comment]
本地起个demo的server看一下了

**Comment by thinkfeed** [comment]
能不能改成可配置的，毕竟加密不是必须要的功能

**Comment by Richard-Cao** [comment]
> 能不能改成可配置的，毕竟加密不是必须要的功能

目前还不支持哦，不过从使用角度出发，本地日志存储的时候加密是必要的功能哦
