### ISSUE TITLE
Android的sdk，没法使用

### ISSUE THREAD

**Issue by Gongcong** [Meituan-Dianping/Logan#14]
类都找不到
![image](https://user-images.githubusercontent.com/3215104/46949894-7f684d00-d0b5-11e8-83e1-42eb8b53070b.png)

**Comment by Richard-Cao** [comment]
重新sync一下呢

**Comment by Microhx** [comment]
这个不影响功能的，可以直接使用的

**Comment by Richard-Cao** [comment]
好的，我来处理下

**Comment by Richard-Cao** [comment]
@WrBug 你的意思是把aar不混淆吗

**Comment by WrBug** [comment]
对的，不用混淆

**Comment by Richard-Cao** [comment]
done.
Please upgrade version to 1.1.0.
Thx.
