### ISSUE TITLE
关于日志类型的说明

### ISSUE THREAD

**Issue by wangyeming** [Meituan-Dianping/Logan#141]
你好，关于type类型，文档里说下面会详细说：

    int type：写入的日志类型，这非常重要，在下文的最佳实践内容会详细讲述如何优雅利用日志类型参数。

然后我的难过看完也没看到哪里说明type了，demo里面也是直接用1，2，3，源码直接就调用到native的clogan_write方法，所以也没办法自己理解。
希望能补充解释一下，多谢

**Comment by Richard-Cao** [comment]
这个type是你自己定义的，比如1是网络日志，2是行为日志，3是代码日志等。
