### ISSUE TITLE
日志解析报错

### ISSUE THREAD

**Issue by NeverForget520** [Meituan-Dianping/Logan#142]
日志解析出现 java.util.zip.ZipException: Not in GZIP format 异常，请问这个是哪里出了问题，我在Android文件管理器里面查看日志是没有文件后缀的，自己写的java调用demo中的parser
 W/System.err: java.util.zip.ZipException: Not in GZIP format
 W/System.err:     at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:163)
 W/System.err:     at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
 W/System.err:     at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:89)
 W/System.err:     at com.jitian.yd.launcher.descrypt.LoganParser.parse(LoganParser.java:116)
 W/System.err:     at com.jitian.yd.launcher.descrypt.MainDecrypt.fileDecrypt(MainDecrypt.java:65)
 W/System.err:     at com.jitian.yd.launcher.descrypt.MainDecrypt.logDecrypt(MainDecrypt.java:49)
 W/System.err:     at com.jitian.yd.launcher.descrypt.MainDecrypt.logDecrypt(MainDecrypt.java:33)

**Comment by Richard-Cao** [comment]
日志被截断了吗？建议在app切换到后台的时候，调用一下flush

**Comment by NeverForget520** [comment]
调用过Logan.f() , 你们正常的log，有没有后缀名？ 我这边的log文件名字一直是1569168000000 ，没有后缀

**Comment by NeverForget520** [comment]
我看了全部的issue，有一样报这个错误的，但是他们好像说可以有部分日志解析出来，我的解析出来是空文件，没有任何日志

**Comment by Richard-Cao** [comment]
> 调用过Logan.f() , 你们正常的log，有没有后缀名？ 我这边的log文件名字一直是1569168000000 ，没有后缀

没有后缀

**Comment by Richard-Cao** [comment]
> 我看了全部的issue，有一样报这个错误的，但是他们好像说可以有部分日志解析出来，我的解析出来是空文件，没有任何日志

空文件这个就得问问你们客户端同学了。。。再怎么样也不会是空文件

**Comment by Richard-Cao** [comment]
解出来的文件是个空的？

**Comment by NeverForget520** [comment]
日志打印完，是处于加密状态的，然后我从手机里面拿出来，放到电脑上，调用LoganParser解密，解密出来的文件是空的，因为在解密过程中已经报错了，就是没有解密成功

**Comment by NeverForget520** [comment]
最新测试发现，我们的log文件用你们的Demo上传到server上，js 方式解密解压是ok 的，但是用java LoganParser的解密就不行，问题：
1、是否需要把log文件上传后以gz后缀保存以后再调用LoganParser
2、是否是在windows下调用LoganParser就无法识别GZIP format

**Comment by Richard-Cao** [comment]
> 最新测试发现，我们的log文件用你们的Demo上传到server上，js 方式解密解压是ok 的，但是用java LoganParser的解密就不行，问题：
> 1、是否需要把log文件上传后以gz后缀保存以后再调用LoganParser
> 2、是否是在windows下调用LoganParser就无法识别GZIP format

1. 不需要
2. windows这个真没测试过

**Comment by lewic1987** [comment]
@Richard-Cao @NeverForget520 遇到的问题一样 日志原始文件有内容，但是解密报java.util.zip.ZipException: Not in GZIP format异常了，导致日志无法解密，请问是LoganParser解密版本的问题吗，不能强制要求必须手动调用一次flush吧，并且已经发版才发现这个问题的怎么办

**Comment by NeverForget520** [comment]
@lewic1987 你试试用demo 的版本抓log然后解密能不能正常，然后对比你的，我之前的问题是因为秘钥配置的有问题，跟版本无关
