### ISSUE TITLE
关于IOS端问题

### ISSUE THREAD

**Issue by zhangdan183** [Meituan-Dianping/Logan#143]
我使用POD导入项目始终无法找到Logan.h文件，我是一个IOS初学者，所以我认定肯定是我的问题，
而我使用的双平台开发给出的模块封装DMEO不太建议我使用PODS来进行引入，所以我想问一下，IOS端的模块是否支持使用framework来进行进入logan，我真的非常想使用LOGAN，阿里 腾讯云 华为云 等等日志服务要么有致命的问题，要么还没有开发完成，希望能给我一个指导，教我怎么打包frameword,谢谢！
或者哪位大神指导一下也可以。

**Comment by jiangteng** [comment]
目前没有提供Framework。如果不使用pod的话，建议直接源码集成，把源码拖到项目工程中就行。

**Comment by zhangdan183** [comment]
我已经使用了您交给我的方法
但是还有一个小问题就是我使用了方法之后在
#import "Logan.h"的时候提示我file无法找到
我已经在Build Settings 中 设置了user header search paths路径
$(SRCROOT)/UZApp/Logan
$(SRCROOT)/UZApp/Logan/iOS
但是还是提示无法找到
如果不嫌我的问题低级的话，麻烦小提示一下，谢谢。

**Comment by jiangteng** [comment]
把源码拖到项目工程时，是不是勾选了 “Create folder references”?

**Comment by zhangdan183** [comment]
选择的是
copy items if needed
create groups
这两个选项
谢谢解答

**Comment by jiangteng** [comment]
你的应该是工程问题，要不参考一下demo?

**Comment by zhangdan183** [comment]
我直接使用的相对路径打包的.a文件，已经可以用了，谢谢
