### ISSUE TITLE
关于上传日志问题

### ISSUE THREAD

**Issue by zhangdan183** [Meituan-Dianping/Logan#144]
你好，针对Logan我有个小问题，
请问日志文件上传完成之后，本地的文件怎么删除呢，我的想法是我有可能两三天才上传一次，上传完成之后，我想把本地的已上传的删除掉，防止再次上传。
不知道有没有方法？谢谢

我从源码中看到这两个方法
deleteLoganFile

loganClearAllLogs
不知道我找的对不对

**Comment by zhangdan183** [comment]
还有个疑问就是，我使用了提供的node后台代码，获取到的日志文件由.temp文件转为了.txt文件，请问你们是怎么批量操作这些txt文件的呢，比如批量读取然后显示在某个网页上面，不知道有没有分享出来的功能？

**Comment by Richard-Cao** [comment]
你是指客户端侧删除文件？

**Comment by zhangdan183** [comment]
安卓和苹果两个平台

**Comment by Richard-Cao** [comment]
readme里有讲解

**Comment by zhangdan183** [comment]
不好意思我只找到了初始化 写入 以及上传日志
并没有找到删除某天日志的功能

**Comment by zhangdan183** [comment]
我是说你们写好的方法 
比如我在IOS代码里面找到loganClearAllLogs这个方法 这个是清除所有日志
我的意思是有没有根据日期或者名称来清除某一天的日志的方法

**Comment by jiangteng** [comment]
> 我想把本地的已上传的删除掉，防止再次上传

最好是控制外层的上传方式的调用。目前没有提供针对单个日志文件进行删除的API，不推荐使用loganClearAllLogs，他会删除本地所有的日志文件

**Comment by zhangdan183** [comment]
奥 谢谢
