### ISSUE TITLE
请教后台日志读取问题

### ISSUE THREAD

**Issue by zhangdan183** [Meituan-Dianping/Logan#145]
请问已上传的日志读取问题有没有已经分享出来的框架呢
通过node后台接收到的文件中不是我平时使用的标准的JSON文件，不知道怎么解析日志然后呈现出来。谢谢

**Comment by jiangteng** [comment]
已经提供了 node版本的解析，[详情](https://github.com/Meituan-Dianping/Logan/wiki/How-to-use-demo#server-demo)

**Comment by zhangdan183** [comment]
![微信截图_20191022110145](https://user-images.githubusercontent.com/10098307/67256781-690c8280-f4bb-11e9-8c6d-8234ba079e49.png)
我的意思是，上传服务器之后，您这边提供的解析程序，解析出来了，也没个中括号，也没个逗号的，比如想拿其中第三条数据，一般的解析json的方法解析不了，不知道你们这边是怎么处理的。
我这么说您能明白吗

**Comment by Richard-Cao** [comment]
这里每一条都是json数据，一条一条处理。

**Comment by jiangteng** [comment]
通过行结束"\n"分隔符对文件做处理，获取每一行的内容，其中每一行都是一条json格式的日志内容。
