### ISSUE TITLE
日志读取

### ISSUE THREAD

**Issue by zhangdan183** [Meituan-Dianping/Logan#146]
我使用了node获取到了log-demo.txt文件，但是里面的数据是
`{"c":"clogan header","f":1,"l":1571032070019,"n":"clogan","i":1,"m":true}
{"c":"1\tclick button 0\t","f":1,"l":1571032070005,"n":"","i":1,"m":true}
{"c":"1\tclick button 1\t","f":1,"l":1571032070005,"n":"","i":1,"m":true}
{"c":"1\tclick button 2\t","f":1,"l":1571032070005,"n":"","i":1,"m":true}
{"c":"1\tclick button 3\t","f":1,"l":1571032070005,"n":"","i":1,"m":true}
{"c":"1\tclick button 4\t","f":1,"l":1571032070005,"n":"","i":1,"m":true}
{"c":"1\tclick button 5\t","f":1,"l":1571032070005,"n":"","i":1,"m":true}
{"c":"1\tclick button 6\t","f":1,"l":1571032070005,"n":"","i":1,"m":true}
{"c":"1\tclick button 7\t","f":1,"l":1571032070005,"n":"","i":1,"m":true}
{"c":"1\tclick button 8\t","f":1,"l":1571032070005,"n":"","i":1,"m":true}
{"c":"1\tclick button 9\t","f":1,"l":1571032070005,"n":"","i":1,"m":true}`
我想问的是，这样的数据怎么解析，就是我想用什么语言把这些日志一条一条的读取出来

**Comment by Richard-Cao** [comment]
这是标准的JSON格式，参考https://github.com/Meituan-Dianping/Logan/wiki/Log-protocol
