### ISSUE TITLE
IOS上传日志NODE服务器解析报错

### ISSUE THREAD

**Issue by zhangdan183** [Meituan-Dianping/Logan#147]
{ Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17) errno: -3, code: 'Z_DATA_ERROR' }
这个是报错信息
1.我传了10条相同的日志
2.解析到第9条的时候报错了，报错了就中断了，请问是什么原因呢，temp文件我已经上传附件了。[http://a34ea008237d0cd726da.qiniucdn.apicloud-system.com/apicloud/6c44d48fb0062986b5d299835a7a373.temp](url)
请解答一下 谢谢

**Comment by zhangdan183** [comment]
有关这个问题我自己解答一下给其他人看一下吧，就是如果日志写的太多太快的话，会写的不完整，所以会解析报错，日志不能for循环的时候写太多的日志进去，否则就会解析报错，不知道会不会还有别的原因，如果有知道的人们欢迎补充。

**Comment by Richard-Cao** [comment]
你只是单纯的for循环吗？

**Comment by zhangdan183** [comment]
是单纯的for循环 只不过我写入的日志比较长

**Comment by Richard-Cao** [comment]
> 是单纯的for循环 只不过我写入的日志比较长

循环了多少次？

**Comment by zhangdan183** [comment]
10次 20次 都一样 都会少一条半

**Comment by Richard-Cao** [comment]
> 10次 20次 都一样 都会少一条半

如果每次都稍微给一个delay试试呢？
