### ISSUE TITLE
Android Logan, LoganThread#quit is never used.

### ISSUE THREAD

**Issue by tankcong** [Meituan-Dianping/Logan#15]
目前Android的Logan提供的api没有quit操作，如果有几个Action.SEND就没法终止上传。
看到LoganThread里有quit方法，但其实并没有暴露出来，而且内部也无调用，
是否应该考虑增加Logan#quit()的api

**Comment by Richard-Cao** [comment]
终止上传这个在什么场景下会用到？

**Comment by Richard-Cao** [comment]
> > 终止上传这个在什么场景下会用到？
> 
> 主动反馈的过程中点取消

这个我们考虑一下。
