### ISSUE TITLE
# logan-thread-send-log(298)  SIGABRT 异常

### ISSUE THREAD

**Issue by xiaxiayang** [Meituan-Dianping/Logan#150]
应用场景是无人售货机，所以程序一直处于前台。时间过长时，会发现程序异常崩溃。通过 bugly 捕获到的错误信息：

#00 pc 0003d9bc /system/lib/libc.so (tgkill+12) [armeabi-v7a]
--
2 #01 pc 00016dad /system/lib/libc.so (pthread_kill+52) [armeabi-v7a]
3 #02 pc 000179bf /system/lib/libc.so (raise+10) [armeabi-v7a]
4 #03 pc 00014165 /system/lib/libc.so (__libc_android_abort+36) [armeabi-v7a]
5 #04 pc 000124ec /system/lib/libc.so (abort+4) [armeabi-v7a]
6 #05 pc 0001549b /system/lib/libc.so (__libc_fatal+16) [armeabi-v7a]
7 #06 pc 000154b3 /system/lib/libc.so (__fortify_chk_fail+18) [armeabi-v7a]
8 #07 pc 0004126d /system/lib/libc.so (__FD_SET_chk+24) [armeabi-v7a]
9 #08 pc 0000a90f /system/lib/libjavacrypto.so [armeabi-v7a]
10 #09 pc 0000f3df /system/lib/libjavacrypto.so [armeabi-v7a]
11 #10 pc 002f8c9b /data/dalvik-cache/arm/system@framework@boot.oat [armeabi]
12 java:
13 com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
14 com.android.okhttp.Connection.upgradeToTls(Connection.java:201)
15 com.android.okhttp.Connection.connect(Connection.java:155)
16 com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
17 com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
18 com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
19 com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
20 com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:217)
21 com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
22 com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
23 com.nposclient.manager.RealSendLogRunnable.doPostRequest(RealSendLogRunnable.java:143)
24 com.nposclient.manager.RealSendLogRunnable.doSendFileByAction(RealSendLogRunnable.java:99)
25 com.nposclient.manager.RealSendLogRunnable.sendLog(RealSendLogRunnable.java:60)
26 com.dianping.logan.SendLogRunnable.run(SendLogRunnable.java:59)
27 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
28 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
29 java.lang.Thread.run(Thread.java:818)

bugly跟踪的日志：

10-24 01:44:26.954 13191 14725 W System.err: java.io.IOException: ioctl failed: EBADF (Bad file number)
--
910-24 01:44:26.954 13191 14725 W System.err: at libcore.io.IoBridge.available(IoBridge.java:74)
1010-24 01:44:26.954 13191 14725 W System.err: at java.io.FileInputStream.available(FileInputStream.java:108)
1110-24 01:44:26.954 13191 14725 W System.err: at com.nposclient.manager.RealSendLogRunnable.doSendFileByAction(RealSendLogRunnable.java:100)
1210-24 01:44:26.954 13191 14725 W System.err: at com.nposclient.manager.RealSendLogRunnable.sendLog(RealSendLogRunnable.java:60)
1310-24 01:44:26.954 13191 14725 W System.err: at com.dianping.logan.SendLogRunnable.run(SendLogRunnable.java:59)
1410-24 01:44:26.954 13191 14725 W System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
1510-24 01:44:26.954 13191 14725 W System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
1610-24 01:44:26.954 13191 14725 W System.err: at java.lang.Thread.run(Thread.java:818)
1710-24 01:44:26.954 13191 14725 W System.err: Caused by: android.system.ErrnoException: ioctl failed: EBADF (Bad file number)
1810-24 01:44:26.954 13191 14725 W System.err: at libcore.io.Posix.ioctlInt(Native Method)
1910-24 01:44:26.954 13191 14725 W System.err: at libcore.io.ForwardingOs.ioctlInt(ForwardingOs.java:99)
2010-24 01:44:26.954 13191 14725 W System.err: at libcore.io.IoBridge.available(IoBridge.java:58)
2110-24 01:44:26.954 13191 14725 W System.err: ... 7 more

希望帮忙看一下原因，谢谢

**Comment by xiaxiayang** [comment]
设备信息：
![image](https://user-images.githubusercontent.com/25956745/67447752-7b1b2c00-f647-11e9-8490-1e2b8a56763c.png)

**Comment by Richard-Cao** [comment]
这个看起来是https的问题，logan上传的时候是你们自己写的https吧

**Comment by xiaxiayang** [comment]
上传的代码是照着demo上的方法写的

**Comment by Richard-Cao** [comment]
这个报错看起来是网络请求的问题，建议你往这方面查一下

**Comment by xiaxiayang** [comment]
好的，多谢
