### ISSUE TITLE
Android  loadLibrary  is private and will be removed in a future Android release

### ISSUE THREAD

**Issue by chouchouyu** [Meituan-Dianping/Logan#152]
麻烦注意一下console 这个提示 

10-30 14:49:02.204 17022-17038/test.logan.dianping.com.logan E/System: java.lang.Runtime#loadLibrary(String, ClassLoader) is private and will be removed in a future Android release

<img width="1233" alt="屏幕快照 2019-10-30 下午2 50 33" src="https://user-images.githubusercontent.com/13679630/67835478-04899d00-fb25-11e9-9435-8abf6dfa005e.png">

**Comment by Richard-Cao** [comment]
ok，会处理的～等我忙完这阵子～

**Comment by Richard-Cao** [comment]
#196
