### ISSUE TITLE
您好  AndroidQ 适配，检测到非SDK接口 限制

### ISSUE THREAD

**Issue by wanglyGithub** [Meituan-Dianping/Logan#153]
#1966: Reflection greylist Ljava/lang/Runtime;->loadLibrary potential use(s):
       Lcom/dianping/logan/Util;->loadLibrary(Ljava/lang/String;Ljava/lang/Class;)Z
       Lorg/android/spdy/SoInstallMgrSdk;->initSo(Ljava/lang/String;ILjava/lang/ClassLoader;)Z

#1967: Reflection blacklist Ljava/lang/Runtime;->loadLibrary0 potential use(s):
       Lcom/dianping/logan/Util;->loadLibrary(Ljava/lang/String;Ljava/lang/Class;)Z

**Comment by Richard-Cao** [comment]
等我忙完这阵子就改一下

**Comment by wanglyGithub** [comment]
:+1:

**Comment by Richard-Cao** [comment]
#196
