### ISSUE TITLE
请教个日志写入硬盘时机问题

### ISSUE THREAD

**Issue by yinjining** [Meituan-Dianping/Logan#156]
美团的朋友，您们好！
         有两个疑问，能帮忙解答一下吗？非常感激。
 
        //文件写入磁盘、更新文件大小
void write_dest_clogan(void *point, size_t size, size_t length, cLogan_model *loganModel) {
    if (!is_file_exist_clogan(loganModel->file_path)) { //如果文件被删除,再创建一个文件
        if (logan_model->file_stream_type == LOGAN_FILE_OPEN) {
            fclose(logan_model->file);
            logan_model->file_stream_type = LOGAN_FILE_CLOSE;
        }
        if (NULL != _dir_path) {
            if (!is_file_exist_clogan(_dir_path)) {
                makedir_clogan(_dir_path);
            }
            init_file_clogan(logan_model);
            printf_clogan("clogan_write > create log file , restore open file stream \n");
        }
    }
    if (CLOGAN_EMPTY_FILE == loganModel->file_len) { //如果是空文件插入一行CLogan的头文件
        insert_header_file_clogan(loganModel);
    }
    fwrite(point, sizeof(char), logan_model->total_len, logan_model->file);//写入到文件中
    fflush(logan_model->file);
    loganModel->file_len += loganModel->total_len; //修改文件大小
}

1、看到用fwrite 写入到文件了，我到demo的磁盘目录下，文件大小为什么没有变化呢？
2、mmap建立的映射是logan.mmap2文件，和日期命名的文件有什么关联呢？

**Comment by jiangteng** [comment]
#1 写文件有个时机，不是实时写的。可以把观察时间拉长点。

# 2 mmap是个临时文件，跟日期命名的文件没有直接有关系
