### ISSUE TITLE
请教关于日志文件的问题

### ISSUE THREAD

**Issue by tankcong** [Meituan-Dianping/Logan#16]
读了下android的代码有以下几个问题想咨询作者，望不吝赐教

1. 既然目前已经支持了分片写入，为何还要限制日志文件的大小，不知如此设计是否有其他考量？

> 某些企业应用每天的日志量很大

2. 目前日志文件超过大小之后会禁止写入，即使上传了当天的日志也只会删除.copy的日志文件，原日志文件并不会一起清理。Logan也没有提供方法可以拿到当天的日志文件进行手动删除（通过getAllFilesInfo返回的Key和传入的path自己拼？），请问超出大小后应该如何处理？

> 简单的想法是再次做文件分包，上传后由后端解析合并。

**Comment by Richard-Cao** [comment]
1.日志文件实际使用中并不能无限大，还得考虑文件上传的情况，假如上传一个30m大小的日志文件很多情况下都不合适。

**Comment by Richard-Cao** [comment]
2.超过7天（默认）的日志就会被清除了
