### ISSUE TITLE
MacOS编译Android版报错

### ISSUE THREAD

**Issue by yy307** [Meituan-Dianping/Logan#17]
Android Studio 3.2RC3
NDK r15c
gradle 3.5.1
macOS 10.14

#gradle-3.5.1/bin/gradle assembleDebug --debug --stacktrace 
报错信息
20:22:08.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Error while executing process /Users/xx/androidsdk/cmake/3.10.2.4988404/bin/cmake with arguments {-H/Users/xx/projects/app/Logan/Example/Logan-Android/logan -B/Users/xx/projects/app/Logan/Example/Logan-Android/logan/.externalNativeBuild/cmake/release/armeabi -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi -DANDROID_NDK=/Users/xx/android-ndk-r15c -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/xx/projects/app/Logan/Example/Logan-Android/logan/build/intermediates/cmake/release/obj/armeabi -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=/Users/xx/androidsdk/cmake/3.10.2.4988404/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/Users/xx/android-ndk-r15c/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-14 -DCMAKE_C_FLAGS=-std=c11 -DBUILD_TESTING=OFF -DANDROID_TOOLCHAIN=gcc}
20:22:08.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] CMake Error: Could not create named generator Android Gradle - Ninja
20:22:08.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
20:22:08.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Generators
20:22:08.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Unix Makefiles               = Generates standard UNIX makefiles.
20:22:08.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Ninja                        = Generates build.ninja files.
20:22:08.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Xcode                        = Generate Xcode project files.
20:22:08.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   CodeBlocks - Ninja           = Generates CodeBlocks project files.
20:22:08.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
20:22:08.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   CodeLite - Ninja             = Generates CodeLite project files.
20:22:08.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   CodeLite - Unix Makefiles    = Generates CodeLite project files.
20:22:08.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
20:22:08.568 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Sublime Text 2 - Unix Makefiles
20:22:08.568 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]                                = Generates Sublime Text 2 project files.
20:22:08.568 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Kate - Ninja                 = Generates Kate project files.
20:22:08.568 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Kate - Unix Makefiles        = Generates Kate project files.
20:22:08.568 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
20:22:08.568 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
20:22:08.568 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   KDevelop3                    = Generates KDevelop 3 project files.
20:22:08.568 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   KDevelop3 - Unix Makefiles   = Generates KDevelop 3 project files.
20:22:08.568 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
20:22:08.568 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
20:22:08.568 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.android.build.gradle.tasks.ExternalNativeBuildTaskUtils.executeBuildProcessAndLogError(ExternalNativeBuildTaskUtils.java:241)
20:22:08.568 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.android.build.gradle.tasks.CmakeExternalNativeJsonGenerator.executeProcess(CmakeExternalNativeJsonGenerator.java:142)
20:22:08.568 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.buildAndPropagateException(ExternalNativeJsonGenerator.java:272)
20:22:08.569 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.build(ExternalNativeJsonGenerator.java:178)
20:22:08.569 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.android.build.gradle.tasks.ExternalNativeBuildJsonTask.build(ExternalNativeBuildJsonTask.java:39)
20:22:08.569 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
20:22:08.569 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 32 more
20:22:08.569 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
20:22:08.569 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
20:22:08.569 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED

**Comment by Richard-Cao** [comment]
这个很奇怪，你本地有做过什么改动吗？

**Comment by yy307** [comment]
没有, 和C编译坏境有关系吗?  NDK r15c是单独下载的, gradle也是本地的, 没有用Android Studio内置的gradle

**Comment by Richard-Cao** [comment]
试下wiki里注明的ndk版本。

**Comment by Richard-Cao** [comment]
@yy307 还有问题吗
