### ISSUE TITLE
关于使用Android 解密aes报错问题

### ISSUE THREAD

**Issue by ShiminChen007** [Meituan-Dianping/Logan#171]
我在本地想解析一下保存的加密文件，发现使用aes解密一直报错，不知道是否是我使用的参数不对，可否给个提示，我看了node.js的解密，有点不太清楚
`public static byte[] decrypt(byte[] input, byte[] key, byte[] iv) {
        try {
            byte[] output = null;
            IvParameterSpec ivSpec = new IvParameterSpec(iv);
            SecretKeySpec skey = new SecretKeySpec(key, "AES");
            Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
            cipher.init(Cipher.DECRYPT_MODE, skey, ivSpec);
            output = cipher.doFinal(input);
            return output;
        } catch (Exception e) {
            //e.printStackTrace();
            Timber.e(e, "decrypt failed");
            return null;
        }

    }`

**Comment by Richard-Cao** [comment]
Java的有工具类哦，就在代码仓库里，现在也有新的后台系统开源可以接入啦。

**Comment by ShiminChen007** [comment]
我没找到，可否告诉我是哪个类么？

**Comment by Richard-Cao** [comment]
可以直接接server：https://github.com/Meituan-Dianping/Logan/blob/master/Logan/Server/README
也可以用Java的解析类：https://github.com/Meituan-Dianping/Logan/blob/master/Logan/parser-java/src/main/java/LoganParser.java

**Comment by cuixiaodong** [comment]
> 可以直接接server：https://github.com/Meituan-Dianping/Logan/blob/master/Logan/Server/README
> 也可以用Java的解析类：https://github.com/Meituan-Dianping/Logan/blob/master/Logan/parser-java/src/main/java/LoganParser.java

现在没这个了~

**Comment by Richard-Cao** [comment]
> > 可以直接接server：https://github.com/Meituan-Dianping/Logan/blob/master/Logan/Server/README
> > 也可以用Java的解析类：https://github.com/Meituan-Dianping/Logan/blob/master/Logan/parser-java/src/main/java/LoganParser.java
> 
> 现在没这个了~

可以往回切几个commit，在删除这个的commit之前能找到
