### ISSUE TITLE
后端Server怎么运行起来

### ISSUE THREAD

**Issue by wangyudong211** [Meituan-Dianping/Logan#175]
Logan\Logan\Server下面的代码只有源码，这块代码应该怎么使用

**Comment by MeDeity** [comment]
这是个maven项目,你需要的是对TA进行打包,然后放到WEB容器中运行，比如Tomcat

**Comment by xiaonan0527** [comment]
> 这是个maven项目,你需要的是对TA进行打包,然后放到WEB容器中运行，比如Tomcat

我用maven打成war包在放到本地tomcat里，iOS端调用上传接口返回200正常，但是Server程序没有写入数据，是怎么回事啊？
