### ISSUE TITLE
文档很不完善

### ISSUE THREAD

**Issue by yuanminglong** [Meituan-Dianping/Logan#180]
这个项目看介绍很不错，我试着把整个项目跑起来看看效果，但是Server，和LoganSite没有完整的文档说明，也没有整个项目的完整说名，凭着感觉折腾半天，还是一头雾水。能否出个详细的文档，或者在文档出来前建立一个群来讨论使用中遇到的问题

**Comment by Richard-Cao** [comment]
好的！

**Comment by Retrospection** [comment]
@yuanminglong 您好，感谢您试用Logan。您可以加一下我的微信angelrex，我帮你添加到Logan微信交流群中为您提供解惑

**Comment by Richard-Cao** [comment]
文档在不断完善中，感谢关注～
