### ISSUE TITLE
后端支持docker化部署吗？

### ISSUE THREAD

**Issue by Barretem** [Meituan-Dianping/Logan#192]
小前端一个，觉得java部署太复杂了。docker化之后，前端都可以快速部署。

**Comment by zlLuo** [comment]
Java Web项目本身是可以部署在docker容器的，只是目前日志是存放在服务器本地磁盘的，docker化后日志存储部分就需要自行处理

**Comment by Barretem** [comment]
能否提供官方的docker镜像，方便前端部署？谢谢

**Comment by Barretem** [comment]
谢谢了！我们后端处理好了

**Comment by xiaonan0527** [comment]
> 谢谢了！我们后端处理好了

我这边部署的服务器端怎么不能写入数据啊？请问你那边是怎么弄的？
