### ISSUE TITLE
websdk 上报了当天的日志后，再次调用上报当天的日志就不会上报了，就是这么设计的吗？

### ISSUE THREAD

**Issue by KevinLoveGitHub** [Meituan-Dianping/Logan#197]

**Comment by sylvia1106** [comment]
WebSDK目前不会限制当天日志重复上报，但是服务端SDK内有对日志内容覆盖的逻辑。

**Comment by KevinLoveGitHub** [comment]
服务端的SDK我直接部署上去没有改动过，现在上传同一天的多次也不会覆盖旧的

**Comment by leoxchang** [comment]
不是不上报，是服务端解析的时候，不重新解析了，当天多次上报后端task是更新了的，web_detail没有重新解析生成新的

**Comment by sylvia1106** [comment]
关闭了，如果上报这块还有问题，可以加微信群或者提issue继续反馈我们。

**Comment by he-yuanchao** [comment]
不会出现不上报日志情况，websdk 上报的日志是基于 **日志的日期 + pageNum + unionId** 识别日志的唯一性的，相同的日志会发生覆盖，但在日志解析过程中会有一定的特殊处理：一旦日志被查看过，那么就会被**标记为已解析的状态**，后续查看时不会再进行重新解析，因此新上报的日志就不会展示出来

**Comment by 80666881** [comment]
遇到同样的问题，请问同一天重复上报的日志是否第二天就会显示？

**Comment by sylvia1106** [comment]
> 遇到同样的问题，请问同一天重复上报的日志是否第二天就会显示？

并不是。
websdk目前上报是按天区分，每天的日志每次都是分页全量上报的，不存在当天有日志但二次上报触发时不上报数据的情况。
服务端数据库内同天日志二次上报时不显示的原因he-yuanchao已经解释了，我补充个栗子。比如'2020-03-23-第一页-xyz'这份日志之前无论何时已经上报且解析过了，那么即使这份日志里后续有新加的日志并且再次上报后，服务端不会重新解析这份日志，才会引起该份日志新加的日志有丢失显示的情况。
所以目前日志有数据不更新的根本原因在于服务端对解析过的'日期 + 页码 + unionId'唯一标识的日志不再重新解析。
我们近期会对websdk上报逻辑做更新，已上报的日志会在本地删除，后续上报的日志页码递增，使每次上报的都是新页码来绕开同页日志不更新的问题。

**Comment by sylvia1106** [comment]
[Web SDK 1.1.0](https://github.com/Meituan-Dianping/Logan/pull/254)已支持可配置的增量上报选项：https://github.com/Meituan-Dianping/Logan/blob/master/Logan/WebSDK/README.ch.md#-reportreportconfig，上报后日志页码递增，可解决同页日志重复上报的问题。
