### ISSUE TITLE
子线程写的日志没有了

### ISSUE THREAD

**Issue by Microhx** [Meituan-Dianping/Logan#20]

**Comment by Microhx** [comment]
<img width="605" alt="default" src="https://user-images.githubusercontent.com/17956663/47081235-a2713900-d23c-11e8-9a14-f4b20356b96f.png">

好像被自动过滤了一下：
子线程写日志代码如下：
`
new Thread(){

            @Override
            public void run() {
                Logan.w("log in sub thread", 1);
                try {
                    sleep(500);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                Logan.w("Log in sub thread" , 4);
                Logan.f();
            }
        }.start();
`

**Comment by Richard-Cao** [comment]
Demo里就是子线程写的吧?

**Comment by Microhx** [comment]
> Demo里就是子线程写的吧?

Demo里在主线程写了，也在子线程中写过，二者混合操作过，先后顺序随机，但是反馈的log文件中每条都是m:true

**Comment by Richard-Cao** [comment]
如果你删掉Logan.f的调用呢？ @Microhx

**Comment by Microhx** [comment]
> 如果你删掉Logan.f的调用呢？ @Microhx

晚上下班时我再看一下

**Comment by Microhx** [comment]
> > 如果你删掉Logan.f的调用呢？ @Microhx
> 
> 晚上下班时我再看一下

您好，最近比较忙，我去掉了 Logan.f方法，发现子线程可以写入了。

**Comment by Richard-Cao** [comment]
Good @Microhx

**Comment by e-snail** [comment]
为什么Logan.f() 不能在子线程中调用呢？
