### ISSUE TITLE
引入后编译报错

### ISSUE THREAD

**Issue by cangyimoyu** [Meituan-Dianping/Logan#203]
尝试了两种方式的引入，在直接将文件拖入项目中，如下图
![图片](https://user-images.githubusercontent.com/20724651/73918531-c27aaf00-48fc-11ea-8866-278e05a734b2.png)
会报clogan_core not found，
但是如果直接通过cocoapods引入的话，那么就会报如下错误
![图片](https://user-images.githubusercontent.com/20724651/73918878-6fedc280-48fd-11ea-9f2a-3fd58f2a2d1f.png)
目前不知道错在什么地方，我是在Appdelegate中使用的，请指点一下是什么问题

**Comment by jiangteng** [comment]
那个版本？

**Comment by jiangteng** [comment]
可以看看这个issue https://github.com/Meituan-Dianping/Logan/issues/29

**Comment by cangyimoyu** [comment]
pod 'Logan', '~> 1.2.6'
在ViewController里面使用是没有问题的，但是在APPDelegate中使用就会报前面截图的错误，应该不会导致和#29一样的问题的啊，我们目前AppDelegate是.mm的后缀会不会和这个有关？

**Comment by jiangteng** [comment]
有可能，可能c，c++函数声明相关导致的问题

**Comment by cangyimoyu** [comment]
如果和这个有关的话，目前版本有兼容的办法或者合适的处理方案吗？

**Comment by jiangteng** [comment]
现在是只在.mm 声明Logan的头文件吗？
