### ISSUE TITLE
logan-server跨域问题

### ISSUE THREAD

**Issue by wananque** [Meituan-Dianping/Logan#205]
login-server怎么处理logan-websdk的跨域？
![image](https://user-images.githubusercontent.com/30593123/74338939-0f1f2800-4dde-11ea-9437-23428a928a67.png)
app.all("*", (req, res, next) => {
  res.header("Access-Control-Allow-Origin", "*");
  // res.header("Access-Control-Allow-Origin", ""http://192.168.1.11:8080"");
  res.header("Access-Control-Allow-Methods", "PUT,POST,GET,DELETE,OPTIONS");

  res.header(
    "Access-Control-Allow-Headers",
    "Authorization, Content-Length, X-CSRF-Token,Token,session,X_Requested_With,Accept, Origin, Host, Connection, Accept-Encoding, Accept-Language,DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Pragma"
  );
  res.header(
    "Access-Control-Expose-Headers",
    "Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma,FooBar"
  );
  // 本次预检请求的有效期，设置为24小时
  res.header("Access-Control-Max-Age", "86400");
  res.header("Access-Control-Allow-Credentials", "true");
  // 跨域请求是否需要带cookie信息 设置为true
  res.header("X-Powered-By", " 3.2.1");
  res.header("Content-Type", "application/json;charset=utf-8");
  if (req.method == "OPTIONS") {
    res.status(200);
  }
  next();
});

请大神指点迷津

**Comment by zlLuo** [comment]
res.header("Access-Control-Allow-Origin", ""); 这个是有问题的吧。
对所有域名允许跨域要用*，或者自己设置白名单后判断再动态填充

**Comment by sylvia1106** [comment]
> res.header("Access-Control-Allow-Origin", "");
> // res.header("Access-Control-Allow-Origin", ""http://192.168.1.11:8080"");

这两句都有问题，使用*或者正确的origin，第二句多了一层""
