### ISSUE TITLE
decodeLog解密问题

### ISSUE THREAD

**Issue by wananque** [Meituan-Dianping/Logan#207]
为什么web-sdk的report可以向node服务端发送请求，并且node端也可以接收到web端的请求，但是在执行decodeLog函数的时候没有执行？有大佬告知为什么吗？下面是web和node控制台的截图。
![image](https://user-images.githubusercontent.com/30593123/74524220-95ac4480-4f59-11ea-9b34-eeee320a9d60.png)
![image](https://user-images.githubusercontent.com/30593123/74524268-aceb3200-4f59-11ea-8d8a-3111e9d86eff.png)

**Comment by chenwenqin** [comment]
我的也是这样的

**Comment by sylvia1106** [comment]
Duplicate of #213
