### ISSUE TITLE
websdk中save-log.ts中的logQueue队列和saveRecursion方法感觉多余了

### ISSUE THREAD

**Issue by yibingxiong** [Meituan-Dianping/Logan#209]
save-log.ts中的saveLog方法每次调用都是先放到一个队列里边，然后调saveRecursion， 这个队列最多就放一项，感觉没必要

**Comment by sylvia1106** [comment]
saveLog方法可能会被并行调用，队列保证了数据落地到IndexedDB中是串行的，并行存储会影响数据容量的正确计算。

**Comment by yibingxiong** [comment]
js是单线程的，请教下为什么说会并行调用

**Comment by sylvia1106** [comment]
saveLog是异步方法，IndexedDB API也都是异步方法。
这意味着前一个saveLog流程没有结束，后一个saveLog可能又执行了，从而导致前一次数据存储还没有完成，后一次数据存储时拿到的还是老的现存容量数据，造成真实落地的数据体积超出限额。

**Comment by sylvia1106** [comment]
> js是单线程的，请教下为什么说会并行调用

可能措辞上引起误解了，应该说异步执行，my apology。

**Comment by sylvia1106** [comment]
如果没有其他问题，该issue先关闭了。

**Comment by yibingxiong** [comment]
> saveLog是异步方法，IndexedDB API也都是异步方法。
> 这意味着前一个saveLog流程没有结束，后一个saveLog可能又执行了，从而导致前一次数据存储还没有完成，后一次数据存储时拿到的还是老的现存容量数据，造成真实落地的数据体积超出限额。

感谢解答~
