### ISSUE TITLE
Invalid path

### ISSUE THREAD

**Issue by asyncHyj** [Meituan-Dianping/Logan#21]
在dmeo中跑的时候正常，但是我把同样的代码引入项目的时候就抛异常了，初始化方法、调用方法都是一样的，但是在项目中会报无效路径，不知道什么原因，为什么会导致文件创建失败呢！

10-18 16:48:34.325 14505-15773/pacageName D/LoganTestActivity: times : 0
10-18 16:48:34.326 14505-15358/pacageName D/LoganThread: Logan write start
10-18 16:48:34.328 14505-15358/pacageName W/System.err: java.lang.IllegalArgumentException: Invalid path: /storage/emulated/0/Android/data/packageName/files/logan_v1
10-18 16:48:34.329 14505-15358/pacageName W/System.err:     at android.os.StatFs.doStat(StatFs.java:46)
10-18 16:48:34.329 14505-15358/pacageName W/System.err:     at android.os.StatFs.<init>(StatFs.java:39)
10-18 16:48:34.329 14505-15358/pacageName W/System.err:     at com.dianping.logan.d.d(Unknown Source)
10-18 16:48:34.329 14505-15358/pacageName W/System.err:     at com.dianping.logan.d.a(Unknown Source)
10-18 16:48:34.329 14505-15358/pacageName W/System.err:     at com.dianping.logan.d.a(Unknown Source)
10-18 16:48:34.330 14505-15358/pacageName W/System.err:     at com.dianping.logan.d.run(Unknown Source)
10-18 16:48:34.330 14505-15358/pacageName W/System.err: Caused by: android.system.ErrnoException: statvfs failed: ENOENT (No such file or directory)
10-18 16:48:34.330 14505-15358/pacageName W/System.err:     at libcore.io.Posix.statvfs(Native Method)
10-18 16:48:34.330 14505-15358/pacageName W/System.err:     at libcore.io.BlockGuardOs.statvfs(BlockGuardOs.java:298)
10-18 16:48:34.331 14505-15358/pacageName W/System.err:     at android.system.Os.statvfs(Os.java:500)
10-18 16:48:34.331 14505-15358/pacageName W/System.err:     at android.os.StatFs.doStat(StatFs.java:44)
10-18 16:48:34.331 14505-15358/pacageName W/System.err: 	... 5 more
10-18 16:48:34.332 14505-15773/pacageName D/LoganTestActivity: times : 1
10-18 16:48:34.333 14505-15358/pacageName D/LoganThread: Logan write start
10-18 16:48:34.338 14505-15773/pacageName D/LoganTestActivity: times : 2
10-18 16:48:34.339 14505-15358/pacageName D/LoganThread: Logan write start
10-18 16:48:34.344 14505-15773/pacageName D/LoganTestActivity: times : 3
10-18 16:48:34.344 14505-15358/pacageName D/LoganThread: Logan write start
10-18 16:48:34.349 14505-15773/pacageName D/LoganTestActivity: times : 4
10-18 16:48:34.350 14505-15358/pacageName D/LoganThread: Logan write start
10-18 16:48:34.360 14505-15773/pacageName D/LoganTestActivity: times : 5
10-18 16:48:34.361 14505-15358/pacageName D/LoganThread: Logan write start
10-18 16:48:34.366 14505-15773/pacageName D/LoganTestActivity: times : 6
10-18 16:48:34.366 14505-15358/pacageName D/LoganThread: Logan write start
10-18 16:48:34.371 14505-15773/pacageName D/LoganTestActivity: times : 7
10-18 16:48:34.372 14505-15358/pacageName D/LoganThread: Logan write start
10-18 16:48:34.377 14505-15773/pacageName D/LoganTestActivity: times : 8
10-18 16:48:34.377 14505-15358/pacageName D/LoganThread: Logan write start
10-18 16:48:34.382 14505-15773/pacageName D/LoganTestActivity: write log end

**Comment by Richard-Cao** [comment]
路径不存在?

**Comment by asyncHyj** [comment]
@Richard-Cao 
是啊，我跟进去《/storage/emulated/0/Android/data/packageName/files/logan_v1》这个路径，“logan_v1”这个文件确实没有，手动创建之后也有问题，logan.s()的时候不会触发去调用sendLog(File logFile)，文件还是不对

**Comment by Richard-Cao** [comment]
权限问题?

**Comment by asyncHyj** [comment]
我在测试的项目里面manifest里面都没有加文件读写权限，都能正常写日志，我还以为你们是底层C去写的日志

我项目里面是有文件读写权限的，手机上也授权的文件的读写，不是权限的问题
@Richard-Cao

**Comment by Richard-Cao** [comment]
写日志是C没错，你运行Demo程序是没问题的，集成在自己的项目中就无法创建文件了么

**Comment by asyncHyj** [comment]
是的，
我以为是我自己手打敲错了
后面我把demo的activity文件、布局、RealSendLogRunnable全部复制过来也不行
用同一个手机测试的

**Comment by Richard-Cao** [comment]
用了外置存储?API版本多少

**Comment by asyncHyj** [comment]
初始化代码，就是从你们demo上copy的
    private void initData() {
        LoganConfig config = new LoganConfig.Builder()
                .setCachePath(getApplicationContext().getFilesDir().getAbsolutePath())
                .setPath(getApplicationContext().getExternalFilesDir(null).getAbsolutePath()
                        + File.separator + FILE_NAME)
                .setEncryptKey16("0123456789012345".getBytes())
                .setEncryptIV16("0123456789012345".getBytes())
                .build();
        Logan.init(config);
        Logan.setDebug(true);
        Logan.setOnLoganProtocolStatus(new OnLoganProtocolStatus() {
            @Override
            public void loganProtocolStatus(String cmd, int code) {
                Log.d(TAG, "clogan > cmd : " + cmd + " | " + "code : " + code);
            }
        });
        mSendLogRunnable = new RealSendLogRunnable();
    }


API版本
compile 'com.dianping.android.sdk:logan:1.0.0'

**Comment by asyncHyj** [comment]
好像找到原因了，liblogan.so这个so包没有？
10-18 17:54:57.729 14778-15594/packageName W/System.err: java.lang.reflect.InvocationTargetException
10-18 17:54:57.730 14778-15594/packageName W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-18 17:54:57.730 14778-15594/packageName W/System.err:     at com.dianping.logan.f.a(Unknown Source)
10-18 17:54:57.730 14778-15594/packageName W/System.err:     at com.dianping.logan.CLoganProtocol.<clinit>(Unknown Source)
10-18 17:54:57.730 14778-15594/packageName W/System.err:     at com.dianping.logan.CLoganProtocol.a(Unknown Source)
10-18 17:54:57.730 14778-15594/packageName W/System.err:     at com.dianping.logan.c.logan_init(Unknown Source)
10-18 17:54:57.730 14778-15594/packageName W/System.err:     at com.dianping.logan.d.a(Unknown Source)
10-18 17:54:57.730 14778-15594/packageName W/System.err:     at com.dianping.logan.d.run(Unknown Source)
10-18 17:54:57.731 14778-15594/packageName W/System.err: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/packageName-1/base.apk", zip file "/data/app/packageName-1/split_lib_dependencies_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_0_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_1_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_2_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_3_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_4_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_5_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_6_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_7_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_8_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/packageName-1/lib/arm, /data/app/packageName-1/base.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "liblogan.so"
10-18 17:54:57.731 14778-15594/packageName W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:367)
10-18 17:54:57.731 14778-15618/packageName D/LoganTestActivity: times : 2
10-18 17:54:57.731 14778-15594/packageName W/System.err: 	... 7 more
10-18 17:54:57.733 14778-15594/packageName W/System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/packageName-1/base.apk", zip file "/data/app/packageName-1/split_lib_dependencies_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_0_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_1_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_2_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_3_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_4_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_5_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_6_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_7_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_8_apk.apk", zip file "/data/app/packageName-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/packageName-1/lib/arm, /data/app/packageName-1/base.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/packageName-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "liblogan.so"
10-18 17:54:57.733 14778-15594/packageName W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:367)
10-18 17:54:57.733 14778-15594/packageName W/System.err:     at java.lang.System.loadLibrary(System.java:1076)
10-18 17:54:57.733 14778-15594/packageName W/System.err:     at com.dianping.logan.CLoganProtocol.<clinit>(Unknown Source)
10-18 17:54:57.733 14778-15594/packageName W/System.err:     at com.dianping.logan.CLoganProtocol.a(Unknown Source)
10-18 17:54:57.733 14778-15594/packageName W/System.err:     at com.dianping.logan.c.logan_init(Unknown Source)
10-18 17:54:57.733 14778-15594/packageName W/System.err:     at com.dianping.logan.d.a(Unknown Source)
10-18 17:54:57.733 14778-15594/packageName W/System.err:     at com.dianping.logan.d.run(Unknown Source)

**Comment by Richard-Cao** [comment]
会自动引入so，你是哪个CPU架构，armeabi还是v7a之类的？

**Comment by WrBug** [comment]
https://github.com/Meituan-Dianping/Logan/pull/18

**Comment by asyncHyj** [comment]
![tim 20181019085921](https://user-images.githubusercontent.com/17506212/47192073-5aa5fb00-d37d-11e8-931c-e469d8099b29.png)

**Comment by asyncHyj** [comment]
@WrBug 
你的.so包是你编译项目自己导的？

**Comment by WrBug** [comment]
@asyncHyj 嗯，自己编译好，把so放到相应目录下

**Comment by asyncHyj** [comment]
@WrBug 
额，so包编译，还不会弄，
可以把你编译好的'armeabi', "armeabi-v7a"，‘arm64-v8a’的so包发一份给我吗(it21sj@foxmail.com)，tks？

**Comment by WrBug** [comment]
https://github.com/WrBug/Logan/releases/tag/1.0.0-wr
这里下载吧

**Comment by asyncHyj** [comment]
@WrBug 
暂时跑起来了，tks

**Comment by Richard-Cao** [comment]
done.
Please upgrade version to 1.1.0.
Thx.
