### ISSUE TITLE
web-sdk Logan.log的 Promise写法是不是有问题? 这样写不会上报新增的日志:

### ISSUE THREAD

**Issue by laochake** [Meituan-Dianping/Logan#211]
```javascript
Logan.log(JSON.stringify({ url: window.location.href, reqUrl: '/a/b', req: { id: 1 }, res: { id: 1, value: 'abc' }}), 3)
      .then(() => {
        return Logan.report({
          deviceId: 'md5phone',
          fromDayString: '2020-02-23',
          toDayString: '2020-02-24'
        });
      })
      .then(res => {
        console.log(res)
        // 两天都是"No log exists"
      })

**Comment by sylvia1106** [comment]
> ```js
> Logan.log(JSON.stringify({ url: window.location.href, reqUrl: '/a/b', req: { id: 1 }, res: { id: 1, value: 'abc' }}), 3)
>       .then(() => {
>         return Logan.report({
>           deviceId: 'md5phone',
>           fromDayString: '2020-02-23',
>           toDayString: '2020-02-24'
>         });
>       })
>       .then(res => {
>         console.log(res)
>         // 两天都是"No log exists"
>       })
> ```

为避免调用时对后续代码执行的阻塞，Logan.log方法在设计时让开发者不必也不应该等待log方法的调用结果，也就是说log方法的调用结果并不会被异步返回。就像ReadMe中写的
![image](https://user-images.githubusercontent.com/45962241/75137705-3f8e8c80-5723-11ea-9394-5d4b1607b890.png)
Logan会默默异步地存储日志，在report接口被调用时，把本地已经存入的日志上传，但存在一种可能就是report触发时还有日志没有落地。

引用代码中report的结果显示没有日志的原因就是因为log方法内还在进行日志的存储，report获取时底层数据还是空的。
