### ISSUE TITLE
LoganSite打开查看日志详情非常卡

### ISSUE THREAD

**Issue by willpyshan13** [Meituan-Dianping/Logan#212]
大佬，请教个问题，LoganSite打开查看日志详情非常卡，这个是我部署方式不对么，还是有啥原因

**Comment by Retrospection** [comment]
LoganSite后续会有大版本更新优化，敬请期待

**Comment by willpyshan13** [comment]
> LoganSite后续会有大版本更新优化，敬请期待

这个后续是大概多久？有个期待时间不

**Comment by Retrospection** [comment]
> > LoganSite后续会有大版本更新优化，敬请期待
> 
> 这个后续是大概多久？有个期待时间不

目前规划上半年会有一版集中更新

**Comment by willpyshan13** [comment]
明白。
