### ISSUE TITLE
server.js解码失败（或者说没有进行解码）

### ISSUE THREAD

**Issue by chenwenqin** [Meituan-Dianping/Logan#213]
![1582873144(1)](https://user-images.githubusercontent.com/32031718/75518585-3ad81a00-5a3c-11ea-91ff-9b5d3b427c84.jpg)

这里是将 body整个传入decodeLog函数，看server.js文档也没做其他说明，不知道用法对不对， decodeLog(req.body, 0)

**Comment by chenwenqin** [comment]
后面经过查看源码，发现其实req.body.logArray的内容，只是做了两次编码，第一次是encode编码，第二次是对第一次的编码结果进行base64编码，即可以自己自定义解码方式，首先使用base64解码，即const firsDecode =  atob(logArray)，在进行decodeURIComponent(firsDecode)即可得到原始内容的json字符串格式： "{"t":32414,"c":"{"id":1,"age":12,"name":"test"}","d":"1582866685316"}"
这里t代表logType，c代表logContent。基于以上即可自定义解码

**Comment by sylvia1106** [comment]
server.js是在服务端开源前老的解码逻辑，为避免误解，已删。
解码逻辑参考[服务端代码](https://github.com/Meituan-Dianping/Logan/tree/master/Logan/Server)。
