### ISSUE TITLE
logan-web sdk 在 next.js 会报错

### ISSUE THREAD

**Issue by wonderswnc** [Meituan-Dianping/Logan#216]
在 next.js 框架里面使用 logan-web sdk, 会报错

import { LogEncryptMode } from './interface';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)

应该是 node_modules 里面的包，导出的模块是 es 模块导致的，希望能修复一下,

**Comment by sylvia1106** [comment]
logan-web中使用了动态import语法，因此输出了es模块而非commonjs，以配合webpack做代码分割。
logan-web本身只适用在浏览器环境运行。如果是想在同构项目中引入logan-web，使用方暂时可以调整为在浏览器端渲染时再引入logan-web；logan-web会在1.0.5版本解决node端运行时报错。

**Comment by wonderswnc** [comment]
好的，谢谢

**Comment by wonderswnc** [comment]
BTW,  node 也有支持 dynamic import 的插件 `https://github.com/airbnb/babel-plugin-dynamic-import-node`
