### ISSUE TITLE
关于ajax跨域请求会发送“ preflight”服务器嗅探问题

### ISSUE THREAD

**Issue by leoxchang** [Meituan-Dianping/Logan#218]
在有的浏览器下可能“preflight'会失败，是否可以把ajax中的”withCredentials“参数拿到外面来，让用户自己配置，是否需要浏览器开启"preflight"嗅探。

**Comment by sylvia1106** [comment]
会在下个feature版本中提供可配置的上报方法，供使用者自定义上报过程。

**Comment by sylvia1106** [comment]
[Web SDK 1.1.0](https://github.com/Meituan-Dianping/Logan/pull/254)提供了自定义上报配置xhrOptsFormatter：https://github.com/Meituan-Dianping/Logan/blob/master/Logan/WebSDK/README.ch.md#-reportreportconfig
