### ISSUE TITLE
loganSite 接入时文件加载404

### ISSUE THREAD

**Issue by mao758444** [Meituan-Dianping/Logan#219]
xhr.js:175 GET http://localhost:3000/logan/latest.json 404 (Not Found)
请问这个文件加载404是什么情况？怎么解决呢？

**Comment by Retrospection** [comment]
需要在.env.development中配置API_BASE_URL指向后端实际地址

**Comment by mao758444** [comment]
<img width="451" alt="截屏2020-03-11下午5 04 29" src="https://user-images.githubusercontent.com/39177573/76400266-fc871700-63ba-11ea-9924-f7b82d9cbad9.png">
<img width="401" alt="截屏2020-03-11下午5 04 37" src="https://user-images.githubusercontent.com/39177573/76400308-0f99e700-63bb-11ea-8ac8-2298661e7476.png">
你好，这里配置过的

**Comment by flycj** [comment]
> <img alt="截屏2020-03-11下午5 04 29" width="451" src="https://user-images.githubusercontent.com/39177573/76400266-fc871700-63ba-11ea-9924-f7b82d9cbad9.png">
> 
> <img alt="截屏2020-03-11下午5 04 37" width="401" src="https://user-images.githubusercontent.com/39177573/76400308-0f99e700-63bb-11ea-8ac8-2298661e7476.png">
> 
> 你好，这里配置过的

请问，这里怎么解决的？

**Comment by flycj** [comment]
> <img alt="截屏2020-03-11下午5 04 29" width="451" src="https://user-images.githubusercontent.com/39177573/76400266-fc871700-63ba-11ea-9924-f7b82d9cbad9.png">
> 
> <img alt="截屏2020-03-11下午5 04 37" width="401" src="https://user-images.githubusercontent.com/39177573/76400308-0f99e700-63bb-11ea-8ac8-2298661e7476.png">
> 
> 你好，这里配置过的

请问，这里怎么解决的？
