### ISSUE TITLE
远程依赖库没有armeabi-v7a的so文件

### ISSUE THREAD

**Issue by w290721955** [Meituan-Dianping/Logan#22]
因为项目没有适配armeabi，都直接走armeabi-v7a，所以远程依赖会找不到so文件。希望优化下。

**Comment by Richard-Cao** [comment]
好，这个我们看下

**Comment by asyncHyj** [comment]
@w290721955 
大胸弟，我也碰到这个问题，你是怎么解决的？

**Comment by Richard-Cao** [comment]
done.
Please upgrade version to 1.1.0.
Thx.
