### ISSUE TITLE
多条日志上传时，日志当天时间没有被更新。

### ISSUE THREAD

**Issue by lxx512511477** [Meituan-Dianping/Logan#221]
调用Logan.s(dates, mSendLogRunnable);
传入日期数组后，继承SendLogRunnable的方法中无法更新header中的filedate字段。
导致上报到后台的日志列表无法正确显示日志当天时间

**Comment by Richard-Cao** [comment]
传入日期数组后，继承SendLogRunnable的方法中无法更新header中的filedate字段。

这句话是什么意思？

**Comment by lxx512511477** [comment]
调用Logan.s(dates, mSendLogRunnable);
自定义的SendLogRunnable中，需要实现sendlog（File f）来上传文件。
每次上传文件需要header中的filedate字段标识该段日志的日期。
自定义的SendLogRunnable中没有可以获得该属性的方法，我无法获得父类中的SendAction中的date属性。
所以我暂时只能通过截取file.name用“.”分割再转换出日期。

**Comment by Richard-Cao** [comment]
你有接入Logan开源的Server吗

**Comment by lxx512511477** [comment]
应该是接入了的，我可以登录 LoganSite来查看测试数据，就是 LoganSite列表中的当前日志日期字段没有被更新

**Comment by Richard-Cao** [comment]
接入开源的Server的话，用新的Logan.s方法就可以，不需要自己写SendLogRunnable了

**Comment by lxx512511477** [comment]
compile 'com.dianping.android.sdk:logan:1.2.2'里面没有指定地址的Logan.s方法........

**Comment by Richard-Cao** [comment]
升级一下？

**Comment by Richard-Cao** [comment]
看一下文档？是不是版本号文档忘记更新了，新的肯定是有的

**Comment by lxx512511477** [comment]
bd98ef4
1.2.2
@Richard-Cao Richard-Cao released this on 23 May 2019 · 77 commits to master since this release
这不就是最后一个release包吗？

**Comment by Richard-Cao** [comment]
这个包里没有新的s方法？

**Comment by Richard-Cao** [comment]
文档更新了，最新版本是1.2.4
