### ISSUE TITLE
fwrite vs write 疑问

### ISSUE THREAD

**Issue by MickeyHub** [Meituan-Dianping/Logan#226]
logan的写入使用了fwrite, fwrite用户态的缓存大小大概是8k, logan模块的mmap空间大小默认是150k, 所以理论上logan使用的fwrite在这里并没有起到减少cpu上下文切换的作用.

**Comment by MickeyHub** [comment]
还有一个疑问是本身mmap做了映射， 这个时候使用fwrite而不是write函数, 是不是等于浪费了mmap做好的内存映射, 转而使用了fwrite提供的用户态缓存? 进而浪费了mmap节省的一次cpu拷贝从而导致cpu的浪费.

**Comment by jiangteng** [comment]
你技术分析的是正确。
但在理解Logan使用mmap原因上和我们出发点有些偏差。使用mmap并不是为了节省cpu上下文切换，是为了解决app异常关闭时产生的丢失数据问题，因为mmap内存映射，可以保证数据不丢失。
