### ISSUE TITLE
关于多条日志上报处理的疑问。

### ISSUE THREAD

**Issue by lxx512511477** [Meituan-Dianping/Logan#229]
目前上报多条日志是通过getAllFilesInfo（）获取到缓存的日期，然后for循环调用新版本的Logan.s(url, date,map，callback)方法上传日志；
但是这个回调是日志上报状态回调（int code，byte[] date），我无法获得到当前文件进行删除吗？会导致缓存文件一直存在，然后getAllFilesInfo（）查询就会有重复的已上传过得日期呀。
之前使用RealSendLogRunnable里面成功就删除本地文件的。

**Comment by Richard-Cao** [comment]
@luoheng158

**Comment by rigortek** [comment]
老接口使用自定义RealSendLogRunnable示例也只是删除了后缀是.copy的临时文件吧，
不带后缀的文件可能正在读写，不宜删除，
新接口在内部使用了默认的Runnable：SendLogDefaultRunnable，它会在onLogSendCompleted回调之后，删除后缀是.copy的临时文件。

**Comment by Richard-Cao** [comment]
> 老接口使用自定义RealSendLogRunnable示例也只是删除了后缀是.copy的临时文件吧，
> 不带后缀的文件可能正在读写，不宜删除，
> 新接口在内部使用了默认的Runnable：SendLogDefaultRunnable，它会在onLogSendCompleted回调之后，删除后缀是.copy的临时文件。

是的，只删除临时文件。正常的日志文件是等过期了才会删除的。

**Comment by Jun1orChan** [comment]
你好，相同的问题，咨询几个疑惑
1、请问客户端如何识别哪些日志文件是已经上报过的呢，今天之前的记录可以使用上传成功，然后本地删除的方式解决吗。
2、当天的日志文件，多次上报到服务端，那么当天的日志就会出现重复现象。当天的logfile是无法删除的。因为mmap正在映射中。
  请问你们是怎么解决的呢，目前就卡在这里了。
@Richard-Cao

**Comment by Richard-Cao** [comment]
@Jun1orChan 
关于问题1，其实不用刻意识别是不是上报过，因为一般情况下是查问题的时候才会上报日志文件，所以是按需上报，有些文件可能就没上报过，然后过期就自动删掉了。
关于问题2，目前是会这样，不过可以在后台做一个优化，就是上报一般会有一个taskid，如果上报过的话，下次还上报这个文件的话，可以先关联到之前上报过的task，如果不够用的话再让客户端上报真正的文件。美团点评内部是做过这个优化的

**Comment by Jun1orChan** [comment]
@Richard-Cao 感谢回答，还是有些疑问
1、“查问题的时候才会上报日志文件”，按需上报，这个应该是基于日志回捞功能，这个是已经发现了问题；异常日志不是应该主动上报吗，如果当天多次发生crash等异常；美团奔溃日志是另外一套吗。
2、我们目前也准备采用差不多的策略，是接收文件，通过deviceId和时间戳saveOrUpdate()。按照您说的，上报的文件关联taskid，这个如何关联呢。通过服务端生成file的名称策略吗。此时客户端已经上报上来了，服务端不使用的话，流量都白白浪费了。

**Comment by Richard-Cao** [comment]
@Jun1orChan 
关于问题1，Logan在美团点评的定位是在Crash日志、打点日志等等日志更下层的一个框架，主要用于个案日志分析。
关于问题2，这个taskid就是指你上报的那一次的任务id，后端生成一个。客户端报上来的话一般都会使用的嘛，用户主动上报触发点一般也是在客诉或者有bug的情况引导上报。

**Comment by Jun1orChan** [comment]
@Richard-Cao 好的，谢谢。
