### ISSUE TITLE
Android运行报错

### ISSUE THREAD

**Issue by z396431245** [Meituan-Dianping/Logan#23]
ndk r12
gradle-3.3

Build command failed.
Error while executing process D:\android\android_sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build D:\demo\Logan\Example\Logan-Android\logan\.externalNativeBuild\cmake\release\x86 --target logan}
[1/4] Building C object clogan.out/CMakeFiles/clogan.dir/mmap_util.c.o
FAILED: D:\android\android_sdk\android-ndk-r12b\toolchains\x86-4.9\prebuilt\windows-x86_64\bin\i686-linux-android-gcc.exe  --sysroot=D:/android/android_sdk/android-ndk-r12b/platforms/android-14/arch-x86  -ID:/demo/Logan/Logan/Clogan/../mbedtls/include -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c11 -O2 -DNDEBUG -MD -MT clogan.out/CMakeFiles/clogan.dir/mmap_util.c.o -MF clogan.out\CMakeFiles\clogan.dir\mmap_util.c.o.d -o clogan.out/CMakeFiles/clogan.dir/mmap_util.c.o   -c D:\demo\Logan\Logan\Clogan\mmap_util.c
D:\demo\Logan\Logan\Clogan\mmap_util.c: In function 'open_mmap_file_clogan':
D:\demo\Logan\Logan\Clogan\mmap_util.c:37:52: error: 'S_IRUSR' undeclared (first use in this function)
         int fd = open(_filepath, O_RDWR | O_CREAT, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP); //后两个添加权限
                                                    ^
D:\demo\Logan\Logan\Clogan\mmap_util.c:37:52: note: each undeclared identifier is reported only once for each function it appears in
D:\demo\Logan\Logan\Clogan\mmap_util.c:37:62: error: 'S_IWUSR' undeclared (first use in this function)
         int fd = open(_filepath, O_RDWR | O_CREAT, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP); //后两个添加权限
                                                              ^
D:\demo\Logan\Logan\Clogan\mmap_util.c:37:72: error: 'S_IRGRP' undeclared (first use in this function)
         int fd = open(_filepath, O_RDWR | O_CREAT, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP); //后两个添加权限
                                                                        ^
D:\demo\Logan\Logan\Clogan\mmap_util.c:37:82: error: 'S_IWGRP' undeclared (first use in this function)
         int fd = open(_filepath, O_RDWR | O_CREAT, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP); //后两个添加权限
                                                                                  ^
ninja: build stopped: subcommand failed.

**Comment by Richard-Cao** [comment]
你是自己本地编译的？

**Comment by z396431245** [comment]
是的

**Comment by Richard-Cao** [comment]
用ndk r16试试呢？

**Comment by z396431245** [comment]
ndk r16也试过了  也是报一样的错

**Comment by Richard-Cao** [comment]
电脑系统是？

**Comment by z396431245** [comment]
Windows 10

**Comment by Richard-Cao** [comment]
拉最新的代码编译试试？

**Comment by haizhiyun** [comment]
这个问题怎么解决，有解决的吗

**Comment by Richard-Cao** [comment]
这个问题我本地复现不出来……你们的环境有更详细的信息吗？

**Comment by haizhiyun** [comment]
int fd = open(_filepath, O_RDWR | O_CREAT, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP)
我用的是13 找机会试试16 我们的环境 O_CREAT, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP 没有这几个变量的申明处  O_RDWR | O_CREAT 是在fcntl.h 中申明的 这个文件找不到后面那几个的申明，不知道你的环境中，那几个常量是哪里申明的呢

**Comment by Richard-Cao** [comment]
@haizhiyun Fine

**Comment by bright999** [comment]
我也碰到这个问题了，换成ndk16，还是那样，有其它解决办法的么？

**Comment by bright999** [comment]
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: D:/android/android-ndk-r16b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/aarch64-linux-android-gcc.exe 
Build flags: -isystem;D:/android/android-ndk-r16b/sysroot/usr/include/aarch64-linux-android;-D__ANDROID_API__=21;-g;-DANDROID;-ffunction-sections;-funwind-tables;-fstack-protector-strong;-no-canonical-prefixes;-Wa,--noexecstack;-Wformat;-Werror=format-security;-std=c11
Id flags: 

The output was:
1
D:/android/android-ndk-r16b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.exe: cannot find crtbegin_dynamic.o: No such file or directory
D:/android/android-ndk-r16b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.exe: cannot find -lc
D:/android/android-ndk-r16b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.exe: cannot find -ldl
D:/android/android-ndk-r16b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.exe: cannot find crtend_android.o: No such file or directory
collect2.exe: error: ld returned 1 exit status


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: D:/android/android-ndk-r16b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/aarch64-linux-android-g++.exe 
Build flags: -isystem;D:/android/android-ndk-r16b/sysroot/usr/include/aarch64-linux-android;-D__ANDROID_API__=21;-g;-DANDROID;-ffunction-sections;-funwind-tables;-fstack-protector-strong;-no-canonical-prefixes;-Wa,--noexecstack;-Wformat;-Werror=format-security;;
Id flags: 

The output was:
1
D:/android/android-ndk-r16b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.exe: cannot find crtbegin_dynamic.o: No such file or directory
D:/android/android-ndk-r16b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.exe: cannot find -lstdc++
D:/android/android-ndk-r16b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.exe: cannot find -lm
D:/android/android-ndk-r16b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.exe: cannot find -lc
D:/android/android-ndk-r16b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.exe: cannot find -ldl
D:/android/android-ndk-r16b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.exe: cannot find crtend_android.o: No such file or directory
collect2.exe: error: ld returned 1 exit status

**Comment by Richard-Cao** [comment]
windows系统吗 @bright999

**Comment by Richard-Cao** [comment]
Windows机器我确实没试过…… @bright999 应该是和Windows的ndk有关系

**Comment by a1850524995** [comment]
所以问题解决了吗，内心崩溃搞了一天了。。。。同Windows

**Comment by Richard-Cao** [comment]
> 所以问题解决了吗，内心崩溃搞了一天了。。。。同Windows

我没Windows机器……没法测试……

**Comment by a1850524995** [comment]
> 
> 
> > 所以问题解决了吗，内心崩溃搞了一天了。。。。同Windows
> 
> 我没Windows机器……没法测试……

好的明天用我的Mac试一下。。。。谢了

**Comment by a1850524995** [comment]
除了降低NDK的版本外，降低OpenCV的版本同样有效，换回3.4.5版本就好了
