### ISSUE TITLE
android 上传到服务端，服务端解析报错 param illegal

### ISSUE THREAD

**Issue by mybadge** [Meituan-Dianping/Logan#233]
ERROR https-jsse-nio-443-exec-9 com.meituan.logan.web.parser.LoganProtocol - java.util.zip.ZipException: Not in GZIP format

我们的后台开发是PHP, 他解决不了这个问题，想问一下这个问题怎么解决， 谢谢了。

**Comment by mybadge** [comment]
昨天，我把服务端的域名的https 换成了 http, iOS 好了，可以解析成功了，但是android 端，解析不出来了，不清楚是什么问题

**Comment by mybadge** [comment]
android 也解决了。。

**Comment by Richard-Cao** [comment]
额。。。
