### ISSUE TITLE
logan-site里没有介绍文档里的时间轴view吗？"利用图形方式进行语义分析简称为时间轴"

### ISSUE THREAD

**Issue by Andrwyw** [Meituan-Dianping/Logan#234]
![image](https://user-images.githubusercontent.com/4827118/78004827-42594e80-736d-11ea-8d69-00865e4cf130.png)

“利用颜色差异，可以轻松区分出错误的日志，点击红点即可直接跳转至错误日志详情。”

这个视图感觉挺好，但是搭建完环境后没有~~ 考虑开源这块的代码嘛？ 急需~~

**Comment by Retrospection** [comment]
这块可能会在今年下半年的版本迭代中进行更新，还请耐心等待~

**Comment by Andrwyw** [comment]
感谢~ 另外，有没有可能把view共享一下，这边自行集成一下呢~

**Comment by Retrospection** [comment]
> 感谢~ 另外，有没有可能把view共享一下，这边自行集成一下呢~

请问您这边说的view是指？

**Comment by sunSink** [comment]
这块还有更新的计划吗？
