### ISSUE TITLE
关于加密和压缩的功能是否可以考虑做个开关配置？

### ISSUE THREAD

**Issue by RenSihao** [Meituan-Dianping/Logan#235]
iOS端，试图将Logan当做一个纯粹的mmap文件IO封装类，不涉及任何加密和压缩，继而尝试抽离加密和压缩的功能代码，发现这个过程还是比较繁琐的，要一块块注释代码，反复调试~~~

**Comment by Richard-Cao** [comment]
因为最初就不是这么设计的。这个在Android上倒是有这种纯粹的封装类

**Comment by RenSihao** [comment]
嗯，了解了，感谢回答
