### ISSUE TITLE
iOS中loganInit方法咨询

### ISSUE THREAD

**Issue by biaoxiaoa** [Meituan-Dianping/Logan#237]
loganInit方法中aes_key16与aes_iv16两个参数必须一致吗？aes_iv16这个参数有什么作用。

**Comment by Richard-Cao** [comment]
不是必须一致，一个是aes的key，一个是aes的iv，满足128位就可以（16子节）

**Comment by biaoxiaoa** [comment]
谢谢。我们的服务端是PHP，能介绍下加密，解密的原理吗？

**Comment by Richard-Cao** [comment]
这个可以看下nodejs的demo，或者是开源server里的解密代码，本质上就是AES
