### ISSUE TITLE
iOS Pod 引入带来编译警告

### ISSUE THREAD

**Issue by CodingPub** [Meituan-Dianping/Logan#238]
麻烦帮忙解决一下

![image](https://user-images.githubusercontent.com/7928804/78883271-e046ca80-7a8b-11ea-9303-529cfb2751a9.png)

**Comment by WeMadeCode** [comment]
@Richard-Cao @Mr-xiaojun 大佬们？？帮忙解决下啊

**Comment by Richard-Cao** [comment]
其他issue应该说过这个问题？我记得
