### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [Meituan-Dianping/Logan#239]
Memory is allocated
https://github.com/Meituan-Dianping/Logan/blob/43ed588a1c9f76e25579370b6062654cd8787009/Logan/Clogan/clogan_core.c#L221
but at the end of function，never free it
https://github.com/Meituan-Dianping/Logan/blob/43ed588a1c9f76e25579370b6062654cd8787009/Logan/Clogan/clogan_core.c#L321

**Comment by jiangteng** [comment]
分配的内存会赋值给_mmap_file_path，_mmap_file_path是个全局变量，所以不需要释放。
![image](https://user-images.githubusercontent.com/7625449/79304599-4d42e000-7f24-11ea-9871-d62cc9ae3de9.png)
