### ISSUE TITLE
$LOGAN_SITE 这路径能说明下么？

### ISSUE THREAD

**Issue by vincent-yan** [Meituan-Dianping/Logan#242]
$LOGAN_SITE 是设置路径的环境变量还是约定的目录，
猜测是/根目录/Logan/LoganSite 这个路径
另外api地址能默认提供个线上测试地址么

**Comment by Retrospection** [comment]
LOGAN_SITE这个目录指的是LoganSite这个目录被放置的路径，API地址的线上测试地址是指什么？

**Comment by vincent-yan** [comment]
$LOGAN_SITE 就是第一次，没找着这应该对应是那个路径
API地址线上测试地址，是说想clone 下来demo可以直接运行，现在是需要直接搭建个java 接口服务吧？

**Comment by Retrospection** [comment]
> $LOGAN_SITE 就是第一次，没找着这应该对应是那个路径
> API地址线上测试地址，是说想clone 下来demo可以直接运行，现在是需要直接搭建个java 接口服务吧？

是的，clone下来之后自建Java服务，因为这个项目是前后端分离的，得分开部署
