### ISSUE TITLE
日志解压工具在哪

### ISSUE THREAD

**Issue by HongshuaiZhao** [Meituan-Dianping/Logan#245]
没有在文件中，找到解密工具。

**Comment by Richard-Cao** [comment]
部署Server端

**Comment by HongshuaiZhao** [comment]
请问wiki中的解密日志的方法，cd Example/Logan-server 可example中没有这个目录，是不是我在本地就没有办法，解密文件了

**Comment by Richard-Cao** [comment]
现在是直接部署server才可以，或者你看老版本的仓库里有Java的解析器工具类。
