### ISSUE TITLE
Android如何在控制台查看打印的日志信息

### ISSUE THREAD

**Issue by angelsusu** [Meituan-Dianping/Logan#250]
请问android如何在控制台查看要打印的日志信息，查看源码接口里面也只有cmd和code会传递出来，并没有log的信息
![image](https://user-images.githubusercontent.com/29451934/81463300-2dcd6900-91eb-11ea-93b4-fe39bc4dd8ac.png)

**Comment by Richard-Cao** [comment]
目前确实没有日志信息。

**Comment by angelsusu** [comment]
我看demo的使用介绍的时候，ios是可以控制是否打印在控制台上的。Android这边是否也可以支持下呢，比如上述接口增加一个参数表示log信息，还是希望可以直接看到打印的日志。
![image](https://user-images.githubusercontent.com/29451934/81468802-65044000-9214-11ea-9959-61ed4e7c636f.png)

**Comment by Richard-Cao** [comment]
主要是感觉写文件之前，加个log拦截，作用不大，和自己打个log一样的

**Comment by angelsusu** [comment]
嗯 的确是的，上层封装会更好些，谢谢

**Comment by Smart-shine** [comment]
还是希望logan能够支持一下Android控制台输出，如果引入日志库还需要自己再单独处理控制台日志，感觉就像一个功能没做完一样，有些缺憾
