### ISSUE TITLE
Android多进程写文件

### ISSUE THREAD

**Issue by angelsusu** [Meituan-Dianping/Logan#252]
你好，我想问下多进程下同时写日志会有问题吗？需要分进程分文件吗？

**Comment by Richard-Cao** [comment]
目前没支持多进程写文件，现在多进程写同一个文件可能会有问题

**Comment by Richard-Cao** [comment]
#249

**Comment by angelsusu** [comment]
那我们先分进程分文件处理是可以的对吧，在这里设置不同的文件名
![image](https://user-images.githubusercontent.com/29451934/81929589-daf41700-9619-11ea-841c-930f33396054.png)

**Comment by Richard-Cao** [comment]
> 那我们先分进程分文件处理是可以的对吧，在这里设置不同的文件名
> ![image](https://user-images.githubusercontent.com/29451934/81929589-daf41700-9619-11ea-841c-930f33396054.png)

可以试试

**Comment by angelsusu** [comment]
我想本地测试下，可不可以直接解密？我没有找到相关的解密工具。

**Comment by Richard-Cao** [comment]
> 我想本地测试下，可不可以直接解密？我没有找到相关的解密工具。

老版本仓库里有Java的解密工具类，你可以捞出来用一下

**Comment by angelsusu** [comment]
可以告知下在哪个版本么以及对应的目录，前期没有服务端的话很难测试

**Comment by angelsusu** [comment]
已找到解密工具，并测试ok，请忽略

**Comment by redspider110** [comment]
> 那我们先分进程分文件处理是可以的对吧，在这里设置不同的文件名
> ![image](https://user-images.githubusercontent.com/29451934/81929589-daf41700-9619-11ea-841c-930f33396054.png)

@angelsusu 大佬，多进程分文件，底层 mmap 有做区分吗？我试了下不同进程写不同文件，在 flush 时会导致内容串文件

**Comment by angelsusu** [comment]
> > 那我们先分进程分文件处理是可以的对吧，在这里设置不同的文件名
> > ![image](https://user-images.githubusercontent.com/29451934/81929589-daf41700-9619-11ea-841c-930f33396054.png)
> 
> @angelsusu 大佬，多进程分文件，底层 mmap 有做区分吗？我试了下不同进程写不同文件，在 flush 时会导致内容串文件

cache也需要根据进程做下区分
