### ISSUE TITLE
请问安卓如何清空本地日志

### ISSUE THREAD

**Issue by hf529270451** [Meituan-Dianping/Logan#258]
我想做成每次打开app都清空一次日志，用户点击上报只上传本次app交互的日志请问怎么做啊

**Comment by Richard-Cao** [comment]
你把日志文件删了就行，Android有方法可以获取到日志文件信息

**Comment by hf529270451** [comment]
行，多谢多谢，请问logan默认的日志清理逻辑是什么呢

**Comment by hf529270451** [comment]
请问是清除logan_cache下的logan.mmap2就可以吗 我看有两个目录，还有个logan_v1  没有见生成

**Comment by Richard-Cao** [comment]
mmap和文件都可以删

**Comment by hf529270451** [comment]
好的，多谢我试一试
