### ISSUE TITLE
android app推到后台后，继续写日志，Logan.w() 写的。定时上传，发现崩溃后，日志丢失，后端解析报错。

### ISSUE THREAD

**Issue by panshimu** [Meituan-Dianping/Logan#263]
android app推到后台后，继续写日志，Logan.w() 写的。但是不确定什么时候进程被杀死，等再次打开app的时候，上传日志，后端java报解析错误，就是日志有丢失了，这个怎么解决呢？
比如说我现在是定时 一个小时上传一次文件，上传成功后就删除本地文件，避免重复上传。在app推到后台后，加入一个小时过去了，app在后台会自动上传，在上传之前调用Logan.f()。然后在后面的一个小时内也产生了部分日志，但是在这个时间内，应用可能异常崩溃了。等app被重新打开的时候，通过获取本地文件然后上传，发现后端报错，然后查看日志，发现少了奔溃之前的日志，和上一次上传对比。

等待解决

**Comment by Richard-Cao** [comment]
切到后台的时候f一下呢
