### ISSUE TITLE
日志上报是需要手动，还是自动会上报

### ISSUE THREAD

**Issue by zhangchaojiong** [Meituan-Dianping/Logan#264]
如题，日志上报是需要手动，还是内部自动会上报。
如果是自动，我好像没有找到设置 server url 的接口。

**Comment by Richard-Cao** [comment]
手动的，如果接入Logan开源server的话，直接使用客户端封装好的上报接口就可以，是需要手动写一下的

**Comment by zhangchaojiong** [comment]
还有一个问题，android sdk 客户端没有发现 日志回捞的相关接口？这部分是要自己实现？

**Comment by Richard-Cao** [comment]
有啊，看下readme，就是上报的接口
