### ISSUE TITLE
怎样把h5日志重定向到手机端

### ISSUE THREAD

**Issue by tangxiangpi** [Meituan-Dianping/Logan#268]
看了美团开源Logan web：前端日志在web端的实现，其中有一部分是
![image](https://user-images.githubusercontent.com/18000558/85985413-499c0100-ba1d-11ea-90f8-473bd0b1391b.png)
这里我有两个疑问：
1、logan web sdk如何判断是运行在手机端的webview中还是pc上？
2、如果我希望将logan wb的日志如同上图一样，利用 JS 桥传给 Logan 客户端，与客户端日志一起落地在 App 本地文件中，那么app需要提供的js bridge的对象和方法是？

**Comment by sylvia1106** [comment]
1、利用UA判断，这部分逻辑不在logan web sdk内部，由美团内一个UA组件封装
2、app端童鞋可继续详解

**Comment by Richard-Cao** [comment]
关于2，需要自己实现一个桥，app端调write的方法就行

**Comment by tangxiangpi** [comment]
> 1、利用UA判断，这部分逻辑不在logan web sdk内部，由美团内一个UA组件封装
> 2、app端童鞋可继续详解

我理解，ogan web sdk默认实现就是往indexedDb写日志； 我想要实现这两个功能，需要修改Logan/WebSDK/src/index.ts 中的写日志的实现，自己去判断是否是运行在手机端webview中，是的话调用jsbridge，不是则写indexedDb，是这样么？

**Comment by tangxiangpi** [comment]
great，而且可以在组件内重写console.log方法，将你上面的这些逻辑都封装在console.log里面，这样H5的写日志的地方就不需要修改了。
