### ISSUE TITLE
Android LogAn1.2.4版本日志丢失问题

### ISSUE THREAD

**Issue by jimoshusheng** [Meituan-Dianping/Logan#269]
1、Android Honor 9i LLD-AL20 8.0.0
测试了一下Android LogAn 1.2.4版本的性能，发现通过for 循环写入10w条日志，会有日志丢失的现象，10W条就剩下1.7W左右的日志，没有杀掉应用，应用也没有崩溃的情况下。

**Comment by Richard-Cao** [comment]
https://github.com/Meituan-Dianping/Logan/blob/master/Example/Logan-Android/app/src/main/java/test/logan/dianping/com/logan/MainActivity.java#L111

for循环测试的时候，稍微sleep一下。

**Comment by jimoshusheng** [comment]
> https://github.com/Meituan-Dianping/Logan/blob/master/Example/Logan-Android/app/src/main/java/test/logan/dianping/com/logan/MainActivity.java#L111
> 
> for循环测试的时候，稍微sleep一下。

1）请问为啥要sleep一下，这样的话，在同一个线程，频繁快速的写入，不就要一直sleep了吗？
2）对比了一下XLog，XLog是没有丢日志的现象的，而且生成的日志大概是1.1M，LogAn的是1.3M，CPU & Memory &耗时好像都要稍逊XLog
3）另外iOS上做这个for 10W 次的操作，没有丢日志的现象。

**Comment by Richard-Cao** [comment]
这个和实现有关，频繁快速的写入也不会是for循环的情况吧，for循环只是测试的时候用

**Comment by Richard-Cao** [comment]
这个并不是「丢日志」，丢日志是指正常情况下日志意外丢失，比如突然断电系统没来得及回写等

**Comment by jimoshusheng** [comment]
> 这个和实现有关，频繁快速的写入也不会是for循环的情况吧，for循环只是测试的时候用

嗯呢，想请教啥为啥for测试的时候，我解密出来的日志，确实是缺失了，这个是啥情况？
对比了XLog 确实没有这样的问题。

**Comment by Richard-Cao** [comment]
好久之前我记过这个问题，现在又忘了。。。和Android的java层代码有关系
