### ISSUE TITLE
为什么之前的解密代码 LoganParser.java新版不见了

### ISSUE THREAD

**Issue by lewic1987** [Meituan-Dianping/Logan#272]
安卓的日志，支持web方式解密吗

**Comment by Richard-Cao** [comment]
因为可以直接接入开源版本的Server了，自带解码功能

**Comment by lewic1987** [comment]
> 因为可以直接接入开源版本的Server了，自带解码功能

因为我们服务端没有接入，主要用的客户端sdk写日志功能，并且ios没有使用，不方便统一接入Server端，麻烦问下有Web版解密代码吗，之前的java文件用不了了，多谢

**Comment by lewic1987** [comment]
@Richard-Cao

**Comment by Richard-Cao** [comment]
web版本的解密代码是指？之前的LogonParser你git回退到老版本还能找到的。

**Comment by rigortek** [comment]
> 安卓的日志，支持web方式解密吗
execute this command, LogonParser.java will come back again.
git reset --hard 6915664beb41e29daf06379fc40a4671e9d07765

**Comment by Richard-Cao** [comment]
> > 安卓的日志，支持web方式解密吗
> > execute this command, LogonParser.java will come back again.
> > git reset --hard [6915664](https://github.com/Meituan-Dianping/Logan/commit/6915664beb41e29daf06379fc40a4671e9d07765)

web方式解密是什么意思？

**Comment by rigortek** [comment]
> > > 安卓的日志，支持web方式解密吗
> > > execute this command, LogonParser.java will come back again.
> > > git reset --hard [6915664](https://github.com/Meituan-Dianping/Logan/commit/6915664beb41e29daf06379fc40a4671e9d07765)
> 
> web方式解密是什么意思？

我回复的是“为什么之前的解密代码 LoganParser.java新版不见了”问题
而不是“web方式解密是什么意思？”

**Comment by lewic1987** [comment]
就是之前的代码是java语言的解密代码，有没有类似web方面语言的解密代码。

**Comment by lewic1987** [comment]
@Richard-Cao

**Comment by lalozhang** [comment]
> 因为可以直接接入开源版本的Server了，自带解码功能

请问Android如何解密？或者说 我如何使用你们server的代码？或者说 使用哪个类 我就可以在Android端解密 或者说 我如何不使用加密

**Comment by Richard-Cao** [comment]
> 就是之前的代码是java语言的解密代码，有没有类似web方面语言的解密代码。

node的那个可以

**Comment by Richard-Cao** [comment]
> > 因为可以直接接入开源版本的Server了，自带解码功能
> 
> 请问Android如何解密？或者说 我如何使用你们server的代码？或者说 使用哪个类 我就可以在Android端解密 或者说 我如何不使用加密

仓库里切到之前的版本 有这个parser类你可以用
