### ISSUE TITLE
日志是按照分片上传的吗

### ISSUE THREAD

**Issue by rogeryleer** [Meituan-Dianping/Logan#275]
看美团的技术文章有写到“Logan作为日志底层库，需要考虑上层传入日志过大的情况。针对这样的场景，Logan会做日志分片处理。以20k大小做分片，每个切片按照Logan的协议进行存储，上报到Logan后台的时候再做反解合并，恢复日志本来的面貌。”

实际测试的时候传输的文件好像并没有做分片，请问这块是需要做什么设置吗

**Comment by Richard-Cao** [comment]
这个是自动的，不需要做什么设置

**Comment by cxMax** [comment]
分片是写的时候，Logan\Clogan\clogan_core.c文件中clogan_write_section
