### ISSUE TITLE
多业务方同时创建、写入多个文件

### ISSUE THREAD

**Issue by violet520** [Meituan-Dianping/Logan#28]
这个可以支持多业务方不同线程同时创建、写入多个文件么，多谢

**Comment by Richard-Cao** [comment]
目前只能写入到一个文件，解析的时候按照业务分开解析就可以了，可以根据type区分

**Comment by Richard-Cao** [comment]
要在C这一层做改动了。

**Comment by violet520** [comment]
这几天我想了一下这样的话，你们就没办法对

**Comment by violet520** [comment]
这几天我想了想：
如果这样，随着业务方存储数据的递增，排查问题一般情况下不需要那么多的数据。
可是目前的做法是无法对汇总的业务数据本地区分，会一起上传
这样就导致不必要的服务端解析，也会提高排查问题的难度。有微信群么，或者QQ群，想跟大佬们一起探讨下

**Comment by Richard-Cao** [comment]
有微信群的，加微信MTDPtech01，然后回复：Logan，就会自动拉你进群。

**Comment by violet520** [comment]
多谢
