### ISSUE TITLE
日志解析报错，急急急！ 和 #142问题一样

### ISSUE THREAD

**Issue by lewic1987** [Meituan-Dianping/Logan#280]
日志原始文件大小看是正常的，但解密失败了，导致有的日志完全解密不出来，客户端已经上线，着急看日志，请问怎么解决啊，是有新版的LoganParser文件可以解决吗？急急急

解密出来只有一行：
{"c":"clogan header","f":1,"l":1594792947998,"n":"clogan","i":1,"m":true}

异常：
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at com.tal.imonkey.downloadlog.LoganParser.parse(LoganParser.java:107)

备注：
1.有些是可以解密成功的。
2.我们没计划接入开源的server端，是说js解密程序是正常的？如果是这样那么麻烦你们更新下java版LoganParser
3.看#142问题里说可以app切换到后台的时候，手动调用一下flush，这能彻底解决问题吗？但是我们已经上线了，对于sdk来说最好不能以强制要求客户端手动调用解决这个问题吧？

**Comment by lewic1987** [comment]
<img width="847" alt="截屏2020-07-16下午2 14 56" src="https://user-images.githubusercontent.com/27275977/87634145-4b7cf880-c76f-11ea-9f47-a880cc4ddfff.png">
这里面有能用的吗

**Comment by lewic1987** [comment]
<img width="847" alt="截屏2020-07-16下午2 14 56" src="https://user-images.githubusercontent.com/27275977/87634277-867f2c00-c76f-11ea-9802-b2e8176cd682.png">
这里面有能用的吗

**Comment by lewic1987** [comment]
Logan/Logan/Server/src/main/java/com/meituan/logan/web/parser/这里面的解析类有能用的吗

**Comment by Richard-Cao** [comment]
老的解析器在新的开源server出来之后就没有再维护了。
切后台执行flush是为了防止后台应用杀死导致日志丢失。
新的server开源代码里也有解密的方法，你可以看一下

**Comment by lewic1987** [comment]
@Richard-Cao 感谢。切后台执行flush这个我明白了是担心日志丢失，已经添加。
解析问题怎么解决呢？可以说下新版具体哪个类哪个方法吗？

**Comment by Richard-Cao** [comment]
具体哪个类我还真不知道…… @zlLuo 后端大佬看下
解析问题一行都出不来我怀疑是不是密钥什么的配错了？这块儿你再看下，按理说解析的核心逻辑应该没变化

**Comment by lewic1987** [comment]
> 具体哪个类我还真不知道…… @zlLuo 后端大佬看下
> 解析问题一行都出不来我怀疑是不是密钥什么的配错了？这块儿你再看下，按理说解析的核心逻辑应该没变化

@Richard-Cao 你好，不是密钥问题，大多数解密是没问题的，个别用户发现日志解密不出来。

**Comment by Richard-Cao** [comment]
这个报错看起来是压缩格式出问题了，很奇怪。。。如果能有复现场景就好了

**Comment by lewic1987** [comment]
@Richard-Cao 有没有js解密代码啊

**Comment by Richard-Cao** [comment]
> @Richard-Cao 有没有js解密代码啊

https://github.com/Meituan-Dianping/Logan/tree/master/Example/Logan-NodeServer
