### ISSUE TITLE
请问日志上报时机是怎么选择的？ 上报完是不是要把本地的日志文件删除掉，重复上报server那边会出现日志重复

### ISSUE THREAD

**Issue by johnxie1** [Meituan-Dianping/Logan#286]
请问日志上报时机是怎么选择的？ 上报完是不是要把本地的日志文件删除掉，重复上报server那边会出现日志重复

**Comment by Richard-Cao** [comment]
上报时机就是你调s方法的时候。一般情况下只要删除当天的copy文件就行了， 其他的可以等过期自动删除

**Comment by johnxie1** [comment]
好的，谢谢

Richard-Cao <notifications@github.com>于2020年7月27日 周一13:57写道：
