### ISSUE TITLE
有js解密方法吗

### ISSUE THREAD

**Issue by lewic1987** [Meituan-Dianping/Logan#288]

**Comment by sylvia1106** [comment]
可参考：https://github.com/Meituan-Dianping/Logan/tree/master/Example/Logan-NodeServer

**Comment by lewic1987** [comment]
> 可参考：https://github.com/Meituan-Dianping/Logan/tree/master/Example/Logan-NodeServer

@sylvia1106 你好，多谢，有单独封装好的方法吗？之前java的就是一个密钥一个文件名

**Comment by lewic1987** [comment]
> > 可参考：https://github.com/Meituan-Dianping/Logan/tree/master/Example/Logan-NodeServer
> 
> @sylvia1106 你好，多谢，有单独封装好的方法吗？之前java的就是一个密钥一个文件名

@sylvia1106 还有那个privateKey是啥 我好像没那个

**Comment by lewic1987** [comment]
@sylvia1106 你好，有封装好的js解密代码吗？

**Comment by sylvia1106** [comment]
解密部分的NodeJS代码已有贡献者提了PR，目前正在验证阶段，您可以先参考Example中的代码来实现解密。
解密所需的privateKey与[WebSDK中配置的publicKey](https://github.com/Meituan-Dianping/Logan/tree/master/Logan/WebSDK#-initconfigglobalconfig)形成一对1024bit的RSA公私钥，目的是确保在用户端存储的日志内容只能被服务端（NodeJS或者Java）解密，您可自行生成您系统专属的公私钥后在两端代码中分别予以配置。

**Comment by lewic1987** [comment]
@sylvia1106 非常感谢回复，我们写日志是用在安卓端的，通过encryptKey16和encryptIv16加密的，现在写了个web程序查看日志，就差解密这部分了，请问如何像以前java版解密功能一样，调用你们封装好的方法解密即可。

**Comment by sylvia1106** [comment]
安卓端日志的解密暂时没有node版本，该部分解密过程可以参考老版java代码：https://github.com/Meituan-Dianping/Logan/blob/1.2.1.swift/Logan/parser-java/src/main/java/LoganParser.java

**Comment by lewic1987** [comment]
@sylvia1106 多谢，请问这个可以用这个解密安卓端的日志吗？https://github.com/Meituan-Dianping/Logan/issues/274

**Comment by lewic1987** [comment]
@sylvia1106 能给写个安卓端日志解密的js版本吗？

**Comment by sylvia1106** [comment]
> @sylvia1106 多谢，请问这个可以用这个解密安卓端的日志吗？#274

这是贡献者提供的解密Web端日志的代码，不可用来直接解密安卓端。

> @sylvia1106 能给写个安卓端日志解密的js版本吗？

暂无支持的计划，可以向我们提PR，已有贡献者向我们提了[Web端日志的node解密](https://github.com/Meituan-Dianping/Logan/pull/251)PR，我们同样欢迎您的贡献，谢谢。

**Comment by lewic1987** [comment]
> 向

没太看懂你这个PR，能给个和java一样的方法吗？入参本地文件源文件，和解密后生成文件。

**Comment by lewic1987** [comment]
@sylvia1106 你们封装的安卓端加密算法，写个js版的解密不是很简单吗？麻烦能否快速提供下啊，业务一般用到的是客户端写日志sdk，至于解密日志就是一个后端程序，可能会用各种语言解密，麻烦提供下js版本的解密吧

**Comment by lewic1987** [comment]
> 安卓端日志的解密暂时没有node版本，该部分解密过程可以参考老版java代码：https://github.com/Meituan-Dianping/Logan/blob/1.2.1.swift/Logan/parser-java/src/main/java/LoganParser.java

@sylvia1106 这端代码在干啥啊 转换成js语言应该怎么处理

int length = (content[i] & 0xFF) << 24 |
                            (content[i + 1] & 0xFF) << 16 |
                            (content[i + 2] & 0xFF) << 8 |
                            (content[i + 3] & 0xFF);
                    i += 3;
                    int type;
                    if (length > 0) {
                        int temp = i + length + 1;
                        if (content.length - i - 1 == length) { //异常
                            type = 0;
                        } else if (content.length - i - 1 > length && '\0' == content[temp]) {
                            type = 1;
                        } else if (content.length - i - 1 > length && '\1' == content[temp]) { //异常
                            type = 2;
                        } else {
                            i -= 4;
                            continue;
                        }

**Comment by Richard-Cao** [comment]
@lewic1987 https://github.com/Meituan-Dianping/Logan/wiki/How-to-use-demo#server-demo
你在老版本的仓库里，把删掉的这个server.js找回来就行了

**Comment by Richard-Cao** [comment]
https://github.com/Meituan-Dianping/Logan/blob/1.2.6/Example/Logan-Server/server.js

**Comment by lewic1987** [comment]
@sylvia1106 @Richard-Cao 感谢两位大神的指导，最终我参照https://github.com/Meituan-Dianping/Logan/issues/274这个简单修改了下可以了。

**Comment by lewic1987** [comment]
@sylvia1106 @Richard-Cao 感谢两位大神的指导，最终我参照https://github.com/Meituan-Dianping/Logan/issues/274  这个简单修改了下可以了。
