### ISSUE TITLE
找不到server.js啊 想用js解密的代码

### ISSUE THREAD

**Issue by lewic1987** [Meituan-Dianping/Logan#289]

**Comment by Richard-Cao** [comment]
https://github.com/Meituan-Dianping/Logan/tree/master/Example/Logan-NodeServer

**Comment by lewic1987** [comment]
@Richard-Cao 这是日志上报的代码吧，我要解密的代码啊

**Comment by Richard-Cao** [comment]
曾经有过：https://github.com/Meituan-Dianping/Logan/wiki/How-to-use-demo
