### ISSUE TITLE
podfile文件里面使用了use_frameworks!,编译报错

### ISSUE THREAD

**Issue by zxfmpy** [Meituan-Dianping/Logan#29]
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!
target 'xxxx' do
  pod 'Logan', '~> 1.1.1'
end

**Comment by jiangteng** [comment]
是的，因为Logan中包含了一些c库，使用use_frameworks的方式会导致c库编译出问题

**Comment by zxfmpy** [comment]
目前有办法可以解决么，项目里面使用了swift的库，所以这个use_frameworks还是要用的

**Comment by zxfmpy** [comment]
已找到解决方案，把整个SDK源工程集成进去

**Comment by jiangteng** [comment]
可以使用1.2.2 版本支持use_frameworks!方式。pod 'Logan', '1.2.2'
