### ISSUE TITLE
App 同一进程按照模块拆分文件

### ISSUE THREAD

**Issue by redspider110** [Meituan-Dianping/Logan#292]
咨询下有办法支持：不同类型写入不同文件吗？因为现在同一个 App 中可能会有多个模块在同时写文件，想拆分为每个模块对应一个文件，因为不熟悉 Logan 底层 C 的实现，请教下 @Richard-Cao 
- LoganThread.java 在 doWriteLog2File 中会写入文件名，可以在这里根据不同模块拆分文件吗
- 如果拆分后，底层 C 会自动 flush 所有打开的拆分文件吗
谢谢

**Comment by Richard-Cao** [comment]
#255 这里说吧
