### ISSUE TITLE
Android问题

### ISSUE THREAD

**Issue by 00011110** [Meituan-Dianping/Logan#299]
1. demo中上传接口有 
xxxx:3000/logupload
xxxx:8080/logan/upload.json
两个接口有什么区别？ 我使用xxxx:8080/logan/upload.json 一直提示日志上传失败，但是后台其实有log了 ：（

2. crash log为什么只有标示，没有具体信息，这个功能非常重要啊
  
![20200917142534](https://user-images.githubusercontent.com/3993433/93428449-09e50700-f8f2-11ea-94fd-1d59eae64393.jpg) 

谢谢

**Comment by Richard-Cao** [comment]
本地key和后台之后统一才能解析数据。你本地换key的话要把之前的文件删了，重新写日志再测。
我再帮你艾特一下后端同学

**Comment by fleetcor** [comment]
试过的，本地key换了，服务端没改，竟然还能解析

现在最关心问题，为什么crash log信息没有啊？

**Comment by Richard-Cao** [comment]
别占用type为1的，用其他的
