### ISSUE TITLE
适配Android11

### ISSUE THREAD

**Issue by fengcoding51** [Meituan-Dianping/Logan#309]
这个库可以适配Android11吗？读写文件会存在问题吗？

**Comment by Richard-Cao** [comment]
哪方面问题？

**Comment by Go-oG** [comment]
在Android 10和11上由于Android 分区存储的限制，导致APP无法在外部存储目录下写入文件，对于公共目录需要通过MediaStore API或者Storage Access Framework方式访问 例如 Download 文件夹。但是目前Logan似乎不支持将路径配置为公共目录。

**Comment by Richard-Cao** [comment]
建议日志还是写在沙盒里
