### ISSUE TITLE
我编译源码的时候zlib报错 undefined reference to 'deflateInit2_'，在Android studio里使用CMake编译，请问这是怎么回事

### ISSUE THREAD

**Issue by RenZhongrui** [Meituan-Dianping/Logan#31]

**Comment by bright999** [comment]
请问你是怎么编译的？能详细写写么

**Comment by RenZhongrui** [comment]
问题已经处理了，感谢您的回复

**Comment by bright999** [comment]
@RenZhongrui 我现在也碰到了这个问题，能问一下，你当时是怎么解决的么？
D:\test\demos\Logan-Android\app\src\main\cpp\Clogan/zlib_util.c:46: error: undefined reference to 'deflateInit2_'
D:\test\demos\Logan-Android\app\src\main\cpp\Clogan/zlib_util.c:77: error: undefined reference to 'deflate'
D:\test\demos\Logan-Android\app\src\main\cpp\Clogan/zlib_util.c:79: error: undefined reference to 'deflateEnd'
D:\test\demos\Logan-Android\app\src\main\cpp\Clogan/zlib_util.c:158: error: undefined reference to 'deflateEnd'
D:\test\demos\Logan-Android\app\src\main\cpp\Clogan/zlib_util.c:187: error: undefined reference to 'deflateEnd'
clang.exe: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bright999** [comment]
https://blog.csdn.net/bright789/article/details/84523298
