### ISSUE TITLE
ios端封装后性能问题

### ISSUE THREAD

**Issue by yangjie2** [Meituan-Dianping/Logan#313]
ios端测试结果：连续写入10万条日志，需要花费45s左右时间。

ios层使用单独队列处理日志写入，不过性能也消耗在了线程调度上。

**Comment by Mr-xiaojun** [comment]
@yangjie2 Logan 实际上只是把io消耗放在了后台线程，实际使用中其实io压力不会有这么大的，Logan在内部使用时一直在向精简日志方向运维，如果要特定场景要进行大量日志记录Logan实际上是不太适合的，因为内部对存储也是有限制的。
