### ISSUE TITLE
我看你们后端就用了个mysql，大量日志的搜索是不是极慢啊

### ISSUE THREAD

**Issue by yibingxiong** [Meituan-Dianping/Logan#317]
```    
<select id="queryByTaskIdTypeKeyword" parameterType="map" resultMap="resultMap">
        SELECT * FROM logan_log_detail
        WHERE task_id = #{taskId}
        <if test="types != null and types.size() != 0">
            AND log_type IN
            <foreach collection="types" item="type" index="index" open="(" close=")" separator=",">
                #{type}
            </foreach>
        </if>
        <if test="keyword !=null">
            AND content LIKE CONCAT('%',#{keyword,jdbcType=VARCHAR},'%');
        </if>
    </select>
```
比如上边这条sql， 直接用了左模糊，根本无法走索引

**Comment by Mr-xiaojun** [comment]
后端应该只是做了日志文件的搜索，日志内容搜索需要自建es的@yibingxiong 

> ```
> <select id="queryByTaskIdTypeKeyword" parameterType="map" resultMap="resultMap">
>         SELECT * FROM logan_log_detail
>         WHERE task_id = #{taskId}
>         <if test="types != null and types.size() != 0">
>             AND log_type IN
>             <foreach collection="types" item="type" index="index" open="(" close=")" separator=",">
>                 #{type}
>             </foreach>
>         </if>
>         <if test="keyword !=null">
>             AND content LIKE CONCAT('%',#{keyword,jdbcType=VARCHAR},'%');
>         </if>
>     </select>
> ```
> 
> 比如上边这条sql， 直接用了左模糊，根本无法走索引

后端只是做了日志文件的搜索，日志内容的搜索要自建es的

**Comment by Mr-xiaojun** [comment]
> ```
> <select id="queryByTaskIdTypeKeyword" parameterType="map" resultMap="resultMap">
>         SELECT * FROM logan_log_detail
>         WHERE task_id = #{taskId}
>         <if test="types != null and types.size() != 0">
>             AND log_type IN
>             <foreach collection="types" item="type" index="index" open="(" close=")" separator=",">
>                 #{type}
>             </foreach>
>         </if>
>         <if test="keyword !=null">
>             AND content LIKE CONCAT('%',#{keyword,jdbcType=VARCHAR},'%');
>         </if>
>     </select>
> ```
> 
> 比如上边这条sql， 直接用了左模糊，根本无法走索引

后端应该只是做了日志文件的列表的搜索，日志内容搜索需要用es自建索引的

**Comment by yibingxiong** [comment]
好的，了解了
