### ISSUE TITLE
日志分析平台还没开放么？

### ISSUE THREAD

**Issue by singleli** [Meituan-Dianping/Logan#318]
https://tech.meituan.com/2020/01/09/meituan-logan.html
看帖子里，有个“日志分析平台展示的某篇日志详情示意图”还挺丰富，这块目前工程里的还很简陋，是没放出来么

**Comment by Richard-Cao** [comment]
是的，还没有

**Comment by tututututututu** [comment]
有计划开放吗

**Comment by tututututututu** [comment]
@Richard-Cao 有计划开放吗

**Comment by Richard-Cao** [comment]
> @Richard-Cao 有计划开放吗

@sylvia1106
