### ISSUE TITLE
Logan的c/c++部分能使用win的android studio编译么？

### ISSUE THREAD

**Issue by bright999** [Meituan-Dianping/Logan#33]
我最近试着自己使用win7 版的android studio 3.0 beta 5 的cmake编译c/c++部分(CLogan和mbedtls)，要么就是编译通过，但是不生成so，要么就是报错CMake Error at D:/test/demos/testloglib/app/src/main/cpp/mbedtls/library/CMakeLists.txt:161 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "mbedtls".
所以我想请问一下，使用这样的环境和工具，能否编译成功？或者有没有相应的教程可以让我们参考，谢谢

**Comment by Richard-Cao** [comment]
windows我没试过……

**Comment by RenZhongrui** [comment]
windows 10 可以的  ndk版本配置成16的  Android studio 3.0.1，估计win7问题不大

**Comment by bright999** [comment]
@RenZhongrui  我现在碰到了
09:34:48.492 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   D:\test\demos\Logan-Android\app\src\main\cpp\Clogan/zlib_util.c:67: error: undefined reference to 'deflateInit2_'
09:34:48.492 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   D:\test\demos\Logan-Android\app\src\main\cpp\Clogan/zlib_util.c:98: error: undefined reference to 'deflate'
09:34:48.493 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   D:\test\demos\Logan-Android\app\src\main\cpp\Clogan/zlib_util.c:100: error: undefined reference to 'deflateEnd'
09:34:48.493 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   D:\test\demos\Logan-Android\app\src\main\cpp\Clogan/zlib_util.c:179: error: undefined reference to 'deflateEnd'
09:34:48.493 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   D:\test\demos\Logan-Android\app\src\main\cpp\Clogan/zlib_util.c:208: error: undefined reference to 'deflateEnd'
09:34:48.493 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   clang.exe: error: linker command failed with exit code 1 (use -v to see invocation)
我使用的是android-ndk-r15b 和android-ndk-r16b 和ndk 1717.0.4754217 ，android studio  3.0 beta 5 win7 64位系统，你的意思还需要换换android studio么

**Comment by bright999** [comment]
@RenZhongrui 我刚刚下载了android studio 3.0.1 和使用android-ndk-r16b 在win7 64位上面还是会报那个错误

**Comment by bright999** [comment]
解决方案已经发布，希望能帮到后面来踩坑的兄弟https://blog.csdn.net/bright789/article/details/84523298

**Comment by 529951164** [comment]
windows我捣鼓了好就没有成功，换了mac就好了。。。

**Comment by RenZhongrui** [comment]
用MAC好一些



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月17日 16:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Meituan-Dianping/Logan] Logan的c/c++部分能使用win的android studio编译么？ (#33) |

windows我捣鼓了好就没有成功，换了mac就好了。。。
