### ISSUE TITLE
近期还会开源那些功能

### ISSUE THREAD

**Issue by lookcat** [Meituan-Dianping/Logan#335]
虽然有点简陋，不过还不错。

**Comment by Richard-Cao** [comment]
你对哪些功能感兴趣

**Comment by lookcat** [comment]
1. 动态指令
`import Vue from 'vue'
import Logan from 'logan-web'

// 日志采集

// Logan.initConfig({
// 	reportUrl: 'https://yourServerAddressToAcceptLogs',
// 	publicKey: '-----BEGIN PUBLIC KEY-----\n'+
//         'MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgG2m5VVtZ4mHml3FB9foDRpDW7Pw\n'+
//         'Foa+1eYN777rNmIdnmezQqHWIRVcnTRVjrgGt2ndP2cYT7MgmWpvr8IjgN0PZ6ng\n'+
//         'MmKYGpapMqkxsnS/6Q8UZO4PQNlnsK2hSPoIDeJcHxDvo6Nelg+mRHEpD6K+1FIq\n'+
//         'zvdwVPCcgK7UbZElAgMBAAE=\n'+
//         '-----END PUBLIC KEY-----',
//     errorHandler: function(e) {},
//     succHandler: function(logItem) {
//         var content = logItem.content;
//         var logType = logItem.logType;
//         var encrypted = logItem.encrypted;
//         console.log('Log Succ:' + content);
//     }
// });

Vue.directive('track', {
  bind:(el, binding, vnode)=>{
    //这里参数是根据自己业务可以自己定义
      let params = {
        currentUrl:binding.value.currentUrl,
        actionType:binding.value.actionType,
        frontTriggerType:binding.value.triggerType,
        businessCode:binding.value.businessCode,
        behavior:binding.value.behavior,
        service:'xxx',
      }

    //如果是浏览类型，直接保存
    if (binding.value.triggerType == 'browse'){
      //调用后台接口保存数据
      // Logan.report(params);
      api.eventTrack.saveEventTrack(params);
    } else if (binding.value.triggerType == 'click'){
      //如果是click类型，监听click事件
      el.addEventListener('click', (event) => {
        //调用后台接口保存数据
        // api.eventTrack.saveEventTrack(params);
        console.log(params);
        Logan.log(params, 1);
      }, false)
    }

  }
});
`

` <el-form-item class="loginBtn">
          <el-button type="primary" @click="submitForm('ruleForm')" v-track="{triggerType:'click',currentUrl: $route.path,behavior:'点击xxx按钮',businessCode: 19,actionType:'xxx-click'}">登录</el-button>
        </el-form-item>`

2. DMP 系统相关的一些开源
