### ISSUE TITLE
咱这个库以后还更新新功能吗

### ISSUE THREAD

**Issue by RenZhongrui** [Meituan-Dianping/Logan#34]
日志文件不能无限大，目前Logan日志文件最大限制为10M，遇到大于10M的情况，应该如何处理最佳？是丢掉前面的日志，还是丢掉追加的日志，还是做分片处理呢？

**Comment by jiangteng** [comment]
Logan会一直维护更新，如果日志超过10m，后续的日志将会丢弃。
