### ISSUE TITLE
上传完日志 目录下仍然含有logan.mmap2文件 且大小在一百多k 

### ISSUE THREAD

**Issue by SnailLife** [Meituan-Dianping/Logan#347]

**Comment by Richard-Cao** [comment]
这个没关系的，上传日志传的是具体的文件，不是mmap2文件

**Comment by SnailLife** [comment]
额 主要是我们这边发现当 ios app退到后台 会出现缺失几分钟的日志，根据我们同事进行业务调试 发现那段时间其实app是有在运转并输出日志的

**Comment by Richard-Cao** [comment]
前后台切换的时候，调一下flush

**Comment by SnailLife** [comment]
这个我们都有调用 就是防止没有立即下沉带来的数据丢失

**Comment by Richard-Cao** [comment]
> 额 主要是我们这边发现当 ios app退到后台 会出现缺失几分钟的日志，根据我们同事进行业务调试 发现那段时间其实app是有在运转并输出日志的

你这个是上传的时候发现退到后台那段时间日志丢失了？

**Comment by SnailLife** [comment]
是的 必入仔3分到6分之间啥都没有 6分33秒后才有一些日志 但其实3分到6分 app处于活跃状态是肯定产生日志了的

**Comment by Richard-Cao** [comment]
帮你assign了iOS同学

**Comment by SnailLife** [comment]
> 帮你assign了iOS同学

大佬 请问ios大佬怎么说
