### ISSUE TITLE
解密问题

### ISSUE THREAD

**Issue by 597579501** [Meituan-Dianping/Logan#352]
说了那么多。就是不想整套用你们的东西就是用呗。我就想客户端用一下。
我看了这么多issues都是希望客户端能有个解密的东西。自己独立部署。
重复的问题问了那么多。你就不能提供一个客户端解密的方案供大家使用么。
就跟我去问产品问题。产品来句。看文档去吧。文档要是看明白我还问你？

**Comment by Richard-Cao** [comment]
独立解密的类是有的，你可以直接用

**Comment by Hiboboo** [comment]
> 独立解密的类是有的，你可以直接用

你好，请问具体是哪个类？在Server模块还是Android模块里的？
目前我在Android模块下没找到相关的类。

其实我们就是有这么一个小需求，因为目前咱们这个日志上传的是整个文件，但我们这个应用对流量要求很严苛，所以就是想直接在客户端这边做一个数据解密，然后再做一次精准筛选，最后只上传特定的一部分日志内容。
因此就需要在客户端进行一次解密。

盼回复！

**Comment by Hiboboo** [comment]
> 

自问自答了，哈哈。
我已经在Server模块找到了相关解析类，并用main方法做了测试，结果OK。

**Comment by Richard-Cao** [comment]
> 

github能看到以前的版本，是有个类似的解析类的，反正和你找到的这个差不多 哈哈
