### ISSUE TITLE
Android，超出MaxFile之后，日志不会再写入了？

### ISSUE THREAD

**Issue by GeorgeWupanpan** [Meituan-Dianping/Logan#353]
Android，超出MaxFile之后，日志不会再写入了？我发现必须每次重新启动app，才会创建log文件了。

**Comment by Richard-Cao** [comment]
对 超出就不写了

**Comment by GeorgeWupanpan** [comment]
有什么方法，可以重新创建一个log文件写入吗？

**Comment by Richard-Cao** [comment]
> 有什么方法，可以重新创建一个log文件写入吗？

没有哦。你maxFile设置的多少m？

**Comment by GeorgeWupanpan** [comment]
1m哦。设置太大，上传太浪费流量了吧。

**Comment by Richard-Cao** [comment]
> 1m哦。设置太大，上传太浪费流量了吧。

其实10m以内问题都不大其实，1m确实太小了，估计一些图都超过1m了吧

**Comment by GeorgeWupanpan** [comment]
> > 1m哦。设置太大，上传太浪费流量了吧。
> 
> 其实10m以内问题都不大其实，1m确实太小了，估计一些图都超过1m了吧

好家伙我是这么理解的。现在logan是根据每次注册初始化，会生成一份log文件。然后maxFile只是控制这份文件的大小。我是不是可以在写入的时候监听这个log文件的大小，当文件超出我规定的大小，就不在写入了，然后重新注册初始化，这样是不是没啥问题捏？

**Comment by Richard-Cao** [comment]
> > > 1m哦。设置太大，上传太浪费流量了吧。
> > 
> > 
> > 其实10m以内问题都不大其实，1m确实太小了，估计一些图都超过1m了吧
> 
> 好家伙我是这么理解的。现在logan是根据每次注册初始化，会生成一份log文件。然后maxFile只是控制这份文件的大小。我是不是可以在写入的时候监听这个log文件的大小，当文件超出我规定的大小，就不在写入了，然后重新注册初始化，这样是不是没啥问题捏？

没这么想过哎，你试试？

**Comment by GeorgeWupanpan** [comment]
> 的

理论上应该是可以的哈哈哈哈，我试试吧。

**Comment by GeorgeWupanpan** [comment]
> > > > 1m哦。设置太大，上传太浪费流量了吧。
> > > 
> > > 
> > > 其实10m以内问题都不大其实，1m确实太小了，估计一些图都超过1m了吧
> > 
> > 
> > 好家伙我是这么理解的。现在logan是根据每次注册初始化，会生成一份log文件。然后maxFile只是控制这份文件的大小。我是不是可以在写入的时候监听这个log文件的大小，当文件超出我规定的大小，就不在写入了，然后重新注册初始化，这样是不是没啥问题捏？
> 
> 没这么想过哎，你试试？

我试过了 是可以的

**Comment by GeorgeWupanpan** [comment]
logan有接口获取当前log文件的大小吗? 还是只能自己通过文件路径自己new成File自己算哟？

**Comment by Richard-Cao** [comment]
> logan有接口获取当前log文件的大小吗? 还是只能自己通过文件路径自己new成File自己算哟？

Logan.getAllFilesInfo()
