### ISSUE TITLE
为啥java与c对应的接口会中间多加一个1？

### ISSUE THREAD

**Issue by bright999** [Meituan-Dianping/Logan#36]
java代码
com.dianping.logan.CLoganProtocol类里面
    private native int clogan_init(String cache_path, String dir_path, int max_file,
            String encrypt_key_16, String encrypt_iv_16);
    private native int clogan_open(String file_name);
    private native void clogan_debug(boolean is_debug);
    private native int clogan_write(int flag, String log, long local_time, String thread_name, long thread_id, int is_main);
    private native void clogan_flush();

这些函数对应的c文件里的代码(clogan_protocol.c clogan_protocol.h)是
Java_com_dianping_logan_CLoganProtocol_clogan_1write(...)
Java_com_dianping_logan_CLoganProtocol_clogan_1init(...)
Java_com_dianping_logan_CLoganProtocol_clogan_1open(...)
Java_com_dianping_logan_CLoganProtocol_clogan_1flush(...)
Java_com_dianping_logan_CLoganProtocol_clogan_1debug(...)

我发现函数中间多了一个1，不对应呀，我的理解应该会报错，但现实是我试了，可以编译并且成功运行正常，当我去掉那个1反而调用失败，说找不到相应实现，心中非常不解，还望大家帮忙解答，谢谢

**Comment by Richard-Cao** [comment]
这是自动生成jni接口的时候加的，表示下划线区分
