### ISSUE TITLE
Logan-web-sdk不支持vite工程

### ISSUE THREAD

**Issue by ztw2010** [Meituan-Dianping/Logan#364]
在vite项目中引入npm install logan-web 打包部署项目后报require is not defined是需要配置vite的rollup吗还是说logan-web本身不支持vite

**Comment by Seashell113** [comment]
+1，发现问题出在es6-promise依赖的引用处，require无法被浏览器解析
`Sm=require("es6-promise");window.Promise||(window.Promise=Sm);`

**Comment by Richard-Cao** [comment]
> +1，发现问题出在es6-promise依赖的引用处，require无法被浏览器解析 `Sm=require("es6-promise");window.Promise||(window.Promise=Sm);`

要不要pr一波

**Comment by Seashell113** [comment]
> #437 
@Richard-Cao 
已提交，es6-promise构造的对象里缺个Symbol.species无力修改了，赋值的时候ignore了一下......

**Comment by liyuan1125** [comment]
这个问题修复了，什么时候发布？？？四个月了

**Comment by houliang999** [comment]
我也遇到了，感觉所有vite项目里面所有的require语法都不行，我一开始也定位到了es6-promise使用到的地方，我手动改成了import的，但是还有其他用到reuqire的都不行。。

**Comment by Richard-Cao** [comment]
> 我也遇到了，感觉所有vite项目里面所有的require语法都不行，我一开始也定位到了es6-promise使用到的地方，我手动改成了import的，但是还有其他用到reuqire的都不行。。

目前pr只改了这一处，还有啥地方

**Comment by houliang999** [comment]
比如save-log.ts和encryption.ts

**Comment by Richard-Cao** [comment]
> 比如save-log.ts和encryption.ts

这个能穷举吗

**Comment by houliang999** [comment]
em..这个不需要穷举啊，你到这两个文件关键字require搜索就行，我目前改成import语法之后，就能正常使用了

**Comment by Richard-Cao** [comment]
> em..这个不需要穷举啊，你到这两个文件关键字require搜索就行，我目前改成import语法之后，就能正常使用了

老哥pr一波？

**Comment by houliang999** [comment]
我在公司电脑上改的，连不了外网。。。

**Comment by Richard-Cao** [comment]
> 我在公司电脑上改的，连不了外网。。。

大佬在华为吗

**Comment by Seashell113** [comment]
#492 
项目里没有使用加密，这块的确实漏改了，估计没有引用到所以也没报错
src下看了就这两处使用了require引入，都替换掉了 
顺便把加密库的types包加上了不然一直报错，allready命令运行过没有问题了

话说还有人在做cr么 @Richard-Cao

**Comment by Richard-Cao** [comment]
> #492 项目里没有使用加密，这块的确实漏改了，估计没有引用到所以也没报错 src下看了就这两处使用了require引入，都替换掉了 顺便把加密库的types包加上了不然一直报错，allready命令运行过没有问题了
> 
> 话说还有人在做cr么 @Richard-Cao

我嘛。你这个pr是vite可以了是吧，如果不用vite的测过么

**Comment by Seashell113** [comment]
> 

源码jest/demo和本地项目构建都ok 但毕竟没有全覆盖的验证，最好还是再完整测试下，避免类似上面的情况

**Comment by saleemshenlin** [comment]
看到源码改了，但是没有发布到NPM上

**Comment by Richard-Cao** [comment]
> 看到源码改了，但是没有发布到NPM上

@luoheng158 @sylvia1106 你们谁有发布权限
