### ISSUE TITLE
iOS-SDK `deviceType`改成`platform`，并发新的公开的版本

### ISSUE THREAD

**Issue by PCBZ** [Meituan-Dianping/Logan#375]
iOS公开的last updated version 1.2.7，上传的接口httpHeader填写的`deviceType`和android，server的不匹配，android和server的是`platform`

**Comment by Richard-Cao** [comment]
卧槽这个还没发吗 我艾特下iOS小伙伴 @Mr-xiaojun

**Comment by zkl5244** [comment]
这个问题还没改吗

**Comment by Richard-Cao** [comment]
iOS 1.2.8已经更新了
