### ISSUE TITLE
iOS 当文件写入内容超过最大容量时，Logon默认不再写入，求解决？

### ISSUE THREAD

**Issue by bullerliu** [Meituan-Dianping/Logan#376]

**Comment by Richard-Cao** [comment]
目前Android和iOS都是这个策略，毕竟总得有个大小限制

**Comment by lewic1987** [comment]
@Richard-Cao 可以指定日志写入文件吗？某个时机会上传日志，希望上传成功后删除日志文件，重新创建个日志文件继续写入新的日志。

**Comment by Richard-Cao** [comment]
> 

目前不支持，只要是调了Logan接口的都会写入文件，上传成功后删除文件是可以的

**Comment by kidGuo** [comment]
考虑超过最大容量，将最先写入的删除嘛

**Comment by Richard-Cao** [comment]
> 考虑超过最大容量，将最先写入的删除嘛

考虑过，不过最后选择的方案是不再写入

**Comment by pengStyle** [comment]
可以借鉴下CocoaLumberjack的实现，文件达到最大容量后，会新建一个文件继续写入
