### ISSUE TITLE
SendLogCallback  和SendLogRunnable的疑问

### ISSUE THREAD

**Issue by qiao236349845** [Meituan-Dianping/Logan#379]
android 文档上推荐的数据上传方式是使用SendLogCallback接口，但是没法上传成功了就删除，所以数据会有重复的。使用SendLogRunnable上传成功的可以直接使用文件引用进行删除。这么比较，推荐使用的方式，好像没有不推荐的好用啊，是我的错觉吗

**Comment by Richard-Cao** [comment]
是这样的，Logan是一天一个文件，一般默认删除的是上传当天的文件的副本，而不删除其他的文件，所以推荐用callback，runnable就是说你要是想自己删除其他的文件也可，两种不同的方式
