### ISSUE TITLE
上传

### ISSUE THREAD

**Issue by qidianli** [Meituan-Dianping/Logan#38]

**Comment by qidianli** [comment]
为什么说.copy文件找不到，但是getAll是有的，手机打开也确实有

**Comment by Richard-Cao** [comment]
.copy文件找不到是什么时候提示的

**Comment by littlecat1988** [comment]
在上传的时候，写到本地的日志文件并没有.copy的扩展名，但是send回调回来的file的path是带了.copy的扩展名，导致了文件找不到

**Comment by Richard-Cao** [comment]
send完成之后会删掉.copy文件的

**Comment by littlecat1988** [comment]
send的时候回调返回的是xxx.copy的文件地址，但是这个地址实际存储的是xxx,导致上传文件没找到

**Comment by Richard-Cao** [comment]
这个问题是上传的时候找不到文件所以上传失败吗？
