### ISSUE TITLE
Server 考虑过springboot支持吗？

### ISSUE THREAD

**Issue by 937447974** [Meituan-Dianping/Logan#381]
Server 启动比较麻烦，希望能支持springboot启动

**Comment by Richard-Cao** [comment]
帮你assign给后端小伙伴哈

**Comment by victoriafeng** [comment]
强烈要求 加1

**Comment by Richard-Cao** [comment]
> 强烈要求 加1

我也+1 
@zlLuo

**Comment by Richard-Cao** [comment]
或者大佬们PR一波？

**Comment by zhangbo00** [comment]
@937447974 @victoriafeng 
我自己从master分支，拉出来简单改了一版，改为了springboot方式启动。
日志改为了logback。

有需要的话可以参考一下不保证准确性，就不提PR了。

**Comment by zhangbo00** [comment]
https://github.com/zhangbo00/Logan/tree/springboot

**Comment by 937447974** [comment]
@zhangbo00 谢谢，我也改了一版，后台用的springboot\mybatis pro+mysql
