### ISSUE TITLE
mmap写回的问题

### ISSUE THREAD

**Issue by stevenxiaoyang** [Meituan-Dianping/Logan#39]
每次app切掉的时候，会flush，也就是把mmap的数据写入文件。而系统把mmap从内存写回文件的时机并不确定，会不会flush的时候，mmap还没有把内存的数据写回mmap文件导致文件内容丢失？

**Comment by stevenxiaoyang** [comment]
我应该是表述的有问题，我详细说下我的疑惑。
不用mmap的话，正常都是写内存，然后app退出的时候把内存中的数据写回文件。但是app退出的原因很多，有可能通知不到，所以内存的数据没有写回。所以才会用mmap，把写回的时机交给系统。
我看了Logan里每次app退出的时候会调用write_flush_clogan，也就是把mmap里的数据写入文件中，但是这和不用mmap一样，可能会通知不到，并不会调用write_flush_clogan，所以数据可能还在临时的mmap文件里，我看了下源码，每次重新启动后mmap文件被置空了（可能我源码理解错了），这样不还是会丢数据吗

**Comment by jiangteng** [comment]
你理解的没错，正常操作情况下mmap不起作用。但在异常情况下比如：断电，crash，这时mmap就能保证日志不丢失。

**Comment by lxz2014** [comment]
也遇到过mmap没有成功写入，不知道啥原因，没有详细找。测试的时候mmap是正常的，但投入生产环境用的时候，大多日志都丢了，不知道是不是和应用开了多个进程有关原因导致的。

**Comment by Richard-Cao** [comment]
目前Logan不支持多进程
