### ISSUE TITLE
最新稳定代码是tag1.2.4那个吗

### ISSUE THREAD

**Issue by lewic1987** [Meituan-Dianping/Logan#399]

**Comment by lewic1987** [comment]
<img width="396" alt="截屏2022-03-11 下午4 11 53" src="https://user-images.githubusercontent.com/27275977/157828270-8aa92e8d-2f59-4b11-8d28-4c7efe02c67c.png">

**Comment by Richard-Cao** [comment]
https://github.com/Meituan-Dianping/Logan/blob/master/Example/Logan-Android/READMD-zh.md
