### ISSUE TITLE
关于日志上传问题

### ISSUE THREAD

**Issue by yihuajia** [Meituan-Dianping/Logan#40]
请教下，当日志大小达到临界值时(比如达到10m)，那么做到达到这个临界时上把日志上传给后台呢？

**Comment by Richard-Cao** [comment]
这个Logan内部没有逻辑处理，可以在外部业务处理。

**Comment by yihuajia** [comment]
通过那个获取日志文件的方法，然后去判断大小再去处理？还是说有其它的方法可以去处理呢？

**Comment by Richard-Cao** [comment]
目前就是通过获取日志文件信息，判断大小然后处理

**Comment by yihuajia** [comment]
好的吧，那不是还得加个定时任务。建议加个达到临界值的回调

**Comment by Richard-Cao** [comment]
好的，这个我考虑一下
