### ISSUE TITLE
IOS 数据打入异常  

### ISSUE THREAD

**Issue by tietouwaa** [Meituan-Dianping/Logan#400]
业务使用ios-sdk 打入日志到server 失败 ，server 错误日志为400 ，需要nginx 配置  Content-Type ： binary/octet-stream 吗？

**Comment by tietouwaa** [comment]
或者拉我进微信群吧 美团小助手没同意我的好友请求

**Comment by Richard-Cao** [comment]
> 或者拉我进微信群吧 美团小助手没同意我的好友请求

你可以加我微信我拉你

**Comment by Richard-Cao** [comment]
> 业务使用ios-sdk 打入日志到server 失败 ，server 错误日志为400 ，需要nginx 配置 Content-Type ： binary/octet-stream 吗？

你试一下

**Comment by NickMeepo** [comment]
> 你可以加我微信我拉你

Hello，请问可以拉进群吗？公司也用Logan遇到了一些问题，看这里没什么更新了。

我的微信号是NickMeepo，您随时可以加我，感谢！

**Comment by Richard-Cao** [comment]
> > 你可以加我微信我拉你
> 
> Hello，请问可以拉进群吗？公司也用Logan遇到了一些问题，看这里没什么更新了。
> 
> 我的微信号是NickMeepo，您随时可以加我，感谢！

加你了
