### ISSUE TITLE
我上传成功直接删除日志文件会影响日志写入吗？会丢日志吗？

### ISSUE THREAD

**Issue by lewic1987** [Meituan-Dianping/Logan#405]
为什么当天的日志拷贝了一份副本，如果我当天的日志上传成功直接删除日志文件会影响日志写入吗？会丢日志吗？

**Comment by Richard-Cao** [comment]
当天日志拷贝副本的原因是，上传当天的日志不影响日志本身文件的完整性，如果当天日志上传成功，在回调里删除copy的文件就可以，不需要删除日志文件本身，这样不会影响日志写入

**Comment by hookbin** [comment]
需要解决增量日志上传问题

**Comment by gonganruyi** [comment]
现在的策略好像是不支持增量上传哇？？ 每次上传都是全量的？？ 这个跟我主动出发日志上传没啥区别哇？

**Comment by Richard-Cao** [comment]
> 现在的策略好像是不支持增量上传哇？？ 每次上传都是全量的？？ 这个跟我主动出发日志上传没啥区别哇？

可以后端做个判断，拦截掉一部分上传，比如说一段时间内，日志内容不会差多少，可以复用一下之前传过的
