### ISSUE TITLE
建议 增加 interceptor 的概念

### ISSUE THREAD

**Issue by lixi0912** [Meituan-Dianping/Logan#41]
建议增加 interceptor 的概念，用于对数据的处理，如加密、格式化( json、protobuf )、debug 模式下 logcat 输出，如 OkHttp 的 Interceptor

**Comment by Richard-Cao** [comment]
主要是很多都在C层，没专门传递log，debug模式下的logcat是有一些

**Comment by lixi0912** [comment]
可以考虑先在 JAVA 层增加，后续看是否需要迭代到 C 层

**Comment by lixi0912** [comment]
是的，希望调试时，能在 logocat 直观看到明文的日志内容，在 Logan 设置 debug 模式时，发现只是输出一些 Logan 的操作日志，并非自己写入的内容。 如果要查看还需要将该日志导出或者其他途径去读取~ 总觉得在测试过程中并不是很便利（不禁怀念 OkHttp 的 Interceptor ）。

**Comment by Richard-Cao** [comment]
Logan不是用来代替Log打日志用的，而是用来存储关键日志，进行个案分析的

**Comment by lixi0912** [comment]
通过拦截器对数据处理，实际操作一样可以放在 C 层，这并不影响拆包。

在调试过程中，关键日志同样需要在 Logocat 中可以查看，便于调试，于是就不得不多编写一份 Log 输出的代码。
```java
    if (BuildConfig.DEBUG) {
         Log.e(xxx);
    }
    Logan.w(xxx);
```
虽然也可以通过包装一次 Logan 来处理这个问题，不过主要目的并不是说这个功能，而是有了拦截器的概念，可以给 Logan 带来更多的可能性，比如 数据格式（ json、protobuf 或者其他），加密规则自定义，数据范本自定义（WriteAction）
```java
    public class LoganDelegate{
        public static void w(xxxx){
            if (BuildConfig.DEBUG) {
               Log.d(xxxx); 
           }
           Logan.w(xxxx);
        }
    }
```

**Comment by Richard-Cao** [comment]
我明白你的意思，不过在Logan中拦截器能做的确实有限，主要功能都在C，如果在java层只是定义拦截器配置传到C再去处理，就会徒增复杂度了。就比如你说要更改加密规则的前提是，C层要有实现才可以。

**Comment by lixi0912** [comment]
如果不放弃性能就会提升复杂度，个人觉得这块性能的影响应该可以忽略？

```java
    Java -> Java -> C 加密 -> Java -> C 擦写
    Java -> Java -> Java 加密 -> Java -> C 擦写
```

**Comment by Richard-Cao** [comment]
这块我们再考虑下吧
