### ISSUE TITLE
Logan是不更新了吗？

### ISSUE THREAD

**Issue by linhui9010** [Meituan-Dianping/Logan#413]
感觉这个项目很久都没有更新了，还有组员在安排后续的迭代吗？不会之前的项目组成员都离职了吧。

**Comment by Richard-Cao** [comment]
> 感觉这个项目很久都没有更新了，还有组员在安排后续的迭代吗？不会之前的项目组成员都离职了吧。

之前的都离职了，不过现在还有新的同学接手，确实好久没更新了

**Comment by tony-xian-2017** [comment]
能不能开放更多的功能给大家，目前有项目需求在接入这个框架，遇到很多问题，也搜不出来什么，感觉资料很少。

**Comment by tony-xian-2017** [comment]
> 感觉这个项目很久都没有更新了，还有组员在安排后续的迭代吗？不会之前的项目组成员都离职了吧。

你是不是也在接入Logan框架？

**Comment by Richard-Cao** [comment]
> 能不能开放更多的功能给大家，目前有项目需求在接入这个框架，遇到很多问题，也搜不出来什么，感觉资料很少。

什么问题呢？要不要拉你进微信群

**Comment by chyaohui** [comment]
> > 能不能开放更多的功能给大家，目前有项目需求在接入这个框架，遇到很多问题，也搜不出来什么，感觉资料很少。
> 
> 什么问题呢？要不要拉你进微信群

请问微信群怎么进

**Comment by tony-xian-2017** [comment]
> > 能不能开放更多的功能给大家，目前有项目需求在接入这个框架，遇到很多问题，也搜不出来什么，感觉资料很少。
> 
> 什么问题呢？要不要拉你进微信群

微信群怎么进啊。

**Comment by Richard-Cao** [comment]
> > > 能不能开放更多的功能给大家，目前有项目需求在接入这个框架，遇到很多问题，也搜不出来什么，感觉资料很少。
> > 
> > 
> > 什么问题呢？要不要拉你进微信群
> 
> 微信群怎么进啊。

你加我微信，或者你留个微信我加你也可

**Comment by tony-xian-2017** [comment]
> > > > > 能不能开放更多的功能给大家，目前有项目需求在接入这个框架，遇到很多问题，也搜不出来什么，感觉资料很少。
> > > > 
> > > > 
> > > > 什么问题呢？要不要拉你进微信群
> > > 
> > > 
> > > 微信群怎么进啊。
> > 
> > 
> > 你加我微信，或者你留个微信我加你也可
> 
> 我微信13049866146

我加你微信了，你没有同意。

**Comment by Richard-Cao** [comment]
> 

加你了
