### ISSUE TITLE
日志大小的限制

### ISSUE THREAD

**Issue by tony-xian-2017** [Meituan-Dianping/Logan#417]
我设置了最大文件为10M，setMaxFile(10)。为什么后端收到的日志可以达到13M。

**Comment by Richard-Cao** [comment]
你说后端的日志13M是解压解密之前的源文件吗？或者你手机里是可以看文件大小的

**Comment by tony-xian-2017** [comment]
> 你说后端的日志13M是解压解密之前的源文件吗？或者你手机里是可以看文件大小的

是我在后端网页下载日志文件，那个文件的大小。手机里看到的永远是512，不知道其余的文件在哪

**Comment by Richard-Cao** [comment]
> 

你能下载的已经是解压解密的了，手机里的文件怎么看文档里有方法的

**Comment by GitZhouQi** [comment]
手机里的文档拿出来怎么解析，没看到这个相关的文档。 @Richard-Cao

**Comment by Richard-Cao** [comment]
> 手机里的文档拿出来怎么解析，没看到这个相关的文档。 @Richard-Cao

手机里是加密压缩后的，要上传到后端解析
