### ISSUE TITLE
解析出来c字段里的内容都是空的

### ISSUE THREAD

**Issue by wangdeyi** [Meituan-Dianping/Logan#42]
解析出来c字段里的内容都是空的：
{"c":"{}","f":2,"l":1544095100003,"n":"NioProcessor-1","i":1641,"m":false}
{"c":"{}","f":2,"l":1544095100954,"n":"NioProcessor-2","i":1642,"m":false}
{"c":"{}","f":2,"l":1544095100963,"n":"NioProcessor-2","i":1642,"m":false}
{"c":"{}","f":2,"l":1544095671567,"n":"NioProcessor-3","i":1643,"m":false}
{"c":"{}","f":2,"l":1544095671571,"n":"NioProcessor-3","i":1643,"m":false}
{"c":"{}","f":2,"l":1544095701645,"n":"NioProcessor-3","i":1643,"m":false}
{"c":"{}","f":2,"l":1544095731716,"n":"NioProcessor-3","i":1643,"m":false}
{"c":"{}","f":2,"l":1544095761790,"n":"NioProcessor-3","i":1643,"m":false}
{"c":"{}","f":2,"l":1544095791866,"n":"NioProcessor-3","i":1643,"m":false}
{"c":"{}","f":2,"l":1544095821942,"n":"NioProcessor-3","i":1643,"m":false}

**Comment by Richard-Cao** [comment]
是怎么写入、上传日志的呢？

**Comment by wangdeyi** [comment]
> 是怎么写入、上传日志的呢？

已解决，上传的日志有问题
