### ISSUE TITLE
微信群怎么进啊。

### ISSUE THREAD

**Issue by tony-xian-2017** [Meituan-Dianping/Logan#421]
我的微信13049866146
能不能把我拉进微信群啊，目前我在接入这个框架。

**Comment by Richard-Cao** [comment]
好的，加你了

**Comment by GitZhouQi** [comment]
也拉我进群呗，Revival_q

**Comment by GitZhouQi** [comment]
也拉我进群呗，微信Revival_q @Richard-Cao

**Comment by Deja-vuuu** [comment]
> 好的，加你了

拉一下 谢谢  Deja-Vuuuuuuu

**Comment by songhongkang** [comment]
17512098093

**Comment by Deja-vuuu** [comment]
> 17512098093

我拉你吧

**Comment by cxMax** [comment]
> > 17512098093
> 
> 我拉你吧

求拉，caixi169，
最近在调研android日志方案，想了解更多，谢谢

**Comment by tianjianshi1989** [comment]
麻烦也拉我下 13776603273
公司刚接入logan框架遇到了一些问题 @Richard-Cao

**Comment by Chuckkk** [comment]
麻烦拉一下我，感谢！vx：18589241848

**Comment by wuyutong** [comment]
麻烦也拉一下我，谢谢~ vx:13530502167

**Comment by gxh-apologize** [comment]
求拉，谢谢～～～ vx:  gxh_apologize

**Comment by WeMadeCode** [comment]
大佬 帮忙拉取群 vx：469478583

**Comment by Richard-Cao** [comment]
要进群的加下我微信吧

**Comment by yemh111** [comment]
> 

麻烦拉下yemh111
