### ISSUE TITLE
SendLogDefaultRunnable中上报时抛异常SocketException Connection reset

### ISSUE THREAD

**Issue by Chuckkk** [Meituan-Dianping/Logan#438]
我这边有个Android在上报日志时的报错问题，想请教一下。

上报过程中，在 SendLogDefaultRunnable 类的 doPostRequest 方法中，HttpURLConnection 变量的 getResponseCode 方法抛出 IOException，SocketException Connection reset。

`private void doPostRequest(String url, InputStream inputData, Map<String, String> headerMap) {
        
//...

        try {

            c = (HttpURLConnection) u.openConnection();

            //...

            statusCode = c.getResponseCode(); //源码中这句抛异常了

            //...

        } catch (ProtocolException e) {

            e.printStackTrace();

        } catch (MalformedURLException e) {

            e.printStackTrace();

        } catch (IOException e) {

            e.printStackTrace();

        } catch (Exception e) {

            e.printStackTrace();

        } finally {

           //...

        }

       //...

    }`

![image](https://user-images.githubusercontent.com/5139703/184598197-8fa695e0-7617-40bb-aac7-3693cf40ceb9.png)

因为我自测过程中遇见挺频繁吧，某一台机型上比较常见，我发现这种情况下重复调用上报接口都会失败，一般清空文件存储后才能正常上报。
想问问这个发生的原因是什么，我可以怎么做去降低发生的概率。

**Comment by Richard-Cao** [comment]
default runnable只是一种默认实现，归根结底和你上传到什么url有关，你也可以不用这个实现，自己实现网络上传部分
