### ISSUE TITLE
移动端安卓如何自行解析本地文件？

### ISSUE THREAD

**Issue by qtaotao** [Meituan-Dianping/Logan#439]
请问，移动端怎么能自己解析log文件，是否可以不加密存储？

**Comment by wangyanxi2019** [comment]
+1，这个日志怎么看啊ios

**Comment by Richard-Cao** [comment]
不能本地解析，要上传到server端，本地没有设置解析模块

**Comment by wangyanxi2019** [comment]
@Richard-Cao Server端是用nodejs部署的，我们后端是goland，请问有goland的解码类吗？如果没有，能否提供下解码思路

**Comment by Richard-Cao** [comment]
> 

nodejs和java的解析是有的，也是开源的，参考项目，golang的没写，可以自己参照实现一个
