### ISSUE TITLE
关于日志增量上传的问题？

### ISSUE THREAD

**Issue by lakeui** [Meituan-Dianping/Logan#45]
在接入这个日志系统的过程遇到一个不合理逻辑，我想确认官方的对这个问题的看法？
场景：
12:00  开始记录日志，
13:00 时上传日志文件，
14:00 时上传日志文体

可目前遇到的问题是，为什么14:00上传的日志文件还要包括，12:00 ，13:00 这段时间产生的日志，从逻辑上不合理，我想请问是：程序代码的问题，还是什么问题？

没有增量上传的功能吗？还是增量上传需要自己去处理？

**Comment by Richard-Cao** [comment]
确实没做增量上传。美团内部是由后端做上传Task关联的，并不是每次都发起日志上传

**Comment by lakeui** [comment]
> 后端做上传Task关联的？
能否详细一点？因为目前有一个隐患问题：如果日志文件内容过多，10分钟内就超过10M，如果这样下来，那基本上10分钟上传10M，这样带宽流量不会大量占用和浪费，因为这10M包含了大量的重复日志？

**Comment by Richard-Cao** [comment]
我的天，你们的日志这么多吗……美团使用下来一天的日志都到不了10m
后端做Task关联是这样的：第一次上传日志，记为Task 1，这时候再次触发上传，客户端不再上报，而是和后端约定接口，传给后端Task 1的id，后端关联上报过的Task 1对应的日志，如果日志内容不够，需要上传，就在前端点击强制上传，再次下发信令，客户端进行上报。这样可以有效的减少日志上报次数。

**Comment by robinvanyang** [comment]
@lakeui 短时间生成如此大量的日志的话，你是在pc软件上使用logan库么，一般来讲，移动平台很少有这种情况

**Comment by robinvanyang** [comment]
@lakeui 如果是这样的话，单客户端每年将近500G压缩过的日志，logan的压缩率在12%左右，解压之后大概4T左右的日志，我感觉是不是在存储之前对日志进行一下过滤

**Comment by Richard-Cao** [comment]
@lakeui 确实有问题，你们这个打的太多了……

**Comment by Ericfengshi** [comment]
> 我的天，你们的日志这么多吗……美团使用下来一天的日志都到不了10m
> 后端做Task关联是这样的：第一次上传日志，记为Task 1，这时候再次触发上传，客户端不再上报，而是和后端约定接口，传给后端Task 1的id，后端关联上报过的Task 1对应的日志，如果日志内容不够，需要上传，就在前端点击强制上传，再次下发信令，客户端进行上报。这样可以有效的减少日志上报次数。

这种方式只是减少上报次数，并不能避免浪费。不同优先级的日志类型如何按需上报，如 crash日志需立即上报，监控日志（如性能监控数据等）可以定时上报，不增量上报，是否会造成流量浪费？能否考虑上报成功后将其转移到其它文件夹(backup)备份

**Comment by Richard-Cao** [comment]
@Ericfengshi Logan的使用场景是集中日志上报进行个案分析，并不用于取代原有的实时与非实时日志上报系统。

**Comment by Ericfengshi** [comment]
@Richard-Cao 看你们架构设计图 CAT Log，Crash Log，底层都接入了 Logan。
你们 Crash 时如何处理的？Crash 日志走实时上报系统，然后再 Logan 上存档，这样的话 Crash 数据会存入多个日志系统里？

**Comment by Richard-Cao** [comment]
2个系统，一个在crash系统，一个在Logan系统。正常查crash都是在crash系统里，当进行个案日志分析的时候，去Logan系统统一看日志。

**Comment by Ericfengshi** [comment]
感谢解答
