### ISSUE TITLE
关于SDK更新

### ISSUE THREAD

**Issue by Unique0071** [Meituan-Dianping/Logan#456]
安卓SDK已经有两年没有更新了，有考虑更新的计划吗？
不更新不敢用😂

**Comment by Richard-Cao** [comment]
主要是第一波小队员都不在美团了，第二波小队员还没update上来，看下他们最近新发的文章：https://tech.meituan.com/2022/11/03/logan-real-time-log.html

**Comment by Unique0071** [comment]
好嘞，期望你们的好消息，感谢付出。
