### ISSUE TITLE
正在打印日志时，手动杀死进程，导致日志文件不完全

### ISSUE THREAD

**Issue by robinvanyang** [Meituan-Dianping/Logan#46]
hi, @Richard-Cao，我现在在安卓下面做测试，开子线程，循环打印日志10000次，每次间隔1毫秒，在循环过程中手动杀死进程，这种情况下生成的文件最后一条日志是不完整的，如图:
<img width="1126" alt="2018-12-07 2 19 15" src="https://user-images.githubusercontent.com/10295652/49631129-cf1b2300-fa2b-11e8-9337-94d8c81acfb1.png">

我觉得这种情况会时有发生，惯用安卓的用户，很多都会通过清理进程来让手机跑的快一点

**Comment by Richard-Cao** [comment]
我们的解析是尽可能多的解析，如果出现日志不全的情况，我们会解析部分

**Comment by robinvanyang** [comment]
嗯，如果是在策略上选择了最大化输出，我觉得是可接受的， 感谢贡献，我马上关闭这条issue
