### ISSUE TITLE
与RN依赖库Flipper-Folly 的冲突

### ISSUE THREAD

**Issue by HeXiuLian** [Meituan-Dianping/Logan#462]
在1.2.7版本中的construct_data.c 文件中的第26行包含stdlib.h 使用了 #include "stdlib.h"  双引号，这这种方式导致stdlib.h  链接 到 Flipper-Folly 的文件 Stdlib.h ，并显示编译Stdlib.h 19行 #include <cstdlib> not found;

解决方法：

将construct_data.c 文件中的第26行   #include "stdlib.h"   改成  #include <stdlib.h"> 使用引用系统库优先的 <> 符号。否则编译时将优先搜索项目中的文件。希望能够更新修复此问题。

**Comment by Richard-Cao** [comment]
pr一个如何
