### ISSUE TITLE
Android日志解密失败Not in GZIP format

### ISSUE THREAD

**Issue by Birds-33** [Meituan-Dianping/Logan#465]
由于服务端没有接入，只写了了一个接收日志文件的接口。然后参照server的demo写了解密逻辑。但是一个日志都解密不出，报错： Not in GZIP format。看到历史提问也有人遇到这种情况，但是也没有解决。另外，客户端初始化的时候code为-1020之类。这是正常的吗？但是日志文件都有，时间戳命名的二进制文件。求大佬告知哪里出了问题？ 如果不想要加密解密。该如何实现？

**Comment by Richard-Cao** [comment]
你先试下server端能不能解，如果能，那就是你的实现哪里有问题。初始化code的含义在代码里是有注释的可以看下。日志加密是默认实现的。

**Comment by Birds-33** [comment]
> 你先试下server端能不能解，如果能，那就是你的实现哪里有问题。初始化code的含义在代码里是有注释的可以看下。日志加密是默认实现的。

看了code对应的状态都是成功，server端试了也报这个错（server是只接入写了解密的逻辑）。看之前您有回答说日志要flush()也试了，但目前还没有日志成功解密过... 所以目前的想法是如果实在无法解决，是否可以通过改源码不加密？此外，我看到之前您回答说有微信群，能否拉我进群帮助答疑?万分感谢！我的微信:Birds-33

**Comment by Richard-Cao** [comment]
> > 你先试下server端能不能解，如果能，那就是你的实现哪里有问题。初始化code的含义在代码里是有注释的可以看下。日志加密是默认实现的。
> 
> 看了code对应的状态都是成功，server端试了也报这个错（server是只接入写了解密的逻辑）。看之前您有回答说日志要flush()也试了，但目前还没有日志成功解密过... 所以目前的想法是如果实在无法解决，是否可以通过改源码不加密？此外，我看到之前您回答说有微信群，能否拉我进群帮助答疑?万分感谢！我的微信:Birds-33

好的。你先试下demo能不能成功，微信我加你了

**Comment by santiagoseek** [comment]
Android 上传的日志 Not in GZIP format的报错， 主要是 密钥的问题。 密钥必须是uft的字符串，必须16位。 Android是把传的二进制数据转成string，jni层把 string 在转成 char*
Android使用随机的二进制数据加密就有问题。


![Image](https://github.com/user-attachments/assets/d6b98926-e0ee-4f7d-8102-bd1ca0a1fb81)
