### ISSUE TITLE
动态日志系统Holmes感兴趣

### ISSUE THREAD

**Issue by lxz2014** [Meituan-Dianping/Logan#47]
什么时候这个动态日志开源就好了，这个很感兴趣

**Comment by lxz2014** [comment]
你们的Holmes日志是不是每个类方法都插桩了，如果每个类方法都插桩，是通过什么方法自动插入进去，免去了人工大量插桩的

**Comment by Richard-Cao** [comment]
这个要问问外卖的同事了……

**Comment by lxz2014** [comment]
> 这个要问问外卖的同事了……

请教个问题，从来没有想过日志可以分这么多类，这个也给我打开一个思路，大开眼界，你们日志一般都分了那些类型？还有就是你们网络日志一般记录啥，如果是记录当前网络质量状况，你们是怎么辨别的？

**Comment by Richard-Cao** [comment]
日志分类有十几种吧，比如网络日志、代码日志、crash日志、行为日志等等。
网络日志一般是记录端到端请求的，比如响应时间、包体大小、请求头等等。
网络质量有专门的质量检测工具判断。
