### ISSUE TITLE
日志上传逻辑问题

### ISSUE THREAD

**Issue by zhangqilu** [Meituan-Dianping/Logan#474]
1.怎么辨别哪些日志已经上传（例如昨天的日志）
2.现在有自动上传日志的策略吗
3.我想传昨天的日志怎么实现

**Comment by zhangqilu** [comment]
帮忙加一下 微信交流群谢谢：zhangqiluGrubby

**Comment by Richard-Cao** [comment]
1.  这个在后台辨别
2.  没有
3.  上传的api里面支持传日期

**Comment by zhangqilu** [comment]
解密现在是在服务端做的吗？

**Comment by Richard-Cao** [comment]
> 解密现在是在服务端做的吗？

是的

**Comment by woaiyouxi0803** [comment]
https://github.com/Meituan-Dianping/Logan/issues/475#issue-1686464642
