### ISSUE TITLE
remain_data数据被丢弃

### ISSUE THREAD

**Issue by stone-4827321** [Meituan-Dianping/Logan#478]
各位开发同学好，我有一个问题想请教下，我注意到如果每次初始化之后执行read_mmap_data_clogan()方法时，即将上次mmap缓存的数据写入文件，此时是否存在上次remain_data的数据未写入以及写入内容未添加结束标记的问题

**Comment by wsxyeah** [comment]
remain_data 是放在内存中的，进程退出是可能丢失的。不过实际测试丢失的一般是 gzip 的尾部，很少出现日志内容丢失。

**Comment by stone-4827321** [comment]
谢谢您的解答，因为日志是按16字节为单位进行分割的吧，所以我测试时，如果是“123456789013456”写入mmap然后退出，下次写入时文件后，读取出来实际只有“12345”。

**Comment by wsxyeah** [comment]
有完整测试代码吗

**Comment by stone-4827321** [comment]
> 请问有什么方式可以发整个项目工程请您查看下

**Comment by wsxyeah** [comment]
缺少 gzip 尾部信息会导致解压报错，目前 Java 的解析代码做了兼容，你可以试一下用 Java 解析是否还会丢失

`Logan/Server/src/main/java/com/meituan/logan/web/parser/LoganProtocol.java`
