### ISSUE TITLE
删除当天日志文件后，再次写入日志不能创建当天日志

### ISSUE THREAD

**Issue by huayingxiong** [Meituan-Dianping/Logan#479]
为了避免日志内容重复上传，我在上传成功后删除了日志，但是再次写入的时候不能新建当天日志，请问该怎么处理

**Comment by huayingxiong** [comment]
求进微信群

**Comment by Richard-Cao** [comment]
当天的不要删

**Comment by huayingxiong** [comment]
> 

请问，如果当天的文件大小超过设定值了，是不是只能删除再重新创建文件再写日志了

**Comment by huayingxiong** [comment]
> 当天的不要删

请问，如果当天的文件大小超过设定值了，是不是只能删除再重新创建文件再写日志了

**Comment by Richard-Cao** [comment]
> > 当天的不要删
> 
> 请问，如果当天的文件大小超过设定值了，是不是只能删除再重新创建文件再写日志了？或者有其他的解决方案么？

是的

**Comment by huayingxiong** [comment]
> > > 当天的不要删
> > 
> > 
> > 请问，如果当天的文件大小超过设定值了，是不是只能删除再重新创建文件再写日志了？或者有其他的解决方案么？
> 
> 是的

求进微信群，chengzhaohua123
