### ISSUE TITLE
删除指定文件的接口

### ISSUE THREAD

**Issue by Rannie** [Meituan-Dianping/Logan#48]
看了下 Logan.h 的接口，发现没有删除单一文件的接口，虽然也可以找到指定文件删除，还是想了解下是出于什么原因没有粒度更细的删除接口设计

**Comment by Richard-Cao** [comment]
没遇到比较强烈要求删除指定文件的需求

**Comment by Rannie** [comment]
> 没遇到比较强烈要求删除指定文件的需求

比如上传完一个就删除这个文件呢~

**Comment by Richard-Cao** [comment]
这个要看具体的场景。如果是当天日志上传，会创建一个copy，上传完直接删除。如果是不是当天日志，就要看各自业务怎么处理了。

**Comment by Rannie** [comment]
OK 了解了
