### ISSUE TITLE
iOS集成报错

### ISSUE THREAD

**Issue by Chance-Cheng** [Meituan-Dianping/Logan#480]
新建的项目没有采用pod方式集成，clogan.xcodeproj直接拖进项目，会报错，如下
![image](https://github.com/Meituan-Dianping/Logan/assets/12249051/367b1089-68bc-4fac-ab2c-e51746523ed7)
工程目录如下：
![image](https://github.com/Meituan-Dianping/Logan/assets/12249051/b846490d-5387-4f78-941d-4033716c26b0)
header search  path如下：
![image](https://github.com/Meituan-Dianping/Logan/assets/12249051/3a319920-3445-4876-a22b-d553b951e8f3)

**Comment by Richard-Cao** [comment]
直接用pod不是更简单

**Comment by huayingxiong** [comment]
> 

因为需要修改一些Logan源码，所以没用pod
