### ISSUE TITLE
web端的server有身份验证的功能吗？

### ISSUE THREAD

**Issue by zoooooway** [Meituan-Dianping/Logan#484]
看了一下web端的server代码，貌似没有鉴权之类的处理。是不是通过网页源代码就能知道server端的api地址，任何人都能进行访问呢？

**Comment by wsxyeah** [comment]
日志上报跟一些打点上报类似，是不需要登录的

**Comment by Richard-Cao** [comment]
私有化部署就好了

**Comment by zoooooway** [comment]
> 私有化部署就好了

@Richard-Cao  抱歉，我不太理解你说的私有化部署。假设我要在一个面向互联网用户的网站上启用Logan来收集日志，那么通过Logan发送的请求就能找到server的地址，那么无论server怎么部署应该都没办法隐藏自己，任何人也就都可以访问吧。如果我的理解有误的话麻烦你指正。

**Comment by weloe** [comment]
> > 私有化部署就好了
> 
> @Richard-Cao 抱歉，我不太理解你说的私有化部署。假设我要在一个面向互联网用户的网站上启用Logan来收集日志，那么通过Logan发送的请求就能找到server的地址，那么无论server怎么部署应该都没办法隐藏自己，任何人也就都可以访问吧。如果我的理解有误的话麻烦你指正。

例如防火墙限定访问ip

**Comment by Richard-Cao** [comment]
> > 私有化部署就好了
> 
> @Richard-Cao 抱歉，我不太理解你说的私有化部署。假设我要在一个面向互联网用户的网站上启用Logan来收集日志，那么通过Logan发送的请求就能找到server的地址，那么无论server怎么部署应该都没办法隐藏自己，任何人也就都可以访问吧。如果我的理解有误的话麻烦你指正。

内网部署，这个没有对外使用的场景吧，不是公网部署
