### ISSUE TITLE
写日志崩溃

### ISSUE THREAD

**Issue by happy201993** [Meituan-Dianping/Logan#488]
![image](https://github.com/Meituan-Dianping/Logan/assets/10241217/dbfc0a75-2cec-4da8-8f57-f50430b4d6e8)

**Comment by happy201993** [comment]
版本使用的是1.2.8，iOS线上环境出现

**Comment by Richard-Cao** [comment]
本地能复现吗

**Comment by happy201993** [comment]
您好，我已收到您的邮件，会尽快给您回复。

**Comment by happy201993** [comment]
复现不了，线上崩溃很多 灰度第一天上万个

**Comment by happy201993** [comment]
![image](https://github.com/Meituan-Dianping/Logan/assets/10241217/7ec582be-e58d-45cf-8829-6d0888a1f458)
还有一个

**Comment by Richard-Cao** [comment]
@wsxyeah 看看呢

**Comment by wsxyeah** [comment]
看起来是内存访问问题，能提供更多信息吗，比如寄存器信息之类的

**Comment by happy201993** [comment]
没有了，我目前也只有这个堆栈。另外看崩溃聚合信息，所有崩溃都是进入后台之后发生的，在前台没有问题

**Comment by Richard-Cao** [comment]
> 没有了，我目前也只有这个堆栈。另外看崩溃聚合信息，所有崩溃都是进入后台之后发生的，在前台没有问题

进入后台flush了？

**Comment by happy201993** [comment]
> > 没有了，我目前也只有这个堆栈。另外看崩溃聚合信息，所有崩溃都是进入后台之后发生的，在前台没有问题
> 
> 进入后台flush了？

没有吧，看堆栈是在后台的时候，写日志导致的

**Comment by Richard-Cao** [comment]
> > > 没有了，我目前也只有这个堆栈。另外看崩溃聚合信息，所有崩溃都是进入后台之后发生的，在前台没有问题
> > 
> > 
> > 进入后台flush了？
> 
> 没有吧，看堆栈是在后台的时候，写日志导致的

你那边退到后台以后掉flush了吗

**Comment by happy201993** [comment]
> > > > 没有了，我目前也只有这个堆栈。另外看崩溃聚合信息，所有崩溃都是进入后台之后发生的，在前台没有问题
> > > 
> > > 
> > > 进入后台flush了？
> > 
> > 
> > 没有吧，看堆栈是在后台的时候，写日志导致的
> 
> 你那边退到后台以后掉flush了吗

我没主动掉flush，我看Logan.m里面有这个操作。从日志上看flush应该是走完了，有的是退到后台后好久才崩的

**Comment by happy201993** [comment]
这个库应该用的人也很多，但是似乎只有我遇到了这个问题，不知道是不是使用不对导致的问题，帮忙检查下。
初始化：
![image](https://github.com/Meituan-Dianping/Logan/assets/10241217/e6cb3925-aee0-40ab-a577-050601f027d5)

写日志
![image](https://github.com/Meituan-Dianping/Logan/assets/10241217/de71369e-5258-4cd1-b25c-47f34cc6646b)

@wsxyeah

**Comment by happy201993** [comment]
@wsxyeah 我看到了你的修改，但是这个崩溃是在日志加密阶段，还没有到mmap的时候把？

**Comment by happy201993** [comment]
最新代码打个tag把 @Richard-Cao @wsxyeah

**Comment by wsxyeah** [comment]
> 最新代码打个tag把 @Richard-Cao @wsxyeah

DONE

**Comment by Chance-Cheng** [comment]
请问这个崩溃修复了么？目前还有出现么？

**Comment by happy201993** [comment]
您好，我已收到您的邮件，会尽快给您回复。

**Comment by Richard-Cao** [comment]
> 请问这个崩溃修复了么？目前还有出现么？

更新一下版本
