### ISSUE TITLE
日志如何手动解析？

### ISSUE THREAD

**Issue by zhanglufei** [Meituan-Dianping/Logan#52]
必须后台运行server.js一直跑？

**Comment by Richard-Cao** [comment]
不是，你用java的parse也行，或者你根据server.js里的代码写任意语言的解密解压都可以，server.js只是一个Demo

**Comment by lewic1987** [comment]
@Richard-Cao server.js在哪啊

**Comment by Richard-Cao** [comment]
> @Richard-Cao server.js在哪啊

https://github.com/Meituan-Dianping/Logan/blob/master/Example/Logan-NodeServer/app.ts
应该是这个
