### ISSUE TITLE
Logan日志文件最大限制为10M，遇到大于10M的情况

### ISSUE THREAD

**Issue by bay2** [Meituan-Dianping/Logan#53]
我看目前 Logan 是采用丢掉追加的日志

是否可以考虑支持下面三种策略，然后提供配置项由使用则选择呢？
- 丢掉追加日志
- 丢掉前面日志
- 分片处理

**Comment by Richard-Cao** [comment]
分片也得有个上限，无非就是丢掉追加还是丢掉前面的问题了。
这块儿我们考虑一下
