### ISSUE TITLE
日志在java如何解密

### ISSUE THREAD

**Issue by hellcan** [Meituan-Dianping/Logan#54]
是否需要对已加密的日志进行额外操作 再使用cipher解密

`
    const contentLen = (((buf.readUInt8(skips) & 0xFF) << 24) |
        ((buf.readUInt8(skips + 1) & 0xFF) << 16) |
        ((buf.readUInt8(skips + 2) & 0xFF) << 8) |
        (buf.readUInt8(skips + 3) & 0xFF));
      skips += 4;
      if (skips + contentLen > buf.length) {
        skips -= 4;
        decodeLog(buf, skips);
        return;
      }
      const content = buf.slice(skips, skips + contentLen);
      skips += contentLen;
`

**Comment by Richard-Cao** [comment]
parser是给后端用的，不是移动端用的

**Comment by 597579501** [comment]
> parser是给后端用的，不是移动端用的

说的跟不知道一样。就是为了本地解密测试一下。你那个server很多人部署不起来。怎么搞

**Comment by Richard-Cao** [comment]
> > parser是给后端用的，不是移动端用的
> 
> 说的跟不知道一样。就是为了本地解密测试一下。你那个server很多人部署不起来。怎么搞

本地测试有node server，npm start一下就好了，只是测试不需要部署整个java server
