### ISSUE TITLE
C层代码格式化日志为Json时，在内容结尾添加"\n"换行符，"\n"字符长度为1，但数据长度为何是增加2？

### ISSUE THREAD

**Issue by hanzhicuilin** [Meituan-Dianping/Logan#58]
在[construct_data.c](https://github.com/Meituan-Dianping/Logan/blob/master/Logan/Clogan/construct_data.c)文件第60行，将构造后的json数据长度增加2，但是只增加了1个换行符，这会导致文本解析时出现null的数据。例如[#19 OS客户端上传到node服务器解析出来的文本包含null(^@)](https://github.com/Meituan-Dianping/Logan/issues/19)

**Comment by Richard-Cao** [comment]
我们看下这个问题

**Comment by baitian0521** [comment]
Json构造数据长度+2的原因是因为C语言中\0结尾才能表示string。所有需要两个byte，一个给\n一个给\0。从而导致了写入时\n后面会多一个\0。也就是你看到的现象。对于java，使用String.trim来消除影响。等下代码修改一下
