### ISSUE TITLE
android：日志上传

### ISSUE THREAD

**Issue by lingyanluoxue** [Meituan-Dianping/Logan#61]
记录日志以后上传，debug显示上传的是一个.copy文件，但是在相应的目录找不到.copy文件

**Comment by Richard-Cao** [comment]
当上传的日志是当日日志，会创建.copy文件，然后会在上传成功之后删除。

**Comment by lingyanluoxue** [comment]
在debug的时候发现确实生成了.copy文件，但是在SendLogRunnable 监听回来还未完成上传.copy文件就被删除，所以我想咨询下.copy文件是在什么时机删除，是怎么评判上传成功呢？

**Comment by Richard-Cao** [comment]
哦不对，是上传之后就删除了，不会管是否成功，我刚又看了一下逻辑，不好意思。。

**Comment by Richard-Cao** [comment]
你遇到的问题是上传文件没有了导致上传失败吗？

**Comment by lingyanluoxue** [comment]
是，文件还没上传.copy文件就已经删除，所以会出现文件找不到。

**Comment by Richard-Cao** [comment]
这块儿逻辑我改一下吧，可能会有隐患，我就不去自动删除了，让开发者自己删除吧，我提供一个方法出来

**Comment by lingyanluoxue** [comment]
好的，非常感谢

**Comment by Richard-Cao** [comment]
我想问下sendLog函数你是怎么实现的？

**Comment by lingyanluoxue** [comment]
String d = dataFormat.format(new Date(System.currentTimeMillis()));
            Logan.s(new String[]{d}, new SendLogRunnable() {
                @Override
                public void sendLog(File logFile) {
                    RequestBody requestBody = RequestBody.
                            create(MediaType.parse("multipart/form-data"), logFile);
                    MultipartBody.Part logFileBody = MultipartBody.Part
                            .createFormData("logFile", logFile.getName(), requestBody);
                    HttpGenerator.loganApi().uploadLogan(params,logFileBody).subscribe(new ReqObserver<BaseModel>() {
                        @Override
                        public void onSuccess(BaseModel resp) {
                            Log.d("logan","success");
                        }

                        @Override
                        public void onFailure(BaseModel resp) {
                            Log.d("logan","Failure");
                        }
                    });
                }
            });

**Comment by lingyanluoxue** [comment]
呃呃，我在使用Logan-Android的时候偶尔也会出现上传不成功的情况

**Comment by lingyanluoxue** [comment]
已经解决

**Comment by Richard-Cao** [comment]
怎么解决的？ @lingyanluoxue

**Comment by lingyanluoxue** [comment]
解决方案还是需要上传成功以后再删除，我看了源码，是发送以后就删除的，发送以后获取到预处理的file，进行网络上传是开启一个子线程，这样的话就会导致出现已经删除，但是还没上传。所以我建议还是应该把删除单独剔出来，让开发者在上传以后自行处理

**Comment by Richard-Cao** [comment]
那你是改了源码还是在外部包装处理的？

**Comment by Richard-Cao** [comment]
外部包装怎么处理的？方便看看代码么

**Comment by lingyanluoxue** [comment]
我理解错了，没有进行外部包装，log.s()会把预处理的file返回，我会重新保存一份.copy文件，上传以后再做处理

**Comment by lingyanluoxue** [comment]
好的，建议对file的删除处理交给开发者进行操作

**Comment by Caij** [comment]
我觉得可以把上传这块逻辑做简单一些，源码中主要是flush和copy两个操作，而且好像这个方法只是获取当前日期的日志文件， 并且源码中还搞了一个ExecutorService,  从性能上我根本不需要源码中这个线程池去做上传。 感觉可以把send操作简化成一个flush操作，ExecutorService也可以去掉， 并回调List<File> 所有文件。关于回调里面的上传提醒开发者必须用异步，避免阻塞写log线程队列。这个回调回来让开发者去copy 和 delete文件，上传的操作写在sample里面开发者应该都可以明白。

**Comment by Richard-Cao** [comment]
这样的话逻辑暴露太多，在使用上就会产生各种意想不到的效果了，这块我最近改一改先

**Comment by Caij** [comment]
因为外部上传文件基本是异步， 有自己配置的线程池复用， 用不上这个线程池，  有点浪费， 而且这个是在实例化LoganThread的时候就创建了，如果你们权衡需要有线程池的话可以在出发上传操作再实例化这个线程池吧。 但是不用这个线程池又可能开发者不用异步，导致写log阻塞。

**Comment by Richard-Cao** [comment]
哦我明白你的意思了，延迟初始化也行，在上传的时候再初始化。

**Comment by Richard-Cao** [comment]
@lingyanluoxue 按照demo的方式，sendLog里是一个同步请求，所以每次都可以获取到结果，删除文件。如果sendLog里执行的是异步方法，就不行了。

**Comment by lingyanluoxue** [comment]
对，是这样的，所以会出现还未上传就已经删除的情况

**Comment by Richard-Cao** [comment]
各位可以看看这个PR #67

**Comment by Richard-Cao** [comment]
Android已更新到1.2.1
