### ISSUE TITLE
日志不写入文件

### ISSUE THREAD

**Issue by skyooo** [Meituan-Dianping/Logan#64]
日志文件到达10M后，后续的日志都不往文件里写了，logan.f() 方法调用了也还是不写，
 int code = clogan_write(flag, log, local_time, thread_name, thread_id,
                    isMain);
这个code 码是 - 4030 ,如果文件大到最大值了，就无法写入了吗？ 如果一天写的日志太多了，就写不进去了.

**Comment by Richard-Cao** [comment]
是的，如果到10M后续就不再写入了。你是在什么场景下打了这么多日志呢？

**Comment by skyooo** [comment]
用户的操作行为。这个估计会很多，也很频繁，按照我们，因为用户使用的频率挺高，10M，或者20M，应该都不够，我们现在的日志记录的一天都超过30M了，如果想记录的更详细点，这个肯定不够。

**Comment by Richard-Cao** [comment]
那你可以通过LoganConfig的setMaxFile方法来设置一个合适的最大文件大小。
