### ISSUE TITLE
log文件无法写入

### ISSUE THREAD

**Issue by CCCCoder** [Meituan-Dianping/Logan#66]
路径写的是demo的路径，manifest有读写权限。我在测试的时候能看到查看到日志信息：
![image](https://user-images.githubusercontent.com/13776721/51957899-721a7700-2488-11e9-9bc9-528515d8f813.png)
但是data/data/packetname/ 下面并没有此文件，上传的时候报错文件不存在，并且库报错：
01-30 12:06:41.370 9292-9477/xxx W/linker: /data/app/xxx-1/lib/arm64/liblogan.so: unused DT entry: type 0x6ffffffe arg 0x2550
01-30 12:06:41.370 9292-9477/xxx W/linker: /data/app/xxx-1/lib/arm64/liblogan.so: unused DT entry: type 0x6fffffff arg 0x1

**Comment by Richard-Cao** [comment]
路径是https://github.com/Meituan-Dianping/Logan/blob/master/Example/Logan-Android/app/src/main/java/test/logan/dianping/com/logan/MainActivity.java#L62 ？

**Comment by CCCCoder** [comment]
@Richard-Cao 是的 
![image](https://user-images.githubusercontent.com/13776721/51963139-84eb7680-249d-11e9-815e-3f44486155f8.png)

**Comment by Richard-Cao** [comment]
这个背景很6啊。
重写几次也写不进去吗？

**Comment by CCCCoder** [comment]
@Richard-Cao 我试了下，貌似都不行啊，这个报错的log（unused DT entry: type 0x6ffffffe arg 0x2550）是什么意思？

**Comment by Richard-Cao** [comment]
这个不是我们代码里打的log……

**Comment by Richard-Cao** [comment]
这问题还有吗 @CCCCoder 稳定复现吗
