### ISSUE TITLE
support print function name, line, file name in log

### ISSUE THREAD

**Issue by piaojin** [Meituan-Dianping/Logan#7]
@jiangteng in server demo the decode  log is: ```  {"c":"clogan header","f":1,"l":1539321701072,"n":"clogan","i":1,"m":true}
�{"c":"1\tclick button 0\t","f":1,"l":1539321701061,"n":"","i":1,"m":true} ```

But it doesn't include function name, line, file name so it's not particularly convenient to find out which function triggered the log.

eg: 
```
//printf("123"),printf("456");
#define TRACE_CMH_1 (printf("%s(%d)-<%s>: ",__FILE__, __LINE__, __FUNCTION__), printf)
 
//printf("%d""%d", 1, 2);
#define TRACE_CMH_2(fmt,...) \
	printf("%s(%d)-<%s>: "##fmt, __FILE__, __LINE__, __FUNCTION__, ##__VA_ARGS__)
```

**Comment by jiangteng** [comment]
Logan log support type, if the log type requires method name, function name can be encapsulated and then write to Logan.Log content belongs to the log input module.
<img width="918" alt="wx20181012-163220 2x" src="https://user-images.githubusercontent.com/7625449/46857839-6ef96d80-ce3c-11e8-87ce-575daa6412f6.png">
