### ISSUE TITLE
加密疑问

### ISSUE THREAD

**Issue by JackyAndroid** [Meituan-Dianping/Logan#71]
已看完提问相关issues

1. 加密算法是AES，但是解密的java文件使用模式为AES/CBC/NoPadding，如果这样不满16字节是如何处理的？
2. 加密算法是否能提供定制？或者加密开关

**Comment by Richard-Cao** [comment]
1.加密的时候不够16字节会自动填充，所以解密的时候用nopadding也能解
2.目前没有提供定制和开关
