### ISSUE TITLE
解密报错，且解出来日志不全

### ISSUE THREAD

**Issue by pxx11111** [Meituan-Dianping/Logan#72]
报错信息：
 java.io.EOFException: Unexpected end of ZLIB input stream                                
     at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)              
     at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)              
     at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:115)                      
     at java.io.FilterInputStream.read(FilterInputStream.java:107)                        
     at com.example.logdemo.LoganParser.parse(LoganParser.java:77)                        
     at com.example.logdemo.MainActivity$1.onClick(MainActivity.java:50)                  
     at android.view.View.performClick(View.java:5647)                                    
     at android.view.View$PerformClick.run(View.java:22465)                               
     at android.os.Handler.handleCallback(Handler.java:754)                               
     at android.os.Handler.dispatchMessage(Handler.java:95)                               
     at android.os.Looper.loop(Looper.java:163)                                           
     at android.app.ActivityThread.main(ActivityThread.java:6388)                         
     at java.lang.reflect.Method.invoke(Native Method)                                    
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:930)   
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)

**Comment by Richard-Cao** [comment]
稳定复现吗？你这是把java解析器直接丢在Android代码里了么……

**Comment by pxx11111** [comment]
是的，有问题吗，不能直接丢？

**Comment by dubiao** [comment]
我也有这个问题。我也是直接丢进去的。解析出来好多没有后半边括号的。

> ed","f":1,"l":1551254557594,"n":"main","i":2,"m":true{"c":"Lagan is init-ed","f":1,"l":1551254557880,"n":"main","i":2,"m":true{"c":"Lagan is init-ed","f":1,"l":1551254803353,"n":"main","i":2,"m":true{"c":"Lagan is init-ed","f":1,"l":1551254803677,"n":"main","i":2,"m":true{"c":"Lagan is init-ed","f":1,"l":1551254910909,"n":"main","i":2,"m":true{"c":"Lagan is init-ed","f":1,"l":1551254911191,"n":"main","i":2,"m":true}{"c":"Lagan is init-ed","f":1,"l":1551255252670,"n":"main","i":2,"m":true


不知道是写入过程的问题还是解密过程的问题。

**Comment by Richard-Cao** [comment]
如果你是直接丢的话可能会遇到日志还没写完你就要解密的情况，那个解析器是给后端用的，因为上传之前会flush一次

**Comment by littlecat1988** [comment]
> 如果你是直接丢的话可能会遇到日志还没写完你就要解密的情况，那个解析器是给后端用的，因为上传之前会flush一次

我这边是日志已经写完上传到后台，但是后端解析也会出现解析截断的问题

**Comment by Richard-Cao** [comment]
> > 如果你是直接丢的话可能会遇到日志还没写完你就要解密的情况，那个解析器是给后端用的，因为上传之前会flush一次
> 
> 我这边是日志已经写完上传到后台，但是后端解析也会出现解析截断的问题

常见吗

**Comment by littlecat1988** [comment]
> > > 如果你是直接丢的话可能会遇到日志还没写完你就要解密的情况，那个解析器是给后端用的，因为上传之前会flush一次
> > 
> > 
> > 我这边是日志已经写完上传到后台，但是后端解析也会出现解析截断的问题
> 
> 常见吗

目前来看，还挺常见的，我们后台一天里已经出现了上百条这样的记录

**Comment by Richard-Cao** [comment]
占比大概多少？

**Comment by littlecat1988** [comment]
> 占比大概多少？

大概在5%左右

**Comment by JackyAndroid** [comment]
我这边也是，经常性丢失，是不是流没关闭导致的？

**Comment by Richard-Cao** [comment]
流没关闭？怎么讲 @JackyAndroid

**Comment by JackyAndroid** [comment]
猜测：
https://stackoverflow.com/questions/24531089/exception-unexpected-end-of-zlib-input-stream

**Comment by Richard-Cao** [comment]
流没关闭可能是调用parse的时候in和out的流自己没关，解析工具内部的流是关闭了的，你们有demo可以复现一下吗？我一直复现不出来

**Comment by Richard-Cao** [comment]
我更新了android的demo。还是复现不出来。

**Comment by Richard-Cao** [comment]
建议在app切换到后台的时候，Android调用Logan.f()，iOS也有类似的方法。如果还有问题，会reopen这个issue。

**Comment by DDstrongman** [comment]
iOS环境下，每个logan日志记录处均调用loganflush,上传之前也调用loganflush，仍有日志解析报错问题。大概3%左右

**Comment by DDstrongman** [comment]
start decode log file
decrypt complete
remove padding complete
decode log file complete
{ Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17) errno: -3, code: 'Z_DATA_ERROR' }

**Comment by hdwmp123** [comment]
测试环境（阿里云）每次必现，本地环境没有问题。
同时会出现只读问题
`@PostMapping("/upload")
    @ResponseBody
    public LoganResponse<String> upload(
            HttpServletRequest request
    ) throws IOException {
        LoganTaskModel model = RequestContextParser.parse(request);
        ResultEnum result = loganLogFileService.write(request.getInputStream(), model.getLogFileName());
        if (ResultEnum.SUCCESS != result) {
            return LoganResponse.exception(result.name());
        }
        long addResult = loganTaskService.insertTask(model);
        // 保存后马上解析
        if (addResult > 0) {
            LoganTaskDTO task = loganTaskService.getDtoByTaskId(addResult);
            if (task != null) {
                loganLogDetailService.tryAnalyze(task);
            }
        }
        //
        return addResult > 0
                ? LoganResponse.success(FileUtil.getDownloadUrl(request, model.getLogFileName()))
                : LoganResponse.exception(ResultEnum.ERROR_DATABASE.name());

    }`

**Comment by Richard-Cao** [comment]
> 测试环境（阿里云）每次必现，本地环境没有问题。
> 同时会出现只读问题
> 
> ```java
> @PostMapping("/upload")
>     @ResponseBody
>     public LoganResponse<String> upload(
>             HttpServletRequest request
>     ) throws IOException {
>         LoganTaskModel model = RequestContextParser.parse(request);
>         ResultEnum result = loganLogFileService.write(request.getInputStream(), model.getLogFileName());
>         if (ResultEnum.SUCCESS != result) {
>             return LoganResponse.exception(result.name());
>         }
>         long addResult = loganTaskService.insertTask(model);
>         // 保存后马上解析
>         if (addResult > 0) {
>             LoganTaskDTO task = loganTaskService.getDtoByTaskId(addResult);
>             if (task != null) {
>                 loganLogDetailService.tryAnalyze(task);
>             }
>         }
>         //
>         return addResult > 0
>                 ? LoganResponse.success(FileUtil.getDownloadUrl(request, model.getLogFileName()))
>                 : LoganResponse.exception(ResultEnum.ERROR_DATABASE.name());
> 
>     }
> ```

客户端后台的时候调flush了吗
