### ISSUE TITLE
关于分片的问题想请教一下

### ISSUE THREAD

**Issue by Nier-halls** [Meituan-Dianping/Logan#76]
想请教一下日志分片是出于什么考虑，是因为zlib压缩大数据会比较占用内存导致短时间的内存峰值吗？

**Comment by baitian0521** [comment]
日志分片考虑原因：上层传递过来的日志大小是不一定的，有可能会很大。这样会导致越过缓存大小。造成缓存越界。所以要对日志分片处理。
压缩占用CPU: 集中压缩会对CPU占用过来。所以采用流式压缩，让CPU更平滑

**Comment by Nier-halls** [comment]
> 日志分片考虑原因：上层传递过来的日志大小是不一定的，有可能会很大。这样会导致越过缓存大小。造成缓存越界。所以要对日志分片处理。
> 压缩占用CPU: 集中压缩会对CPU占用过来。所以采用流式压缩，让CPU更平滑

谢谢解答
