### ISSUE TITLE
关于LoganThread类的一点建议

### ISSUE THREAD

**Issue by Nier-halls** [Meituan-Dianping/Logan#77]
```
action.sendLogRunnable.setCallBackListener(
                new SendLogRunnable.OnSendLogCallBackListener() {
                    @Override
                    public void onCallBack(int statusCode) {
                        synchronized (sendSync) {
                            mSendLogStatusCode = statusCode;
                            if (statusCode == SendLogRunnable.FINISH) {
                                //假设在极端情况下，每次在这里都会有一个新的send请求插入
                                mCacheLogQueue.addAll(mCacheSendQueue);
                                mCacheSendQueue.clear();
                                notifyRun();
                            }
                        }
                    }
                });

```
假设在mCacheLogQueue.addAll(mCacheSendQueue);代码前有异步的send action插入队列，那mCacheSendQueue缓存的send action就有可能一直被排在队列的尾端。
另外每次发送完成需要手动的finish来触发回调，是不是可以考虑设计成AsyncTask源码中的SerialExecutor来顺序执行发送Runnable；
AsyncTask
```
    private static class SerialExecutor implements Executor {
        final ArrayDeque<Runnable> mTasks = new ArrayDeque<Runnable>();
        Runnable mActive;

        public synchronized void execute(final Runnable r) {
            mTasks.offer(new Runnable() {
                public void run() {
                    try {
                        r.run();
                    } finally {
                        scheduleNext();
                    }
                }
            });
            if (mActive == null) {
                scheduleNext();
            }
        }

        protected synchronized void scheduleNext() {
            if ((mActive = mTasks.poll()) != null) {
                THREAD_POOL_EXECUTOR.execute(mActive);
            }
        }
    }
```

**Comment by Richard-Cao** [comment]
手动执行finish是因为在接收action的地方有处理，有个锁

**Comment by Richard-Cao** [comment]
你说的极端情况，mCacheSendQueue缓存的send action不会一直在队列尾，只是没跟上前一波进入发送队列，mCacheSendQueue的作用是当正在发送日志的时候，先把send action缓存一下，等不在发送日志的时候再去统一处理

**Comment by Nier-halls** [comment]
> 你说的极端情况，mCacheSendQueue缓存的send action不会一直在队列尾，只是没跟上前一波进入发送队列，mCacheSendQueue的作用是当正在发送日志的时候，先把send action缓存一下，等不在发送日志的时候再去统一处理
你说的对，是我这边考虑的有问题，新加入的action也会被缓存到mCacheSendQueue，因此不会被插队。

**Comment by Nier-halls** [comment]
> 你说的极端情况，mCacheSendQueue缓存的send action不会一直在队列尾，只是没跟上前一波进入发送队列，mCacheSendQueue的作用是当正在发送日志的时候，先把send action缓存一下，等不在发送日志的时候再去统一处理

你说的对，是我这边考虑的有问题，新加入的action也会被缓存到mCacheSendQueue，因此不会被插队

**Comment by Nier-halls** [comment]
> finish是因为在接收action的地方有处理，有个锁，需要一个callback去执行互斥操作。还有一个意

手动finish并且执行互斥操作的意义就是将缓存mCacheSendQueue中的action重新加入到mCacheLogQueue中重新做分发处理，因此我觉得用那种自动执行任务的类似于SerialExecutor的线程执行器会不会更好，这样就减少了需要外层强制finish的限制，并且发送的action都可以自己来做管理，不需要缓存重新汇入到LoganThread线程的mCacheLogQueue队列中再作分发，而SerialExecutor就能够满足单任务顺序执行，也省去了sendSync锁来控制状态进行互斥操作。而删除文件仍然可以让用户自己来做决定执不执行，属于发送逻辑的一部分（也就是代码中的sendLog），这两步应该互不影响，不知道我理解的有没有问题。

**Comment by Richard-Cao** [comment]
> > finish是因为在接收action的地方有处理，有个锁，需要一个callback去执行互斥操作。还有一个意
> 
> 手动finish并且执行互斥操作的意义就是将缓存mCacheSendQueue中的action重新加入到mCacheLogQueue中重新做分发处理，因此我觉得用那种自动执行任务的类似于SerialExecutor的线程执行器会不会更好，这样就减少了需要外层强制finish的限制，并且发送的action都可以自己来做管理，不需要缓存重新汇入到LoganThread线程的mCacheLogQueue队列中再作分发，而SerialExecutor就能够满足单任务顺序执行，也省去了sendSync锁来控制状态进行互斥操作。而删除文件仍然可以让用户自己来做决定执不执行，属于发送逻辑的一部分（也就是代码中的sendLog），这两步应该互不影响，不知道我理解的有没有问题。

我思考一下

**Comment by Nier-halls** [comment]
还有一个问题
```
    private void deleteExpiredFile(long deleteTime) {
        File dir = new File(mPath);
        if (dir.isDirectory()) {
            String[] files = dir.list();
            if (files != null) {
                for (String item : files) {
                    try {
                        if (TextUtils.isEmpty(item)) {
                            continue;
                        }
                        String[] longStrArray = item.split("\\."); //这里为什么是需要分割文件名字呢？
                        if (longStrArray.length > 0) {  //小于时间就删除
                            long longItem = Long.valueOf(longStrArray[0]);
                            if (longItem <= deleteTime && longStrArray.length == 1) {
                                new File(mPath, item).delete(); //删除文件
                            }
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }
    }
```
这段代码逻辑应该是超过7天的日志文件会被删除，但是这边分割的逻辑不是很明白**String[] longStrArray = item.split("\\.");** 我这边看源码日志文件直接以**时间戳**来命名的

> mido:/storage/emulated/0/Android/data/test.logan.dianping.com.logan/files/logan_v1 # ls -al
> total 16
> drwxrwx--x 2 u0_a101 sdcard_rw 4096 2019-03-05 20:41 .
> drwxrwx--x 3 u0_a101 sdcard_rw 4096 2019-02-27 16:58 ..
> -rw-rw---- 1 u0_a101 sdcard_rw  188 2019-02-27 16:58 1551196800000
> -rw-rw---- 1 u0_a101 sdcard_rw  188 2019-03-01 11:22 1551369600000
> -rw-rw---- 1 u0_a101 sdcard_rw    0 2019-03-05 20:41 1551715200000

上面是我手机中的日志，按照逻辑应该永远不会进入到下面的删除逻辑中，是不是我哪里理解的有问题....求大佬解答一下..thx @Richard-Cao

**Comment by Richard-Cao** [comment]
这个是能进入删除逻辑的，longStrArray.length最起码是个1

**Comment by Richard-Cao** [comment]
我想了一下，顺序执行器有一个问题，那就是上传当天日志的时候，会有临时的.copy后缀的文件，上传完成之后才删除，如果外界不调finish，内部是感知不到什么时候网络请求结束的，顺序执行没问题，但是开发者就不知道什么时候应该删文件了，所以才由外界来决定是否开启下一次上传
