### ISSUE TITLE
日志文件解析

### ISSUE THREAD

**Issue by littlecat1988** [Meituan-Dianping/Logan#78]
日志文件解析偶现截断，想问下有哪些原因可能造成这些问题

**Comment by Nier-halls** [comment]
是本地直接解析日志文件吗？
如果是本地直接解析会不会是有一部分mmap文件中的日志没有被flush到LogFile中。

**Comment by littlecat1988** [comment]
不是本地解析的，是上传到后台以后，后台解析出来有截断的现象

**Comment by Richard-Cao** [comment]
日志残缺是有可能的，比如mmap还没来得及写入的情况应用就G了，有可能造成日志残缺

**Comment by littlecat1988** [comment]
按理说，如果mmap还没来得及写，应该是某条日志缺失，现在是随机从一条记录的中间断掉了，某个string都是不全的，有没有可能是相关buffer满了，导致的缺失

**Comment by Richard-Cao** [comment]
能发下断档日志的前后日志片段吗

**Comment by littlecat1988** [comment]
{"c":"{\"page\":\"HomeFragment\"}","f":1,"l":1549798736626,"n":"main","i":1,"m":true}
{"c":"{\"action\":14,\"page\":\"HomeFragment\"}","f":1,"l":1549798746403,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"ReadWebActivity\"}","f":1,"l":1549798746476,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"HomeFragment\"}","f":1,"l":1549798764322,"n":"main","i":1,"m":true}
{"c":"{\"action\":1,\"attr\":{\"skuId\":0},\"page\":\"HomeFragment\"}","f":1,"l":1549798771282,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"CoursesTaskFragment\"}","f":1,"l":1549798771357,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"CoursesTaskFragment\"}","f":1,"l":1549799714905,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"HomeFragment\"}","f":1,"l":1549799752224,"n":"main","i":1,"m":true}
{"c":"{\"action\":1,\"attr\":{\"skuId\":0},\"page\":\"HomeFragment\"}","f":1,"l":1549799754143,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"CoursesTaskFragment\"}","f":1,"l":1549799754188,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"HomeFragment\"}","f":1,"l":1549799827697,"n":"main","i":1,"m":true}
{"c":"{\"action\":1,\"attr\":{\"skuId\":0},\"page\":\"HomeFragment\"}","f":1,"l":1549799829436,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"CoursesTaskFragment\"}","f":1,"l":1549799829480,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSDetailFragment\"}","f":1,"l":154979983{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":1549799839171,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":1549800193475,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":1549800279463,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":1549800340372,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":1549801595","f":1,"l":15cÜ7kfÇó∂hbò0279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":1549880595","f":1,"l":15cÜ7kfÇó∂hbò0279463,"n":"main","i":1,"m":true}
{"c":"{\"page\":70305bActivity\"}","f":1,"l":154980800340372,"n":"main4:"{\"page\":\"IPSWebActivity\"}","f":1,"l":154713280Activity\"}","f":1,"l":1549800279463,"n":"main"ReadWebA"n"vityvity\"}","f":1,"l":15471353bActivity\"}","f":1,"l":1549800279463,"n":"main","i":1,"m":true}
{"c":"{\"page\":736626Activity\"}","f":1,"l":154980800340372,"n":"main4:"{\"page\":\"IPSWebActivity\"}","f":1,"l":15474640bActivity\"}","f":1,"l":1549800279463,"n":"main"ReadWebA"n"vityvity\"}","f":1,"l":154746476Activity\"}","f":1,"l":1549800279463,"n":"main","i":1,"m":true}
{"c":"{\"page\":76IPSWActivity\"}","f":1,"l":154980800340372,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":15477128WActivity\"}","f":1,"l":1549800279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":154771357Activity\"}","f":1,"l":1549800279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":15971490WebActivity\"}","f":1,"l":15490279463,"n":"main","i":1,"m":true}
{"c":"{\"page\"975SWe4ebActivity\"}","f":1,"l":1549800340372,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":15975414bActivity\"}","f":1,"l":1549800279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":15975418ge\":\"IPSWebActivity\"}","f":0279463,"n":"main","i":1,"m":true}
{"c":"{\"page\"9827980e\":\"IPSWebActivity\"}","f":800340372,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":159829436Activity\"}","f":1,"l":1549800279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":159829480Activity\"}","f":1,"l":1549800279463,"n":"main"IPSDetailSWebActivity\"}","f":1,"l":159830757Activity\"}","f":1,"l":1549800279463,"n":"main"IPSDetailSWebActivity\"}","f":1,"l":8001:7674ebActivity\"}","f":1,"l":15490279463,"n":"main"IPSDetailSWebActivity\"}","f":1,"l":80027916bActivity\"}","f":1,"l":1549800279463,"n":"main"IPSDetailSWebActivity\"}","f":1,"l":80033864bActivity\"}","f":1,"l":1549800279463,"n":"main"IPSDetailSWebActivity\"}","f":1,"l":800391354ebActivity\"}","f":1,"l":15490279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":800392200Activity\"}","f":1,"l":1549800279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":801092121Activity\"}","f":1,"l":1549800279463,"n":"main","i":1,"m":true}
{"c":"{\"page801107404ebActivity\"}","f":1,"l":1549800340372,"n":"main3,,"n":"main","i":1,"m":true}
{"c":"{\"page80111138ge\":\"IPSWebActivity\"}","f":0279463,"n":"main"WatchCont":tA"n"vityvity\"}","f":1,"l":8011114295","f":1,"l":15cÜ7kfÇó∂hbò0279463,"n":"main"WatchCont":t:1,"m":true}
{"c":"{\"page801111477Activity\"}","f":1,"l":1549800279463,"n":"main"WatchCont":t:1,"m":true}
{"c":"{\"page801111481Activity\"}","f":1,"l":1549800279463,"n":"main","i":1,"m":true}
{"c":"{\"page8011151895","f":1,"l":15cÜ7kfÇó∂hbò800340372,"n":"main3,,"n":"main","i":1,"m":true}
{"c":"{\"page801116480e\":\"IPSWebActivity\"}","f":0279463,"n":"main"WatchCont":tA"n"vityvity\"}","f":1,"l":8011165295","f":1,"l":15cÜ7kfÇó∂hbò0279463,"n":"main"WatchCont":t:1,"m":true}
{"c":"{\"page801116550Activity\"}","f":1,"l":1549800279463,"n":"main"WatchCont":t:1,"m":true}
{"c":"{\"page80111655bActivity\"}","f":1,"l":1549800279463,"n":"main","i":1,"m":true}
{"c":"{\"page801122034ebActivity\"}","f":1,"l":1549800340372,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":801124418ebActivity\"}","f":1,"l":15490279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":8011244SWebActivity\"}","f":1,"l":15490279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":80158728WebActivity\"}","f":1,"l":15490279463,"n":"main"IPSDetailSWebActivity\"}","f":1,"l":80159028WActivity\"}","f":1,"l":1549800279463,"n":"main"IPSDetailSWebActivity\"}","f":1,"l":801621206Activity\"}","f":1,"l":1549800279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":801621960e\":\"IPSWebActivity\"}","f":0279463,"n":"main","i":1,"m":true}还有类似这种情况的解析出现了错乱的情况

**Comment by Richard-Cao** [comment]
你已经在线上使用了吗 @littlecat1988

**Comment by jiangteng** [comment]
方便把一个完整解密后的日志文件发一下吗？@littlecat1988

**Comment by littlecat1988** [comment]
> 你已经在线上使用了吗 @littlecat1988

是的，已经是线上数据了

**Comment by littlecat1988** [comment]
{"c":"clogan header","f":1,"l":1549798399724,"n":"clogan","i":1,"m":true}
{"c":"{\"page\":\"WelcomeActivity\"}","f":1,"l":1549798399701,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"HomeFragment\"}","f":1,"l":1549798401978,"n":"main","i":1,"m":true}
{"c":"{\"action\":12,\"page\":\"HomeFragment\"}","f":1,"l":1549798432223,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"HomeFragment\"}","f":1,"l":1549798692965,"n":"main","i":1,"m":true}
{"c":"{\"action\":1,\"attr\":{\"skuId\":0},\"page\":\"HomeFragment\"}","f":1,"l":1549798697999,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"CoursesTaskFragment\"}","f":1,"l":1549798698099,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"HomeFragment\"}","f":1,"l":1549798703053,"n":"main","i":1,"m":true}
{"c":"{\"action\":14,\"page\":\"HomeFragment\"}","f":1,"l":1549798713280,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"ReadWebActivity\"}","f":1,"l":1549798713533,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"HomeFragment\"}","f":1,"l":1549798736626,"n":"main","i":1,"m":true}
{"c":"{\"action\":14,\"page\":\"HomeFragment\"}","f":1,"l":1549798746403,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"ReadWebActivity\"}","f":1,"l":1549798746476,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"HomeFragment\"}","f":1,"l":1549798764322,"n":"main","i":1,"m":true}
{"c":"{\"action\":1,\"attr\":{\"skuId\":0},\"page\":\"HomeFragment\"}","f":1,"l":1549798771282,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"CoursesTaskFragment\"}","f":1,"l":1549798771357,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"CoursesTaskFragment\"}","f":1,"l":1549799714905,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"HomeFragment\"}","f":1,"l":1549799752224,"n":"main","i":1,"m":true}
{"c":"{\"action\":1,\"attr\":{\"skuId\":0},\"page\":\"HomeFragment\"}","f":1,"l":1549799754143,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"CoursesTaskFragment\"}","f":1,"l":1549799754188,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"HomeFragment\"}","f":1,"l":1549799827697,"n":"main","i":1,"m":true}
{"c":"{\"action\":1,\"attr\":{\"skuId\":0},\"page\":\"HomeFragment\"}","f":1,"l":1549799829436,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"CoursesTaskFragment\"}","f":1,"l":1549799829480,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSDetailFragment\"}","f":1,"l":154979983{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":1549799839171,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":1549800193475,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":1549800279463,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":1549800340372,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":1549801595","f":1,"l":15cÜ7kfÇó∂hbò0279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":1549880595","f":1,"l":15cÜ7kfÇó∂hbò0279463,"n":"main","i":1,"m":true}
{"c":"{\"page\":70305bActivity\"}","f":1,"l":154980800340372,"n":"main4:"{\"page\":\"IPSWebActivity\"}","f":1,"l":154713280Activity\"}","f":1,"l":1549800279463,"n":"main"ReadWebA"n"vityvity\"}","f":1,"l":15471353bActivity\"}","f":1,"l":1549800279463,"n":"main","i":1,"m":true}
{"c":"{\"page\":736626Activity\"}","f":1,"l":154980800340372,"n":"main4:"{\"page\":\"IPSWebActivity\"}","f":1,"l":15474640bActivity\"}","f":1,"l":1549800279463,"n":"main"ReadWebA"n"vityvity\"}","f":1,"l":154746476Activity\"}","f":1,"l":1549800279463,"n":"main","i":1,"m":true}
{"c":"{\"page\":76IPSWActivity\"}","f":1,"l":154980800340372,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":15477128WActivity\"}","f":1,"l":1549800279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":154771357Activity\"}","f":1,"l":1549800279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":15971490WebActivity\"}","f":1,"l":15490279463,"n":"main","i":1,"m":true}
{"c":"{\"page\"975SWe4ebActivity\"}","f":1,"l":1549800340372,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":15975414bActivity\"}","f":1,"l":1549800279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":15975418ge\":\"IPSWebActivity\"}","f":0279463,"n":"main","i":1,"m":true}
{"c":"{\"page\"9827980e\":\"IPSWebActivity\"}","f":800340372,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":159829436Activity\"}","f":1,"l":1549800279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":159829480Activity\"}","f":1,"l":1549800279463,"n":"main"IPSDetailSWebActivity\"}","f":1,"l":159830757Activity\"}","f":1,"l":1549800279463,"n":"main"IPSDetailSWebActivity\"}","f":1,"l":8001:7674ebActivity\"}","f":1,"l":15490279463,"n":"main"IPSDetailSWebActivity\"}","f":1,"l":80027916bActivity\"}","f":1,"l":1549800279463,"n":"main"IPSDetailSWebActivity\"}","f":1,"l":80033864bActivity\"}","f":1,"l":1549800279463,"n":"main"IPSDetailSWebActivity\"}","f":1,"l":800391354ebActivity\"}","f":1,"l":15490279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":800392200Activity\"}","f":1,"l":1549800279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":801092121Activity\"}","f":1,"l":1549800279463,"n":"main","i":1,"m":true}
{"c":"{\"page801107404ebActivity\"}","f":1,"l":1549800340372,"n":"main3,,"n":"main","i":1,"m":true}
{"c":"{\"page80111138ge\":\"IPSWebActivity\"}","f":0279463,"n":"main"WatchCont":tA"n"vityvity\"}","f":1,"l":8011114295","f":1,"l":15cÜ7kfÇó∂hbò0279463,"n":"main"WatchCont":t:1,"m":true}
{"c":"{\"page801111477Activity\"}","f":1,"l":1549800279463,"n":"main"WatchCont":t:1,"m":true}
{"c":"{\"page801111481Activity\"}","f":1,"l":1549800279463,"n":"main","i":1,"m":true}
{"c":"{\"page8011151895","f":1,"l":15cÜ7kfÇó∂hbò800340372,"n":"main3,,"n":"main","i":1,"m":true}
{"c":"{\"page801116480e\":\"IPSWebActivity\"}","f":0279463,"n":"main"WatchCont":tA"n"vityvity\"}","f":1,"l":8011165295","f":1,"l":15cÜ7kfÇó∂hbò0279463,"n":"main"WatchCont":t:1,"m":true}
{"c":"{\"page801116550Activity\"}","f":1,"l":1549800279463,"n":"main"WatchCont":t:1,"m":true}
{"c":"{\"page80111655bActivity\"}","f":1,"l":1549800279463,"n":"main","i":1,"m":true}
{"c":"{\"page801122034ebActivity\"}","f":1,"l":1549800340372,"n":"main","i":1,"m":true}
{"c":"{\"page\":\"IPSWebActivity\"}","f":1,"l":801124418ebActivity\"}","f":1,"l":15490279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":8011244SWebActivity\"}","f":1,"l":15490279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":80158728WebActivity\"}","f":1,"l":15490279463,"n":"main"IPSDetailSWebActivity\"}","f":1,"l":80159028WActivity\"}","f":1,"l":1549800279463,"n":"main"IPSDetailSWebActivity\"}","f":1,"l":801621206Activity\"}","f":1,"l":1549800279463,"n":"main"CoursesTaskSWebActivity\"}","f":1,"l":801621960e\":\"IPSWebActivity\"}","f":0279463,"n":"main","i":1,"m":true}
{"c":"{\"page801622971e\":\"IPSWebActivity\"}","f":

**Comment by Richard-Cao** [comment]
只有android有这问题吗？ @littlecat1988

**Comment by littlecat1988** [comment]
> 只有android有这问题吗？ @littlecat1988

android和ios目前都有出现

**Comment by jiangteng** [comment]
方便发一个iOS完整解密后的文件？ @littlecat1988

**Comment by jiangteng** [comment]
1.你们本地测试会不会出现这种情况？
2.后端解析代码用的是什么？
3.客户端的版本号是多少？

**Comment by littlecat1988** [comment]
@jiangteng 
1.我们本地测试的时候没有出现这个问题，当然也不排除是本地测试的样本数据太小
2.后端的解析代码是根据你们提供的解析文件翻译成的go语言版本
3.logon的版本号线上的是1.1.0

**Comment by jiangteng** [comment]
把你们的加密文件用demo提供的node.js或者java版本解一下试试？
https://github.com/Meituan-Dianping/Logan/wiki/How-to-use-demo

**Comment by littlecat1988** [comment]
@jiangteng 你好，我们跑了一遍，解析的结果和我们自己的go版本的一模一样

**Comment by littlecat1988** [comment]
@Richard-Cao 你好，请问这个问题有什么解决办法么

**Comment by Richard-Cao** [comment]
目前还没找到原因，你们APP都在什么情况下记录日志呢

**Comment by Richard-Cao** [comment]
要不尝试下升个级？https://github.com/Meituan-Dianping/Logan/releases

**Comment by jiangteng** [comment]
@littlecat1988 你加一下我们微信客服助手：MTDPtech01。回复logan，她会拉你进客服群

**Comment by Pickacat** [comment]
你好，我遇到了同样的问题，日志被不同程度的截断了。

^@{"c":"Android 25,6.1.0,bd3af32d7dba9749,173b1","f":0,"l":1552786640462,"n":"main","i":1,"m":
^@{"c":"Android 23,6.1.0,33107e947f5ff2f6,e3c4f","f":0,"l":1552838746931,"n":"main","i":1,"m":
^@{"c":"15,43736,文章详情,Page End","f":1,"l":1552740723078,"n":"main","i":2,"m":true,
^@{"c":"Android 24,6.1.0,522ee617695e22e0,a8e21","f":0,"l":1552838582106,"n":"main","i":1,"m":tr
^@{"c":"Android 24,6.1.0,522ee617695e22e0,339d3","f":0,"l":1552838855773,"n":"main","i":1,"m":t
^@{"c":"Android 24,6.1.0,522ee617695e22e0,a87a7","f":0,"l":1552838858647,"n":"main","i":1,"m":t

而且你们的微信客服助手一直没有通过我的申请。

**Comment by Richard-Cao** [comment]
可以加我微信caolicheng921104，我拉你们进群

**Comment by Richard-Cao** [comment]
建议在app切换到后台的时候，Android调用Logan.f()，iOS也有类似的方法。如果还有问题，会reopen这个issue。
