### ISSUE TITLE
android 日志解析问题

### ISSUE THREAD

**Issue by chenyuzuishuai** [Meituan-Dianping/Logan#79]
我使用的node ./server.js手动解析日志  解析的时候报错，日志出现了截断问题
start decode log file
decrypt complete
remove padding complete
decode log file complete
write finish

start decode log file
decrypt complete
remove padding complete
{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:154:17) errno: -5, code: 'Z_BUF_ER
ROR' }

start decode log file
decrypt complete
remove padding complete
{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:154:17) errno: -5, code: 'Z_BUF_ER
ROR' }

start decode log file
decrypt complete
remove padding complete
{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:154:17) errno: -5, code: 'Z_BUF_ER
ROR' }

start decode log file
decrypt complete
remove padding complete
{ Error: invalid stored block lengths
    at Zlib.zlibOnError [as onerror] (zlib.js:154:17) errno: -3, code: 'Z_DATA_E
RROR' }

start decode log file
decrypt complete
请问如何解决

**Comment by Richard-Cao** [comment]
是本地测试是用的吗？

**Comment by chenyuzuishuai** [comment]
对的 本地测试

**Comment by Richard-Cao** [comment]
是直接使用Demo测试的吗？

**Comment by chenyuzuishuai** [comment]
对的  解析ios那边的日志没问题，android这边报错 ，日志截断

**Comment by Richard-Cao** [comment]
清空log再试试呢？有中途意外退出之类的么

**Comment by chenyuzuishuai** [comment]
一样的...没有中途意外退出的情况...

**Comment by Richard-Cao** [comment]
是最新的master?

**Comment by Richard-Cao** [comment]
我刚拿demo试了一下，一切正常……

**Comment by chenyuzuishuai** [comment]
抱歉最近事情有点多，我自己重现并且必现了这个问题，当我需要在application中打日志的时候（在Logan初始化之后）就会出现日志解析错误的问题，当我去掉其中的日志，能够解压出日志，希望能够在新版本解决这个问题，辛苦了

**Comment by Richard-Cao** [comment]
明白了，你是直接在application里Logan.init之后立马打了日志么

**Comment by chenyuzuishuai** [comment]
对的，这个时候日志写入应该不是完整的，所以解压会存在问题

**Comment by Richard-Cao** [comment]
好，这块儿我看一下

**Comment by Richard-Cao** [comment]
> 抱歉最近事情有点多，我自己重现并且必现了这个问题，当我需要在application中打日志的时候（在Logan初始化之后）就会出现日志解析错误的问题，当我去掉其中的日志，能够解压出日志，希望能够在新版本解决这个问题，辛苦了

我试了你这个情况，没法复现，最新的demo你看下呢
