### ISSUE TITLE
日志缺陷

### ISSUE THREAD

**Issue by zColdWater** [Meituan-Dianping/Logan#81]
Hi，各位美团的同学。

又是我，我阅读源码的逻辑后，发现个问题，Logan里面 对压缩的数据进行AES128加密，每次不足16字节的数据都保存在内存当中，当程序Crash或者断电了，这块数据就没了，是否考虑开两个mmap文件，一个保存缓存，一个保存aes不足16字节的剩余数据。 即使出现意外 还能从上次的文件里取到。

**Comment by zColdWater** [comment]
或者不用再开一个mmap，直接当前的mmap文件内 找个地方 存放16字节。

**Comment by jiangteng** [comment]
你解理的非常正确。 首先16字节存储的信息量比较少，16字节存储int的话可能存储4个int，再者客户端需要额外处理、存储，同时后端解析后需要重新拼装。所以Logan暂时没有做兼容

**Comment by zColdWater** [comment]
好的 谢谢。

**Comment by brunoduan** [comment]
每次加密增加padding方案就比较完整了。可以做兼容吧，利用logan的版本号，后端解析明文的时候，对于新版本的格式则去掉padding。
