### ISSUE TITLE
日志缺陷

### ISSUE THREAD

**Issue by XiangliJiaxing** [Meituan-Dianping/Logan#83]
LoganThread.java 中
private void doWriteLog2File(WriteAction action) {
// ......      
  long currentTime = System.currentTimeMillis(); //每隔1分钟判断一次
        if (currentTime - mLastTime > MINUTE) {
            mIsSDCard = isCanWriteSDCard();
        }
        mLastTime = System.currentTimeMillis();

        if (!mIsSDCard) { //如果大于50M 不让再次写入
            return;
        }
// ......
}
mIsSDCard 为false 时，持续性不可写入；

**Comment by Richard-Cao** [comment]
这个的问题是？没太明白不好意思……
