### ISSUE TITLE
setMaxFile文件大小设置不生效

### ISSUE THREAD

**Issue by tonghuangxx** [Meituan-Dianping/Logan#84]
setMaxFile文件的大小我设置了1M，但是实际日志超过1M还可以写入

**Comment by Richard-Cao** [comment]
超过1M之后写入了多少？

**Comment by tonghuangxx** [comment]
看了手机保存的日志是在1M左右，一开始看的是上传服务器解密后的文件有好几M了所以误认为1M限制无效了
