### ISSUE TITLE
日志丢失坏损问题

### ISSUE THREAD

**Issue by zColdWater** [Meituan-Dianping/Logan#85]
Hi 各位美团的同学，
又是我。。。  我看完代码逻辑后，我们一个日志文件有多个单元，一个单元有多条日志，当一个单元大于一个值时就会给这个单元结尾，开启下一个单元，这样会带来一个问题就是，当我一个单元还没写完，但是我突然crash了，杀掉App，那么当时的AES IV已经不知道是多少了，即使你保存起来，你再进来可能也再也接不上了，在我看来这块日志就算坏日志，那么我觉得 这样的一次 日志损失较大，其实是否可以 将每条写入数据就为一个压缩单元，这样损失的就比较小，对于后端来说，我想美团的同学 也不会直接就解析吧，应该存在一个地方，需要的时候去让服务去检索再解析吧。

**Comment by zColdWater** [comment]
方便的话 可以加qq: 1486297824  昵称: StrongHeart  交流更及时一些。

**Comment by Richard-Cao** [comment]
有没有微信呀

**Comment by zColdWater** [comment]
wechat id: azhuyongpeng
