### ISSUE TITLE
关于日志捞取问题

### ISSUE THREAD

**Issue by yihuajia** [Meituan-Dianping/Logan#88]
目前用的是1.2.1版本，看代码是通过xxxx-xx-xx这种格式来捞取对应日志的日志文件，这个对应的是0点的时间戳吧？那么问题来了，尽管是同一天，但是时间戳不一样，那不是捞不回日志了？

**Comment by yihuajia** [comment]
或者说在什么情况下会出现日志文件名不是0点的时间戳呢

**Comment by Richard-Cao** [comment]
这个是精确到天，不是具体点

**Comment by yihuajia** [comment]
@Richard-Cao 是这样的，项目有在海外运营，但是发现拉不回来，一看时间点是1点钟的时间戳而不是0点的，导致拉不回来。

**Comment by Richard-Cao** [comment]
是不是因为时差导致了天数的变化？

**Comment by yihuajia** [comment]
怀疑过，就刚好就相差一个小时的时差。那像这种情况要怎么处理呢？自己去实现日志查找那块？

**Comment by Richard-Cao** [comment]
建议给Logan.send传日期的时候，要计算好时差，是否有隔天的情况

**Comment by yihuajia** [comment]
尝试过，但是怎么都拉不回来，后来通过人肉回来的就发现日志文件名是1点钟的时间戳。还有一个问题是，有时候日志文件夹里面，同一天存在两个日志文件

**Comment by Richard-Cao** [comment]
这个我看下，是不是有可能存在这种时差导致的问题

**Comment by yihuajia** [comment]
好的，麻烦了

**Comment by Richard-Cao** [comment]
问下，你在传给send函数时间戳的时候，是精确到几点的吗？因为我们format的时候使用的是new SimpleDateFormat("yyyy-MM-dd")，只精确到天，然后这个方法默认会使用Locale.getDefault()作为Locale参数，按理说不应该存在时差的问题

**Comment by yihuajia** [comment]
我们这边是直接发送的xxxx-xx-xx这种格式的，精确到几点也没用吧？我看源码里面是直接格式化到天。但是目前海外的日志我们都拉不回来，人肉回来的不是0点的时间戳。如果日志文件名改用yyyyMMdd这种命名是不是会更好？

**Comment by yihuajia** [comment]
你好，我尝试调整设备的时区，调整为曼谷时间，比北京时间晚一个小时。发现日志文件名确实不会是0点的时间戳，而是一点的。

**Comment by Richard-Cao** [comment]
冥冥之中我感觉是Locale.getDefault()有坑……

**Comment by yihuajia** [comment]
那要怎么破，惆怅。。。但是如果是以20190410这种格式来命名呢？

**Comment by Richard-Cao** [comment]
我想想

**Comment by yangxiangnan** [comment]
触发上报时，会拷贝一份日志，如果此时出现异常，就会有2份日志存在

**Comment by walfud** [comment]
> 我想想

请问这个问题找到原因了吗?

**Comment by Richard-Cao** [comment]
> 触发上报时，会拷贝一份日志，如果此时出现异常，就会有2份日志存在

只有当天的会拷贝

**Comment by Richard-Cao** [comment]
> > 我想想
> 
> 请问这个问题找到原因了吗?

还没。

**Comment by caiqingchong1989** [comment]
不是系统的bug
long getTime ()
Returns the number of milliseconds since January 1, 1970, 00:00:00 GMT represented by this Date object
这个方法返回是格林威治的1970年7月1日到现在的时间  

楼上设置成曼谷时间后 然后用的北京时间转换 有一个小时的时差  需要减去一个小时
