### ISSUE TITLE
日志打印怎么添加换行符

### ISSUE THREAD

**Issue by tonghuangxx** [Meituan-Dianping/Logan#89]
您好，我单条日志可能包含的信息比较长，为了可读性就添加了\n的换行符，但是打印出来的日志显示的也是\n不是换行，请问怎么能打印换行符？

**Comment by jiangteng** [comment]
看一下代码怎么写的？ 是不是没有添加转义符？

**Comment by tonghuangxx** [comment]
![image](https://user-images.githubusercontent.com/6210916/54910959-5b444e00-4f28-11e9-8d88-8c1a58a6884a.png)
我打印的代码是如图这么写的，
日志的输出的话是
{"c":"0\naaaa","f":1,"l":1553508115474,"n":"Thread-6","i":25137,"m":false}
{"c":"1\naaaa","f":1,"l":1553508115479,"n":"Thread-6","i":25137,"m":false}
{"c":"2\naaaa","f":1,"l":1553508115485,"n":"Thread-6","i":25137,"m":false}
{"c":"3\naaaa","f":1,"l":1553508115490,"n":"Thread-6","i":25137,"m":false}
{"c":"4\naaaa","f":1,"l":1553508115496,"n":"Thread-6","i":25137,"m":false}

**Comment by jiangteng** [comment]
加一些转义符试试？

**Comment by tonghuangxx** [comment]
转义字符试了也是不行

**Comment by jiangteng** [comment]
试试这个 "/\n"

**Comment by tonghuangxx** [comment]
"/\n" 也没用
