### ISSUE TITLE
日志是主动上报日志文件和回捞日志文件，埋点的话怎么接入呢

### ISSUE THREAD

**Issue by pll739530476** [Meituan-Dianping/Logan#90]

**Comment by Richard-Cao** [comment]
你要埋什么点？

**Comment by pll739530476** [comment]
比如页面上面的点击曝光点击等

**Comment by Richard-Cao** [comment]
这个首先你肯定是有一个埋点系统去做的，然后可以顺手在Logan里写一份，在个案分析的时候进行分析

**Comment by pll739530476** [comment]
其实我理解Logan就是一个收集日志的系统，这个日志可以是，埋点数据，crash日志，业务日志等，然后上报上来，正对不同的日志做不同的分析，这样理解合适吗？

**Comment by Richard-Cao** [comment]
是一个日志收集系统，用来做个案分析的，和你已有的各种收集系统功能并不重复，可以看一下README和文章介绍

**Comment by pll739530476** [comment]
如果不做个案分析，利用Logan的采集和上报功能，把上报上来的日志做一些统计监控应该也可以吧。

**Comment by Richard-Cao** [comment]
也可以，但是感觉不是很适合做，毕竟收集日志是上传文件……

**Comment by pll739530476** [comment]
目前Logan后台日志不是通过文件上传的吗？

**Comment by Richard-Cao** [comment]
是的，个案分析用文件上传是比较合理的，但是如果你日常监控上报也是用文件，就有点重了

**Comment by pll739530476** [comment]
但是实时的上报也比较耗流量耗性能啊，可以定时的上报日常监控日志，每次都要找到用户主动上报，用户也比较烦，Logan回捞的话，不能监控一些机器的性能还有一些用户行为相关的日志。

在咨询个问题，Logan和腾讯的Xlog之间有做过比较和性能测试吗，哪一个性能更加

**Comment by Richard-Cao** [comment]
没有专门做过对比

**Comment by pll739530476** [comment]
好的，感谢耐心解答
