### ISSUE TITLE
Android 9.0闪退报错信息如下

### ISSUE THREAD

**Issue by HarmanJi** [Meituan-Dianping/Logan#91]
logcat日志输出信息： 
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 22017 (t.application), pid 22017 (t.application)

其中小米mix3弹出兼容性错误弹窗
Detected problems with API compatibility(visit g.co/dev/appcompat for more info)

**Comment by Richard-Cao** [comment]
是直接跑的Demo吗

**Comment by HarmanJi** [comment]
> 是直接跑的Demo吗
不是，是引入Logan后，进行了LoganConfig设置，然后进行Logan.init初始化，就会出现。目前只发现在9.0手机上会闪退，其它版本运行正常。

**Comment by Richard-Cao** [comment]
是9.0的小米吗

**Comment by HarmanJi** [comment]
> 是9.0的小米吗

是的，9.0小米MIX3

**Comment by HarmanJi** [comment]
> 是9.0的小米吗

请问有复现问题吗

**Comment by Richard-Cao** [comment]
没有……

**Comment by Richard-Cao** [comment]
我再找其他测试机查一下，有问题会更新这个issue

**Comment by HarmanJi** [comment]
> 我再找其他测试机查一下，有问题会更新这个issue

好的，主要是9.0机型

**Comment by jiangteng** [comment]
@HarmanJi 详细点日志帖一下？

**Comment by HarmanJi** [comment]
目前没有再复现了，之前出现的时候日志就是我上面提到的那些。
