### ISSUE TITLE
个人建议

### ISSUE THREAD

**Issue by Caij** [Meituan-Dianping/Logan#94]
1. 关于版本更新 希望能在项目中打个tag  release版本添加一些更新信息。 现在发现新版本也不知改了什么  需要自己看commit记录。
2.  然后希望在初始化失败能抛出异常，这样我可以初始化失败后通过自己方法写日志。

**Comment by Richard-Cao** [comment]
版本更新日志在这里：https://github.com/Meituan-Dianping/Logan/releases

**Comment by Richard-Cao** [comment]
初始化失败指的是哪些场景？

**Comment by Caij** [comment]
so或者mmap加载失败的时候。 看源码是有OnLoganProtocolStatus这个回调的。
