### ISSUE TITLE
希望有自定义接口扩展日志格式

### ISSUE THREAD

**Issue by Caij** [Meituan-Dianping/Logan#98]
现在的格式是{"c":"clogan header","f":1,"l":1538034504703,"n":"clogan","i":1,"m":true}
希望提供接口自己定义内容格式 现在的格式读来太麻烦，而且对于换行也支持不好 我打印exception，日志解析出来都变成一行了。

**Comment by jiangteng** [comment]
解析出的日志文件最好进行二次结构化解析。c中可以放个jsonString，内容格式应该能满足。目前美团点评使用是解析文件后再经过二次结构化解析展示。

**Comment by Caij** [comment]
对于二次解析的确方便， 但是就直观看日志还是不太清晰。
